BEGIN;

SELECT plan(20);

-- Final migration state: every tested SECURITY DEFINER application RPC pins
-- search_path explicitly to the trusted public schema. This is the effective
-- contract after the release hardening chain has replayed in order.
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_order search_path is pinned to public') FROM pg_proc WHERE oid='public.create_order(text,uuid,jsonb)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','transition_order search_path is pinned to public') FROM pg_proc WHERE oid='public.transition_order(uuid,public.order_status)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_category search_path is pinned to public') FROM pg_proc WHERE oid='public.create_category(text,text,uuid)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','upsert_product search_path is pinned to public') FROM pg_proc WHERE oid='public.upsert_product(uuid,text,text,text,uuid,text,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','set_product_price search_path is pinned to public') FROM pg_proc WHERE oid='public.set_product_price(uuid,public.customer_tier,numeric,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','adjust_inventory search_path is pinned to public') FROM pg_proc WHERE oid='public.adjust_inventory(uuid,uuid,integer,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_supplier search_path is pinned to public') FROM pg_proc WHERE oid='public.create_supplier(text,text,text,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_purchase_order search_path is pinned to public') FROM pg_proc WHERE oid='public.create_purchase_order(uuid,uuid,text,jsonb,text,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','submit_purchase_order search_path is pinned to public') FROM pg_proc WHERE oid='public.submit_purchase_order(uuid)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','approve_purchase_order search_path is pinned to public') FROM pg_proc WHERE oid='public.approve_purchase_order(uuid)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','receive_purchase_order search_path is pinned to public') FROM pg_proc WHERE oid='public.receive_purchase_order(uuid,text,jsonb,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_customer search_path is pinned to public') FROM pg_proc WHERE oid='public.create_customer(text,text,public.customer_tier)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','set_customer_tier search_path is pinned to public') FROM pg_proc WHERE oid='public.set_customer_tier(uuid,public.customer_tier)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','set_customer_active search_path is pinned to public') FROM pg_proc WHERE oid='public.set_customer_active(uuid,boolean)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','transfer_inventory search_path is pinned to public') FROM pg_proc WHERE oid='public.transfer_inventory(uuid,uuid,text,jsonb,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','set_stock_threshold search_path is pinned to public') FROM pg_proc WHERE oid='public.set_stock_threshold(uuid,uuid,integer,integer,integer)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_invoice_from_order search_path is pinned to public') FROM pg_proc WHERE oid='public.create_invoice_from_order(uuid,timestamptz)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','record_payment search_path is pinned to public') FROM pg_proc WHERE oid='public.record_payment(uuid,numeric,public.payment_method,uuid,text)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','record_expense search_path is pinned to public') FROM pg_proc WHERE oid='public.record_expense(uuid,uuid,text,numeric,text,text,date)'::regprocedure;
SELECT is((SELECT value FROM unnest(COALESCE(proconfig, ARRAY[]::text[])) AS value WHERE value LIKE 'search_path=%' LIMIT 1),'search_path=public','create_cash_account search_path is pinned to public') FROM pg_proc WHERE oid='public.create_cash_account(uuid,text,text,numeric)'::regprocedure;

SELECT * FROM finish();
ROLLBACK;
