begin;
select plan(10);
select ok(has_function_privilege('authenticated','public.update_supplier(uuid,text,text,text,text,boolean)','execute'),'authenticated supplier update execute');
select ok(has_function_privilege('authenticated','public.update_warehouse(uuid,text,uuid,boolean)','execute'),'authenticated warehouse update execute');
select ok(not has_function_privilege('anon','public.update_supplier(uuid,text,text,text,text,boolean)','execute'),'anon supplier update denied');
select ok(not has_function_privilege('anon','public.update_warehouse(uuid,text,uuid,boolean)','execute'),'anon warehouse update denied');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('update_supplier','update_warehouse') and p.prosecdef),2,'both update commands are SECURITY DEFINER');
select is((select count(*)::int from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('update_supplier','update_warehouse') and coalesce((select value from unnest(p.proconfig) c(value) where c.value like 'search_path=%' limit 1),'')='search_path=""'),2,'both update commands pin empty search_path');
select ok(pg_get_functiondef('public.update_supplier(uuid,text,text,text,text,boolean)'::regprocedure) ilike '%v_role not in (''owner'',''admin'')%','supplier update is owner/admin only');
select ok(pg_get_functiondef('public.update_warehouse(uuid,text,uuid,boolean)'::regprocedure) ilike '%v_role not in (''owner'',''admin'')%','warehouse update is owner/admin only');
select ok(pg_get_functiondef('public.update_supplier(uuid,text,text,text,text,boolean)'::regprocedure) ilike '%organization_id=v_org%','supplier update is tenant scoped');
select ok(pg_get_functiondef('public.update_warehouse(uuid,text,uuid,boolean)'::regprocedure) ilike '%organization_id=v_org%','warehouse update is tenant scoped');
select * from finish();
rollback;
