import { describe, expect, it } from 'vitest';
import { canMarkNotificationRead, filterAudit, filterNotifications, filterOutbox, outboxLifecycle, redactAuditMetadata, redactSensitiveText, type AuditRow, type NotificationRow, type OutboxRow } from './operations';
const notification=(overrides:Partial<NotificationRow>={}):NotificationRow=>({id:'n1',kind:'order',title:'تم تأكيد الطلب',body:'طلب #1001 أصبح مؤكدًا',entity_type:'order',entity_id:'o1',read_at:null,recipient_user_id:null,customer_id:'c1',created_at:'2026-09-25T00:00:00Z',...overrides});
describe('operations filters',()=>{
 it('filters notifications by query, kind, and unread state',()=>{expect(filterNotifications([notification(),notification({id:'n2',kind:'inventory',title:'مخزون منخفض',body:'تنبيه مخزون عام',customer_id:null})],'طلب #1001','all',false)).toHaveLength(1);expect(filterNotifications([notification(),notification({id:'n2',kind:'inventory',title:'مخزون منخفض',read_at:'2026-09-25T01:00:00Z'})],'','inventory',true)).toHaveLength(0);});
 it('only exposes mark-read controls when persistence policy can accept update',()=>{expect(canMarkNotificationRead(notification(),'customer','user-1')).toBe(true);expect(canMarkNotificationRead(notification({customer_id:null,recipient_user_id:'user-1'}),'staff','user-1')).toBe(true);expect(canMarkNotificationRead(notification({customer_id:null,recipient_user_id:'another-user'}),'staff','user-1')).toBe(false);expect(canMarkNotificationRead(notification({read_at:'2026-09-25T00:01:00Z'}),'customer','user-1')).toBe(false);});
 it('filters audit records without dropping denial/failure states',()=>{const rows:AuditRow[]=[{id:'a1',action:'order.submit',target_type:'order',target_id:'o1',result:'success',correlation_id:null,metadata:{channel:'portal'},created_at:'2026-09-25T00:00:00Z'},{id:'a2',action:'order.transition',target_type:'order',target_id:'o2',result:'denied',correlation_id:null,metadata:{reason:'role'},created_at:'2026-09-25T00:01:00Z'}];expect(filterAudit(rows,'role','all')).toHaveLength(1);expect(filterAudit(rows,'','denied')).toHaveLength(1);});
 it('redacts sensitive audit metadata and bearer tokens before display',()=>{expect(redactAuditMetadata({token:'abc',nested:{password:'xyz',safe:'ok'},text:'Bearer secret-value'})).toEqual({token:'[REDACTED]',nested:{password:'[REDACTED]',safe:'ok'},text:'Bearer [REDACTED]'});});
 it('redacts sensitive outbox errors before display',()=>{expect(redactSensitiveText('Bearer abc123 token=secret password=hidden api_key=value')).toBe('Bearer [REDACTED] token=[REDACTED] password=[REDACTED] api_key=[REDACTED]');});
 it('derives retryable, retrying, and terminal outbox lifecycle states',()=>{const base:OutboxRow={id:'x',aggregate_type:'order',aggregate_id:'o1',event_type:'order.notify',status:'pending',attempts:2,available_at:'2026-09-25T00:00:00Z',locked_until:null,last_error:'timeout',created_at:'2026-09-25T00:00:00Z',delivered_at:null};expect(outboxLifecycle(base,Date.parse('2026-09-25T00:01:00Z'))).toBe('retryable');expect(outboxLifecycle({...base,available_at:'2026-09-25T00:02:00Z'},Date.parse('2026-09-25T00:01:00Z'))).toBe('retrying');expect(outboxLifecycle({...base,status:'dead'},Date.parse('2026-09-25T00:01:00Z'))).toBe('terminal');});
 it('filters outbox records while preserving terminal failures',()=>{const rows:OutboxRow[]=[{id:'x1',aggregate_type:'order',aggregate_id:'o1',event_type:'order.confirmed',status:'delivered',attempts:1,available_at:'2026-09-25T00:00:00Z',locked_until:null,last_error:null,created_at:'2026-09-25T00:00:00Z',delivered_at:'2026-09-25T00:01:00Z'},{id:'x2',aggregate_type:'order',aggregate_id:'o2',event_type:'order.notify',status:'dead',attempts:5,available_at:'2026-09-25T00:00:00Z',locked_until:null,last_error:'timeout',created_at:'2026-09-25T00:00:00Z',delivered_at:null}];expect(filterOutbox(rows,'timeout','all')).toHaveLength(1);expect(filterOutbox(rows,'','dead')).toHaveLength(1);});
});