export type NotificationKind = 'order' | 'inventory' | 'security' | 'system' | 'task';
export type NotificationRow = { id:string; kind:NotificationKind; title:string; body:string; entity_type:string|null; entity_id:string|null; read_at:string|null; recipient_user_id:string|null; customer_id:string|null; created_at:string; };
export type AuditRow = { id:string; action:string; target_type:string; target_id:string|null; result:'success'|'failure'|'denied'; correlation_id:string|null; metadata:Record<string,unknown>; created_at:string; };
export type OutboxRow = { id:string; aggregate_type:string; aggregate_id:string; event_type:string; status:'pending'|'processing'|'delivered'|'dead'; attempts:number; available_at:string; locked_until:string|null; last_error:string|null; created_at:string; delivered_at:string|null; };
export type OutboxLifecycle = 'pending'|'retrying'|'retryable'|'processing'|'delivered'|'terminal';

export function filterNotifications(rows:NotificationRow[],query:string,kind:'all'|NotificationKind,unreadOnly:boolean){const needle=query.trim().toLocaleLowerCase();return rows.filter(row=>{if(kind!=='all'&&row.kind!==kind)return false;if(unreadOnly&&row.read_at)return false;if(!needle)return true;return [row.title,row.body,row.kind,row.entity_type??'',row.entity_id??''].join(' ').toLocaleLowerCase().includes(needle);});}
export function canMarkNotificationRead(row:NotificationRow,audience:'customer'|'staff',actorId:string|null){if(row.read_at||!actorId)return false;if(audience==='customer')return Boolean(row.customer_id);return row.recipient_user_id===actorId;}
export function filterAudit(rows:AuditRow[],query:string,result:'all'|AuditRow['result']){const needle=query.trim().toLocaleLowerCase();return rows.filter(row=>{if(result!=='all'&&row.result!==result)return false;if(!needle)return true;return [row.action,row.target_type,row.target_id??'',row.result,JSON.stringify(row.metadata)].join(' ').toLocaleLowerCase().includes(needle);});}
export function outboxLifecycle(row:OutboxRow,now=Date.now()):OutboxLifecycle{if(row.status==='dead')return 'terminal';if(row.status==='delivered')return 'delivered';if(row.status==='processing')return 'processing';const available=Date.parse(row.available_at);if(row.last_error&&Number.isFinite(available)&&available<=now)return 'retryable';if(row.last_error)return 'retrying';return 'pending';}
export function filterOutbox(rows:OutboxRow[],query:string,status:'all'|OutboxRow['status']){const needle=query.trim().toLocaleLowerCase();return rows.filter(row=>{if(status!=='all'&&row.status!==status)return false;if(!needle)return true;return [row.aggregate_type,row.aggregate_id,row.event_type,row.status,outboxLifecycle(row),redactSensitiveText(row.last_error??'')].join(' ').toLocaleLowerCase().includes(needle);});}
export function redactSensitiveText(value:string){return value.replace(/(bearer\s+)[A-Za-z0-9._-]+/gi,'$1[REDACTED]').replace(/((?:token|secret|password|authorization|api[_-]?key)\s*[=:]\s*)[^\s,}]+/gi,'$1[REDACTED]');}
export function redactAuditMetadata(value:unknown):unknown{if(Array.isArray(value))return value.map(redactAuditMetadata);if(value&&typeof value==='object'){return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>{const sensitive=/(token|secret|password|authorization|api[_-]?key|cookie)/i.test(key);return [key,sensitive?'[REDACTED]':redactAuditMetadata(item)];}));}if(typeof value==='string')return redactSensitiveText(value);return value;}
