import { useCallback, useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from 'react';
import readXlsxFile from 'read-excel-file/browser';
import type { CartLine, Product, OrderStatus } from './domain/types';
import { calculateClientPreviewTotal } from './domain/order';
import { formatMoney } from './domain/pricing';
import { getCatalog, getProductImageUrls, type CatalogItem } from './services/catalog';
import { getCategories, type CategoryOption } from './services/categories';
import { getCart, removeCartItem, setCartItem } from './services/cart';
import { createOrder } from './services/orders';
import { getCustomerOrders, type CustomerOrderSummary } from './services/customerOrders';
import { getSession, signIn, signOut } from './services/auth';
import { supabase } from './lib/supabase';
import AdminPanel from './AdminPanel';
import './styles.css';
import './customer-portal-v3.css';

type UserRole = 'owner' | 'admin' | 'sales' | 'warehouse' | 'viewer';
const STAFF_ROLES = new Set<UserRole>(['owner', 'admin', 'sales', 'warehouse']);
const STATUS_LABELS: Record<OrderStatus, string> = { draft: 'مسودة', pending: 'قيد المراجعة', confirmed: 'مؤكد', preparing: 'قيد التجهيز', ready: 'جاهز', completed: 'مكتمل', cancelled: 'ملغي' };
const STATUS_STEPS: OrderStatus[] = ['pending', 'confirmed', 'preparing', 'ready', 'completed'];
const UNIT_OPTIONS = ['حبة', 'كرتون', 'طن'];

type PriceTier = { min_quantity: number; unit_price: number; currency: string };
type TemplateLine = { productId: string; sku: string; name: string; unit: string; quantity: number };
type OrderTemplate = { id: string; name: string; branchLabel: string; lines: TemplateLine[]; updatedAt: string };
type Finance = { currency: string; creditLimit: number; outstanding: number; available: number; entries: Array<{ id: string; reference?: string; description: string; debit: number; credit: number; due_date?: string; status: string; created_at: string }> };

function mapCatalogItem(item: CatalogItem, categoryName: string, imageUrl?: string): Product & { authorizedPrice?: number } {
  return { id: item.id, sku: item.sku, name: item.name, unit: item.unit, category: categoryName, description: item.description ?? undefined, availableQuantity: item.available_quantity, status: item.status === 'active' ? 'active' : 'inactive', imageUrl, authorizedPrice: item.authorized_price ?? undefined };
}
function readLocalTemplates(customerId: string): OrderTemplate[] { try { return JSON.parse(localStorage.getItem(`aghbari:templates:${customerId}`) ?? '[]') as OrderTemplate[]; } catch { return []; } }
function writeLocalTemplates(customerId: string, templates: OrderTemplate[]) { localStorage.setItem(`aghbari:templates:${customerId}`, JSON.stringify(templates)); }
function currencyLabel(currency = 'YER') { return currency === 'YER' ? 'ر.ي' : currency; }
function statusIndex(status: OrderStatus) { return STATUS_STEPS.indexOf(status); }

export default function App() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [sessionReady, setSessionReady] = useState(false); const [signedIn, setSignedIn] = useState(false); const [role, setRole] = useState<UserRole>('viewer');
  const [authBusy, setAuthBusy] = useState(false); const [authError, setAuthError] = useState<string | null>(null);
  const [query, setQuery] = useState(''); const [catalogSearch, setCatalogSearch] = useState(''); const [categoryId, setCategoryId] = useState<string | null>(null);
  const [categoryOptions, setCategoryOptions] = useState<CategoryOption[]>([]); const [products, setProducts] = useState<Product[]>([]); const [serverPrices, setServerPrices] = useState<Record<string, number>>({}); const [priceTiers, setPriceTiers] = useState<Record<string, PriceTier[]>>({});
  const [catalogLoading, setCatalogLoading] = useState(false); const [cart, setCart] = useState<CartLine[]>([]); const [checkoutKey, setCheckoutKey] = useState<string | null>(null); const [warehouseId, setWarehouseId] = useState<string | null>(null); const [customerId, setCustomerId] = useState<string | null>(null);
  const [customerName, setCustomerName] = useState('تاجر الأغبري'); const [customerTier, setCustomerTier] = useState('wholesale'); const [orders, setOrders] = useState<CustomerOrderSummary[]>([]); const [ordersLoading, setOrdersLoading] = useState(false); const [ordersError, setOrdersError] = useState<string | null>(null);
  const [finance, setFinance] = useState<Finance | null>(null); const [financeLoading, setFinanceLoading] = useState(false); const [templates, setTemplates] = useState<OrderTemplate[]>([]); const [templateName, setTemplateName] = useState('');
  const [quickOrderOpen, setQuickOrderOpen] = useState(false); const [cartOpen, setCartOpen] = useState(false); const [section, setSection] = useState<'catalog' | 'orders' | 'finance' | 'templates'>('catalog');
  const [runtimeError, setRuntimeError] = useState<string | null>(null); const [orderBusy, setOrderBusy] = useState(false); const [orderResult, setOrderResult] = useState<string | null>(null); const [isOnline, setIsOnline] = useState(() => typeof navigator === 'undefined' ? true : navigator.onLine);

  const loadIdentity = useCallback(async (userId: string) => {
    if (!supabase) return;
    const { data: profile, error } = await supabase.from('profiles').select('customer_id, role').eq('id', userId).single();
    if (error) throw error;
    setCustomerId(profile.customer_id); setRole((profile.role as UserRole) ?? 'viewer');
    if (profile.customer_id) {
      const { data: customer } = await supabase.from('customers').select('name,tier').eq('id', profile.customer_id).maybeSingle();
      if (customer) { setCustomerName(customer.name); setCustomerTier(String(customer.tier ?? 'wholesale')); }
      setTemplates(readLocalTemplates(profile.customer_id));
    }
  }, []);

  useEffect(() => {
    let cancelled = false;
    void getSession().then(async (currentSession) => { if (cancelled) return; setSignedIn(Boolean(currentSession)); setSessionReady(true); if (currentSession) await loadIdentity(currentSession.user.id); }).catch((error) => { if (!cancelled) { setSessionReady(true); setAuthError(error instanceof Error ? error.message : 'تعذر قراءة جلسة الدخول.'); } });
    const listener = supabase?.auth.onAuthStateChange((event, nextSession) => { if (cancelled) return; setSignedIn(Boolean(nextSession)); if (nextSession && (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED')) void loadIdentity(nextSession.user.id).catch((error) => setAuthError(error instanceof Error ? error.message : 'تعذر تحميل هوية الحساب.')); else if (!nextSession) { setCustomerId(null); setRole('viewer'); setProducts([]); setCart([]); setOrders([]); setTemplates([]); setFinance(null); } });
    return () => { cancelled = true; listener?.data.subscription.unsubscribe(); };
  }, [loadIdentity]);
  useEffect(() => { const on = () => setIsOnline(true); const off = () => setIsOnline(false); window.addEventListener('online', on); window.addEventListener('offline', off); return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off); }; }, []);
  useEffect(() => { if (!signedIn) return; const timer = window.setTimeout(() => setCatalogSearch(query.trim()), 220); return () => window.clearTimeout(timer); }, [query, signedIn]);

  useEffect(() => {
    if (!signedIn || !supabase || !isOnline || STAFF_ROLES.has(role)) return; let cancelled = false;
    async function loadRuntime() {
      setCatalogLoading(true); setRuntimeError(null);
      try {
        const [{ data: warehouse, error: warehouseError }, items, savedCart, categories] = await Promise.all([
          supabase!.from('warehouses').select('id').eq('is_active', true).order('created_at').limit(1).maybeSingle(), getCatalog(catalogSearch, categoryId, 60, 0), getCart(), getCategories()
        ]);
        if (warehouseError) throw warehouseError; if (!warehouse?.id) throw new Error('لا يوجد مستودع تشغيلي نشط.'); if (cancelled) return;
        const categoryMap = new Map(categories.map((item) => [item.id, item.name])); const imageUrls = await getProductImageUrls(items.map((item) => item.image_path));
        const mapped = items.map((item) => mapCatalogItem(item, categoryMap.get(item.category_id ?? '') ?? 'أصناف', item.image_path ? imageUrls.get(item.image_path) : undefined));
        setWarehouseId(warehouse.id); setCategoryOptions(categories); setProducts(mapped); setServerPrices(Object.fromEntries(items.map((item) => [item.id, item.authorized_price ?? 0])));
        setCart(savedCart.map((item) => ({ product: mapped.find((product) => product.id === item.product_id) ?? { id: item.product_id, sku: item.sku, name: item.name, unit: item.unit, category: 'أصناف', availableQuantity: 0, status: 'active' }, quantity: item.quantity, unitPrice: item.authorized_price ?? 0 })));
        if (customerId && items.length) { const { data: tiers } = await supabase.from('customer_price_tiers').select('product_id,min_quantity,unit_price,currency').eq('customer_id', customerId).in('product_id', items.map((item) => item.id)).order('min_quantity'); const grouped: Record<string, PriceTier[]> = {}; for (const row of tiers ?? []) (grouped[row.product_id] ??= []).push({ min_quantity: Number(row.min_quantity), unit_price: Number(row.unit_price), currency: row.currency }); if (!cancelled) setPriceTiers(grouped); }
      } catch (error) { if (!cancelled) setRuntimeError(error instanceof Error ? error.message : 'تعذر تحميل بيانات المتجر.'); }
      finally { if (!cancelled) setCatalogLoading(false); }
    }
    void loadRuntime(); return () => { cancelled = true; };
  }, [catalogSearch, categoryId, signedIn, isOnline, customerId, role]);

  useEffect(() => {
    if (!signedIn || !isOnline || STAFF_ROLES.has(role)) return; let cancelled = false; setOrdersLoading(true); setOrdersError(null);
    void getCustomerOrders(30).then((items) => { if (!cancelled) setOrders(items); }).catch((error) => { if (!cancelled) setOrdersError(error instanceof Error ? error.message : 'تعذر تحميل الطلبات.'); }).finally(() => { if (!cancelled) setOrdersLoading(false); });
    return () => { cancelled = true; };
  }, [signedIn, isOnline, role, orderResult]);

  useEffect(() => {
    if (!signedIn || !customerId || !supabase || STAFF_ROLES.has(role)) return; let cancelled = false; setFinanceLoading(true);
    void (async () => { try { const [{ data: account, error: accountError }, { data: entries, error: entriesError }] = await Promise.all([supabase!.from('customer_credit_accounts').select('currency,credit_limit,outstanding_balance,available_credit').eq('customer_id', customerId).maybeSingle(), supabase!.from('customer_ledger_entries').select('id,reference,description,debit,credit,due_date,status,created_at').eq('customer_id', customerId).order('created_at', { ascending: false }).limit(50)]); if (accountError || entriesError) throw accountError ?? entriesError; if (!cancelled) setFinance(account ? { currency: account.currency, creditLimit: Number(account.credit_limit), outstanding: Number(account.outstanding_balance), available: Number(account.available_credit), entries: (entries ?? []).map((e) => ({ ...e, debit: Number(e.debit), credit: Number(e.credit) })) } : null); } catch { if (!cancelled) setFinance(null); } finally { if (!cancelled) setFinanceLoading(false); } })();
    return () => { cancelled = true; };
  }, [signedIn, customerId, role]);

  const categories = useMemo(() => [{ id: null, name: 'الكل' }, ...categoryOptions], [categoryOptions]);
  const priceFor = (product: Product) => serverPrices[product.id] ?? 0; const total = calculateClientPreviewTotal(cart); const cartCount = cart.reduce((sum, line) => sum + line.quantity, 0);
  function nextTier(product: Product, quantity: number) { return (priceTiers[product.id] ?? []).filter((tier) => tier.min_quantity > quantity).sort((a, b) => a.min_quantity - b.min_quantity)[0]; }
  function effectivePrice(product: Product, quantity = 1) { const tiers = priceTiers[product.id] ?? []; return [...tiers].sort((a, b) => b.min_quantity - a.min_quantity).find((tier) => quantity >= tier.min_quantity)?.unit_price ?? priceFor(product); }
  function savingHint(product: Product) { const quantity = cart.find((line) => line.product.id === product.id)?.quantity ?? 1; const tier = nextTier(product, quantity); return tier ? `أضف ${tier.min_quantity - quantity} ${product.unit} للوصول إلى ${formatMoney(tier.unit_price)} ${currencyLabel(tier.currency)}` : 'أنت على أفضل سعر متاح لحسابك'; }

  async function handleLogin(event: FormEvent) { event.preventDefault(); setAuthBusy(true); setAuthError(null); try { const session = await signIn(email.trim(), password); if (session) await loadIdentity(session.user.id); setPassword(''); } catch (error) { setAuthError(error instanceof Error ? error.message : 'تعذر تسجيل الدخول.'); } finally { setAuthBusy(false); } }
  async function handleSignOut() { try { await signOut(); } finally { setProducts([]); setCart([]); setOrders([]); setCustomerId(null); setRole('viewer'); setTemplates([]); setFinance(null); } }
  async function addToCart(product: Product, quantity = 1) { const price = effectivePrice(product, quantity); if (price <= 0 || product.availableQuantity < quantity || !isOnline) return; const existing = cart.find((line) => line.product.id === product.id); const next = Math.min((existing?.quantity ?? 0) + quantity, product.availableQuantity); try { await setCartItem(product.id, next); setCart((current) => existing ? current.map((line) => line.product.id === product.id ? { ...line, quantity: next, unitPrice: effectivePrice(product, next) } : line) : [...current, { product, quantity: next, unitPrice: price }]); setCartOpen(true); setRuntimeError(null); } catch (error) { setRuntimeError(error instanceof Error ? error.message : 'تعذر تحديث السلة.'); } }
  async function updateQuantity(id: string, quantity: number) { const line = cart.find((item) => item.product.id === id); if (!line) return; const next = Math.max(0, Math.min(quantity, line.product.availableQuantity)); try { if (!next) { await removeCartItem(id); setCart((c) => c.filter((item) => item.product.id !== id)); } else { await setCartItem(id, next); setCart((c) => c.map((item) => item.product.id === id ? { ...item, quantity: next, unitPrice: effectivePrice(item.product, next) } : item)); } } catch (error) { setRuntimeError(error instanceof Error ? error.message : 'تعذر تحديث السلة.'); } }
  async function submitOrder() { if (!isOnline) { setRuntimeError('إرسال الطلب يحتاج اتصالًا بالإنترنت.'); return; } if (!customerId || !warehouseId || !cart.length || orderBusy) return; setOrderBusy(true); setRuntimeError(null); const idempotencyKey = checkoutKey ?? crypto.randomUUID(); setCheckoutKey(idempotencyKey); try { const result = await createOrder({ customerId, idempotencyKey, lines: cart.map((line) => ({ productId: line.product.id, quantity: line.quantity })) }, warehouseId); setCart([]); setCheckoutKey(null); setCartOpen(false); setOrderResult(`تم إرسال الطلب #${result.order_number} بنجاح.`); setSection('orders'); } catch (error) { setRuntimeError(error instanceof Error ? error.message : 'تعذر إرسال الطلب.'); } finally { setOrderBusy(false); } }
  async function reorder(order: CustomerOrderSummary) { setRuntimeError(`إعادة الطلب #${order.order_number} تتطلب تفاصيل الأصناف من مصدر الطلب قبل إعادة إضافتها بأمان.`); }
  async function saveTemplate() { if (!customerId || !cart.length || !templateName.trim()) return; const template: OrderTemplate = { id: crypto.randomUUID(), name: templateName.trim(), branchLabel: 'الفرع الرئيسي', lines: cart.map((line) => ({ productId: line.product.id, sku: line.product.sku, name: line.product.name, unit: line.product.unit, quantity: line.quantity })), updatedAt: new Date().toISOString() }; const next = [template, ...templates].slice(0, 30); setTemplates(next); writeLocalTemplates(customerId, next); setTemplateName(''); setRuntimeError(null); }
  async function applyTemplate(template: OrderTemplate) { for (const line of template.lines) { const product = products.find((item) => item.id === line.productId); if (product) await addToCart(product, Math.min(line.quantity, product.availableQuantity)); } setSection('catalog'); }
  function downloadStatement() { if (!finance) return; const rows = [['المرجع','البيان','مدين','دائن','الاستحقاق','الحالة'], ...finance.entries.map((e) => [e.reference ?? '-', e.description, String(e.debit), String(e.credit), e.due_date ?? '-', e.status])]; const csv = '\ufeff' + rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `aghbari-statement-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }
  async function importExcel(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { const rows = await readXlsxFile(file); const header = rows[0]?.map((x) => String(x ?? '').trim().toLowerCase()) ?? []; const skuIndex = header.findIndex((x) => ['sku','الكود','كود الصنف'].includes(x)); const qtyIndex = header.findIndex((x) => ['quantity','qty','الكمية'].includes(x)); if (skuIndex < 0 || qtyIndex < 0) throw new Error('ملف Excel يجب أن يحتوي على عمودي SKU والكمية.'); let added = 0; for (const row of rows.slice(1)) { const sku = String(row[skuIndex] ?? '').trim(); const quantity = Number(row[qtyIndex]); const product = products.find((item) => item.sku === sku); if (product && Number.isSafeInteger(quantity) && quantity > 0) { await addToCart(product, Math.min(quantity, product.availableQuantity)); added++; } } setRuntimeError(added ? `تمت مطابقة ${added} أصناف من ملف Excel.` : 'لم تتم مطابقة أي صنف.'); } catch (error) { setRuntimeError(error instanceof Error ? error.message : 'تعذر قراءة ملف Excel.'); } }

  if (!sessionReady) return <div className="auth-shell"><div className="auth-card"><span className="eyebrow">بوابة الأغبري</span><h1>جارٍ التحقق…</h1><p>يتم التحقق من الجلسة قبل عرض بيانات المتجر.</p></div></div>;
  if (!signedIn) return <div className="auth-shell"><form className="auth-card" onSubmit={handleLogin}><span className="eyebrow">بوابة الأغبري التجارية</span><h1>دخول التاجر</h1><p>الوصول إلى الكتالوج والأسعار والطلبات المصرح بها لحسابك.</p><label>البريد الإلكتروني<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>كلمة المرور<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label>{authError && <div className="error-banner">{authError}</div>}<button className="checkout" disabled={authBusy}>{authBusy ? 'جارٍ الدخول…' : 'دخول آمن'}</button></form></div>;
  if (STAFF_ROLES.has(role)) return <div className="app-shell"><AdminPanel role={role} /></div>;

  return <div className="customer-app" dir="rtl">
    <header className="customer-topbar"><div className="customer-brand"><span className="brand-mark">أ</span><div><strong>بوابة الأغبري التجارية</strong><small>منصة الجملة والطلبات الذكية</small></div></div><label className="global-search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث عن المنتج، SKU أو الباركود..." aria-label="بحث المنتج"/><kbd>Ctrl K</kbd></label><div className="customer-actions"><button onClick={() => setSection('orders')} className="icon-action">طلباتي</button><button onClick={() => setCartOpen(true)} className="cart-action">السلة <b>{cartCount}</b></button><button onClick={() => void handleSignOut()} className="signout">خروج</button></div></header>
    {!isOnline && <div className="offline-banner">أنت دون اتصال. يمكن تعديل السلة محليًا، أما إرسال الطلب فيحتاج اتصالًا.</div>}
    <main className="customer-main">
      <section className="customer-welcome"><div><span className="eyebrow">مرحبًا، {customerName}</span><h1>احتياج متجرك<br/><em>جاهز للطلب.</em></h1><p>أسعار الجملة والمخزون والخصومات المصرح بها لحسابك في مكان واحد.</p><div className="welcome-actions"><button onClick={() => setQuickOrderOpen(true)}>⚡ طلب سريع</button><button className="secondary" onClick={() => setSection('templates')}>↻ إعادة طلب محفوظ</button></div></div><div className="credit-mini"><span>المتاح الائتماني</span><strong>{finance ? formatMoney(finance.available) : '—'}</strong><small>{finance ? `من حد ${formatMoney(finance.creditLimit)} ${currencyLabel(finance.currency)}` : 'المعلومات المالية ستظهر بعد مزامنة المركز المالي'}</small></div></section>
      {runtimeError && <div className="error-banner">{runtimeError}</div>}
      <section className="customer-nav"><button className={section === 'catalog' ? 'nav-pill active' : 'nav-pill'} onClick={() => setSection('catalog')}>الكتالوج</button><button className={section === 'orders' ? 'nav-pill active' : 'nav-pill'} onClick={() => setSection('orders')}>طلباتي <span>{orders.length}</span></button><button className={section === 'templates' ? 'nav-pill active' : 'nav-pill'} onClick={() => setSection('templates')}>المسحات</button><button className={section === 'finance' ? 'nav-pill active' : 'nav-pill'} onClick={() => setSection('finance')}>المركز المالي</button></section>
      {section === 'catalog' && <><section className="catalog-toolbar"><div><h2>الكتالوج السريع</h2><p>ابحث بالاسم أو SKU أو الباركود، ثم أضف الكمية مباشرة.</p></div><div className="toolbar-actions"><label className="upload-button">رفع Excel<input type="file" accept=".xlsx,.xls" onChange={importExcel} hidden/></label><button onClick={() => setQuickOrderOpen(true)}>طلب سريع</button></div></section><div className="category-strip">{categories.map((item) => <button key={item.id ?? 'all'} className={item.id === categoryId ? 'category-chip active' : 'category-chip'} onClick={() => setCategoryId(item.id)}>{item.name}</button>)}</div><section className="product-grid" aria-busy={catalogLoading}>{catalogLoading && <div className="empty-state">جارٍ تحميل الكتالوج…</div>}{!catalogLoading && products.map((product) => { const price = effectivePrice(product); const tier = nextTier(product, 1); return <article className="b2b-product-card" key={product.id}><div className="product-visual">{product.imageUrl ? <img src={product.imageUrl} alt={product.name} loading="lazy"/> : <span>{product.name.slice(0,1)}</span>}<span className={product.availableQuantity > 20 ? 'stock-badge good' : product.availableQuantity > 0 ? 'stock-badge low' : 'stock-badge out'}>{product.availableQuantity > 20 ? 'متوفر' : product.availableQuantity > 0 ? 'مخزون منخفض' : 'غير متوفر'}</span></div><div className="b2b-product-info"><div className="sku-row"><span>{product.category}</span><code>{product.sku}</code></div><h3>{product.name}</h3><p>{product.description ?? 'توريد جملة مباشر من مخزون الأغبري.'}</p><div className="unit-row">{UNIT_OPTIONS.map((unit) => <span key={unit} className={product.unit === unit ? 'unit-tag active' : 'unit-tag'}>{unit}</span>)}</div><div className="price-row"><div><small>سعر حسابك</small><strong>{price > 0 ? `${formatMoney(price)} ${currencyLabel()}` : 'غير متاح'}</strong></div><button disabled={price <= 0 || product.availableQuantity < 1 || !isOnline} onClick={() => void addToCart(product)}>+ إضافة</button></div>{tier && <div className="tier-hint">✦ {savingHint(product)}</div>}</div></article>; })}{!catalogLoading && !products.length && <div className="empty-state">لا توجد أصناف مطابقة للبحث الحالي.</div>}</section></>}
      {section === 'orders' && <section className="content-card"><div className="section-title"><div><span className="eyebrow">المتابعة</span><h2>طلباتك وشحناتك</h2></div><span>{orders.length} طلبًا</span></div>{ordersLoading ? <div className="empty-state">جارٍ تحميل الطلبات…</div> : ordersError ? <div className="error-banner">{ordersError}</div> : !orders.length ? <div className="empty-state">لا توجد طلبات سابقة بعد.</div> : <div className="orders-list">{orders.map((order) => { const idx = statusIndex(order.status); return <article className="order-card" key={order.id}><div className="order-head"><strong>طلب #{order.order_number}</strong><span>{formatMoney(order.total)} {currencyLabel(order.currency)}</span></div><small>{new Date(order.created_at).toLocaleString('ar-YE')}</small><div className="timeline">{STATUS_STEPS.map((step, i) => <div key={step} className={idx >= i ? 'timeline-step done' : 'timeline-step'}><span>{idx >= i ? '✓' : '•'}</span><label>{step === 'pending' ? 'جديد' : step === 'confirmed' ? 'مؤكد' : step === 'preparing' ? 'قيد التجهيز' : step === 'ready' ? 'قيد الشحن' : 'مكتمل'}</label></div>)}</div><div className="order-footer"><span className={`status status-${order.status}`}>{STATUS_LABELS[order.status]}</span><button onClick={() => void reorder(order)}>إعادة الطلب</button></div></article>; })}</div>}</section>}
      {section === 'templates' && <section className="content-card"><div className="section-title"><div><span className="eyebrow">طلباتك المتكررة</span><h2>المسحات الجاهزة</h2></div><button onClick={() => setSection('catalog')}>+ أنشئ من السلة</button></div>{templates.length ? <div className="template-grid">{templates.map((template) => <article className="template-card" key={template.id}><span className="template-icon">▦</span><h3>{template.name}</h3><small>{template.lines.length} أصناف · {template.branchLabel}</small><div><button onClick={() => void applyTemplate(template)}>إعادة الطلب</button><button className="ghost" onClick={() => { const next = templates.filter((item) => item.id !== template.id); setTemplates(next); if (customerId) writeLocalTemplates(customerId, next); }}>حذف</button></div></article>)}</div> : <div className="empty-state">لا توجد مسحات محفوظة. أضف أصنافًا إلى السلة ثم احفظها كطلب متكرر.</div>}<div className="template-save"><input value={templateName} onChange={(e) => setTemplateName(e.target.value)} placeholder="اسم المسحة الجديدة"/><button disabled={!templateName.trim() || !cart.length} onClick={() => void saveTemplate()}>حفظ السلة كمسحة</button></div></section>}
      {section === 'finance' && <section className="content-card"><div className="section-title"><div><span className="eyebrow">الثقة المالية</span><h2>المركز المالي</h2></div><button onClick={downloadStatement} disabled={!finance}>تنزيل الكشف</button></div>{financeLoading ? <div className="empty-state">جارٍ تحميل المركز المالي…</div> : <>{finance ? <><div className="finance-grid"><div><small>الحد الائتماني</small><strong>{formatMoney(finance.creditLimit)} {currencyLabel(finance.currency)}</strong></div><div><small>الرصيد المستحق</small><strong>{formatMoney(finance.outstanding)} {currencyLabel(finance.currency)}</strong></div><div><small>المتاح للشراء</small><strong>{formatMoney(finance.available)} {currencyLabel(finance.currency)}</strong></div></div><div className="ledger-table">{finance.entries.map((entry) => <div className="ledger-row" key={entry.id}><span>{entry.reference ?? '—'}</span><strong>{entry.description}</strong><span>{entry.debit ? `مدين ${formatMoney(entry.debit)}` : `دائن ${formatMoney(entry.credit)}`}</span><span>{entry.due_date ?? '—'}</span><span className={`status status-${entry.status}`}>{entry.status === 'overdue' ? 'متأخر' : entry.status === 'paid' ? 'مسدد' : 'مفتوح'}</span></div>)}</div></> : <div className="empty-state">لا توجد بيانات مركز مالي متاحة لحسابك حاليًا.</div>}</>}</section>}
    </main>
    {quickOrderOpen && <div className="modal-backdrop" onClick={() => setQuickOrderOpen(false)}><section className="modal" onClick={(e) => e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">Quick Order</span><h2>الطلب السريع</h2></div><button onClick={() => setQuickOrderOpen(false)}>×</button></div><p>أدخل SKU والكمية لإضافة أصناف كثيرة بسرعة.</p><QuickOrderEditor products={products} onAdd={addToCart} onClose={() => setQuickOrderOpen(false)}/></section></div>}
    {cartOpen && <div className="drawer-backdrop" onClick={() => setCartOpen(false)}><aside className="cart-drawer" onClick={(e) => e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">سلة الشراء</span><h2>{cartCount} وحدة</h2></div><button onClick={() => setCartOpen(false)}>×</button></div>{!cart.length ? <div className="empty-state">السلة فارغة.</div> : <>{cart.map((line) => <div className="drawer-line" key={line.product.id}><div><strong>{line.product.name}</strong><small>{formatMoney(line.unitPrice)} / {line.product.unit}</small></div><div className="quantity"><button onClick={() => void updateQuantity(line.product.id, line.quantity - 1)}>−</button><span>{line.quantity}</span><button onClick={() => void updateQuantity(line.product.id, line.quantity + 1)}>+</button></div><strong>{formatMoney(line.unitPrice * line.quantity)}</strong></div>)}<div className="drawer-total"><span>الإجمالي</span><strong>{formatMoney(total)} ر.ي</strong></div><label className="template-inline"><input value={templateName} onChange={(e) => setTemplateName(e.target.value)} placeholder="اسم المسحة (اختياري)"/><button disabled={!templateName.trim()} onClick={() => void saveTemplate()}>حفظ</button></label><button className="checkout" disabled={orderBusy || !customerId || !warehouseId || !isOnline} onClick={() => void submitOrder()}>{orderBusy ? 'جارٍ اعتماد الطلب…' : 'تأكيد وإرسال الطلب'}</button></>}</aside></div>}
    <footer className="customer-footer"><span>بوابة الأغبري التجارية</span><span>حساب {customerTier === 'wholesale' ? 'جملة' : customerTier}</span><span>{isOnline ? '● متصل' : '○ دون اتصال'}</span></footer>
  </div>;
}

function QuickOrderEditor({ products, onAdd, onClose }: { products: Product[]; onAdd: (product: Product, quantity?: number) => Promise<void>; onClose: () => void }) {
  const [rows, setRows] = useState([{ sku: '', quantity: 1 }]);
  return <div className="quick-editor">{rows.map((row, index) => <div className="quick-row" key={index}><input value={row.sku} onChange={(e) => setRows((r) => r.map((item, i) => i === index ? { ...item, sku: e.target.value } : item))} placeholder="SKU"/><input type="number" min="1" value={row.quantity} onChange={(e) => setRows((r) => r.map((item, i) => i === index ? { ...item, quantity: Number(e.target.value) } : item))}/><button disabled={!products.find((p) => p.sku === row.sku) || row.quantity < 1} onClick={() => { const product = products.find((p) => p.sku === row.sku); if (product) void onAdd(product, row.quantity); }}>إضافة</button></div>)}<div className="quick-actions"><button className="ghost" onClick={() => setRows((r) => [...r, { sku: '', quantity: 1 }])}>+ سطر</button><button onClick={onClose}>تم</button></div></div>;
}
