import { lazy, Suspense, useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import readXlsxFile from './lib/read-excel-file-browser';
import type { CartLine, Product } from './domain/types';
import { calculateClientPreviewTotal } from './domain/order';
import { formatMoney } from './domain/pricing';
import { getCatalog, getProductImageUrls, type CatalogItem } from './services/catalog';
import { getCategories, type CategoryOption } from './services/categories';
import { getCart, removeCartItem, setCartItem, syncOfflineCart } from './services/cart';
import { createOrder } from './services/orders';
import { applyQuickOrder } from './services/quickOrder';
import { getCustomerOrderDetail, type CustomerOrderDetail, type CustomerOrderSummary } from './services/customerOrders';
import { getSession, signIn, signOut } from './services/auth';
import { createOrderTemplate, deleteOrderTemplate, getOrderTemplates, applyOrderTemplate, type OrderTemplate } from './services/orderTemplates';
import { supabase } from './lib/supabase';
const AdminPanel = lazy(() => import('./AdminPanel'));
import CustomerOrdersPanel from './CustomerOrdersPanel';
import './customer-orders.css';
import NotificationPanel from './NotificationPanel';
import OfflineRecoveryPanel from './OfflineRecoveryPanel';
import './styles.css';
import './customer-portal-v3.css';
import './customer-portal-v3-dynamic.css';
import './customer-account-catalog.css';

type UserRole = 'owner' | 'admin' | 'sales' | 'warehouse' | 'viewer' | 'customer';
type PortalSection = 'catalog' | 'orders' | 'finance' | 'templates' | 'account' | 'notifications';
const PORTAL_SECTION_META: Record<PortalSection,{label:string;eyebrow:string;hint:string}> = { catalog:{label:'الكتالوج',eyebrow:'التسوق',hint:'اكتشف الأصناف والأسعار والمخزون ثم أضف الكميات مباشرة.'}, orders:{label:'طلباتي',eyebrow:'المتابعة',hint:'راجع الطلبات الحالية والسجل والتتبع وإعادة الطلب.'}, finance:{label:'المركز المالي',eyebrow:'الثقة المالية',hint:'راجع الرصيد والائتمان والحركات المالية المتاحة لحسابك.'}, templates:{label:'المسحات الجاهزة',eyebrow:'طلبات متكررة',hint:'أعد تطبيق طلباتك المحفوظة بضغطة واحدة.'}, account:{label:'حسابي',eyebrow:'سياق الحساب',hint:'الهوية والاتصال والمستودع وحالات الاسترداد.'}, notifications:{label:'الإشعارات',eyebrow:'التشغيل',hint:'تابع التنبيهات المرتبطة بالحساب والطلبات.'} };
const PORTAL_SECTIONS = new Set<PortalSection>(['catalog', 'orders', 'finance', 'templates', 'account', 'notifications']);
const sectionFromHash = (): PortalSection => {
  if (typeof window === 'undefined') return 'catalog';
  const value = window.location.hash.replace(/^#/, '') as PortalSection;
  return PORTAL_SECTIONS.has(value) ? value : 'catalog';
};
const STAFF_ROLES = new Set<UserRole>(['owner', 'admin', 'sales', 'warehouse']);
type PriceTier = { min_quantity: number; unit_price: number; currency: string };
type Finance = { currency: string; creditLimit: number; outstanding: number; available: number; entries: Array<{ id: string; reference?: string; description: string; debit: number; credit: number; due_date?: string; status: string; created_at: string }> };
type ClientUiConfig = {
  showSearch:boolean; showCategories:boolean; showExcel:boolean; showCredit:boolean; showTemplates:boolean; showInventory:boolean; showRetailPrice:boolean; showQuickOrder:boolean;
  requireQuantityConfirmation:boolean; showTieredPricing:boolean; showSavingsCalculator:boolean; showImageSearch:boolean; showVoiceSearch:boolean; showPaymentMethods:boolean;
  paymentOnCredit:boolean; paymentCash:boolean; paymentTransfer:boolean; minOrderValue:number; maxOrderValue:number; maxTemplates:number;
};
const DEFAULT_UI_CONFIG: ClientUiConfig = { showSearch:true, showCategories:true, showExcel:true, showCredit:true, showTemplates:true, showInventory:true, showRetailPrice:false, showQuickOrder:true, requireQuantityConfirmation:true, showTieredPricing:true, showSavingsCalculator:true, showImageSearch:false, showVoiceSearch:false, showPaymentMethods:true, paymentOnCredit:true, paymentCash:true, paymentTransfer:true, minOrderValue:0, maxOrderValue:0, maxTemplates:50 };
const PAYMENT_OPTIONS = [{key:'credit' as const,label:'آجل / ائتمان',field:'paymentOnCredit' as const},{key:'cash' as const,label:'نقدي',field:'paymentCash' as const},{key:'transfer' as const,label:'حوالة',field:'paymentTransfer' as const}];
function mapProduct(item: CatalogItem, categoryName: string, imageUrl?: string): Product { return { id:item.id, sku:item.sku, name:item.name, unit:item.unit, category:categoryName, description:item.description ?? undefined, availableQuantity:item.available_quantity, status:item.status === 'active' ? 'active' : 'inactive', imageUrl }; }
function money(value:number,currency='YER'){return `${formatMoney(value)} ${currency==='YER'?'ر.ي':currency}`;}
type QuickExcelLine = { identifier:string; quantity:number; product:Product|null; error:string|null };
const CATALOG_PAGE_SIZE=24;
type VoiceRecognitionResult = { results: ArrayLike<ArrayLike<{ transcript: string }>> };
type VoiceRecognition = {
  lang: string;
  interimResults: boolean;
  maxAlternatives: number;
  start: () => void;
  stop: () => void;
  onresult: ((event: VoiceRecognitionResult) => void) | null;
  onerror: ((event: { error?: string }) => void) | null;
  onend: (() => void) | null;
};
type VoiceRecognitionConstructor = new () => VoiceRecognition;

export default function AppV3Fixed(){
  const [sessionUserId,setSessionUserId]=useState<string|null>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [signedIn,setSignedIn]=useState(false); const [ready,setReady]=useState(false); const [role,setRole]=useState<UserRole>('viewer'); const [customerId,setCustomerId]=useState<string|null>(null); const [organizationId,setOrganizationId]=useState<string|null>(null); const [warehouseId,setWarehouseId]=useState<string|null>(null); const [customerName,setCustomerName]=useState('تاجر الأغبري');
  const [config,setConfig]=useState<ClientUiConfig>(DEFAULT_UI_CONFIG); const [catalogView,setCatalogView]=useState<'grid'|'compact'>('grid'); const [catalogSort,setCatalogSort]=useState<'relevance'|'name'|'stock'>('relevance'); const [query,setQuery]=useState(''); const [catalogPage,setCatalogPage]=useState(0); const [catalogHasMore,setCatalogHasMore]=useState(false); const [categoryId,setCategoryId]=useState<string|null>(null); const [categories,setCategories]=useState<CategoryOption[]>([]); const [products,setProducts]=useState<Product[]>([]); const [tiers,setTiers]=useState<Record<string,PriceTier[]>>({}); const [cart,setCart]=useState<CartLine[]>([]); const [cartOpen,setCartOpen]=useState(false); const [quickOpen,setQuickOpen]=useState(false); const [excelOpen,setExcelOpen]=useState(false); const [excelRows,setExcelRows]=useState<QuickExcelLine[]>([]); const [excelBusy,setExcelBusy]=useState(false); const [section,setSection]=useState<PortalSection>(sectionFromHash()); const [selectedOrder,setSelectedOrder]=useState<CustomerOrderDetail|null>(null); const [orderDetailBusy,setOrderDetailBusy]=useState(false);
 const [orders,setOrders]=useState<CustomerOrderSummary[]>([]); const [selectedProduct,setSelectedProduct]=useState<Product|null>(null); const [finance,setFinance]=useState<Finance|null>(null); const [financePage,setFinancePage]=useState(1); const FINANCE_PAGE_SIZE=10; const financePages=Math.max(1,Math.ceil((finance?.entries.length??0)/FINANCE_PAGE_SIZE)); const activeFinancePage=Math.min(financePage,financePages); const visibleFinanceEntries=finance?.entries.slice((activeFinancePage-1)*FINANCE_PAGE_SIZE,activeFinancePage*FINANCE_PAGE_SIZE)??[]; const [templates,setTemplates]=useState<OrderTemplate[]>([]); const [templateName,setTemplateName]=useState(''); const [confirmed,setConfirmed]=useState<Record<string,boolean>>({}); const [payment,setPayment]=useState<'credit'|'cash'|'transfer'>('credit'); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine); const [offlineSyncing,setOfflineSyncing]=useState(false); const [voiceListening,setVoiceListening]=useState(false); const [checkoutIdempotencyKey,setCheckoutIdempotencyKey]=useState(()=>crypto.randomUUID());
  function startVoiceSearch(){
    const browserWindow=window as typeof window & { SpeechRecognition?: VoiceRecognitionConstructor; webkitSpeechRecognition?: VoiceRecognitionConstructor };
    const Recognition=browserWindow.SpeechRecognition??browserWindow.webkitSpeechRecognition;
    if(!Recognition){setError('البحث الصوتي غير مدعوم في هذا المتصفح. استخدم البحث النصي بدلًا منه.');return;}
    if(voiceListening)return;
    setError('');setMessage('');
    const recognition=new Recognition();
    recognition.lang='ar-YE';recognition.interimResults=false;recognition.maxAlternatives=1;
    recognition.onresult=(event)=>{const transcript=String(event.results?.[0]?.[0]?.transcript??'').trim();if(transcript){setQuery(transcript);setMessage('تم تحويل الصوت إلى نص والبحث في الكتالوج.');}else setError('لم ألتقط عبارة واضحة. حاول مرة أخرى.');};
    recognition.onerror=(event)=>setError(event.error==='not-allowed'?'تم رفض صلاحية الميكروفون. يمكنك استخدام البحث النصي.':'تعذر تنفيذ البحث الصوتي.');
    recognition.onend=()=>setVoiceListening(false);
    setVoiceListening(true);
    try{recognition.start();}catch{setVoiceListening(false);setError('تعذر بدء البحث الصوتي. استخدم البحث النصي.');}
  }
  const loadConfig=useCallback(async(orgId:string)=>{ if(!supabase)return; const {data,error:configError}=await supabase.from('client_ui_settings').select('config').eq('organization_id',orgId).maybeSingle(); if(configError)throw configError; setConfig(data?.config?{...DEFAULT_UI_CONFIG,...(data.config as Partial<ClientUiConfig>)}:DEFAULT_UI_CONFIG); },[]);
  const loadIdentity=useCallback(async(userId:string)=>{if(!supabase)return;const {data,error:profileError}=await supabase.from('profiles').select('customer_id,role,organization_id').eq('id',userId).single();if(profileError)throw profileError;setRole((data?.role as UserRole)??'viewer');setCustomerId(data?.customer_id??null);setOrganizationId(data?.organization_id??null);if(data?.organization_id){await loadConfig(data.organization_id);const {data:warehouse,error:warehouseError}=await supabase.from('warehouses').select('id').eq('organization_id',data.organization_id).eq('is_active',true).order('created_at').limit(1).maybeSingle();if(warehouseError)throw warehouseError;setWarehouseId(warehouse?.id??null);}if(data?.customer_id){const {data:customer,error:customerError}=await supabase.from('customers').select('name').eq('id',data.customer_id).maybeSingle();if(customerError)throw customerError;if(customer?.name)setCustomerName(customer.name);setTemplates(await getOrderTemplates());}},[loadConfig]);
  useEffect(()=>{setFinancePage(1);},[customerId]);
 useEffect(()=>{
   const syncSectionFromUrl=()=>setSection(sectionFromHash());
   window.addEventListener('hashchange',syncSectionFromUrl);
   window.addEventListener('popstate',syncSectionFromUrl);
   syncSectionFromUrl();
   return()=>{window.removeEventListener('hashchange',syncSectionFromUrl);window.removeEventListener('popstate',syncSectionFromUrl);};
 },[]);
 useEffect(()=>{
   const onKeyDown=(event:KeyboardEvent)=>{
     if(event.key!=='Escape')return;
     if(excelOpen&&!excelBusy){setExcelOpen(false);return;}
     if(quickOpen){setQuickOpen(false);return;}
     if(selectedOrder){setSelectedOrder(null);return;}
     if(selectedProduct){setSelectedProduct(null);return;}
     if(cartOpen)setCartOpen(false);
   };
   window.addEventListener('keydown',onKeyDown);
   return()=>window.removeEventListener('keydown',onKeyDown);
 },[cartOpen,excelBusy,excelOpen,quickOpen,selectedOrder,selectedProduct]);
 useEffect(()=>{let dead=false;void getSession().then(async s=>{if(dead)return;setSignedIn(Boolean(s));setReady(true);if(s){setEmail(s.user.email??'');setSessionUserId(s.user.id);await loadIdentity(s.user.id);}}).catch(e=>{if(!dead){setReady(true);setError(e instanceof Error?e.message:'تعذر قراءة الجلسة.');}});const sub=supabase?.auth.onAuthStateChange((event,s)=>{if(dead)return;setSignedIn(Boolean(s));if(s&&(event==='SIGNED_IN'||event==='TOKEN_REFRESHED')){setSessionUserId(s.user.id);void loadIdentity(s.user.id);}if(!s){setSessionUserId(null);setCustomerId(null);setOrganizationId(null);setWarehouseId(null);setRole('viewer');setProducts([]);setCart([]);setFinance(null);setOrders([]);setTemplates([]);setConfig(DEFAULT_UI_CONFIG);}});return()=>{dead=true;sub?.data.subscription.unsubscribe();};},[loadIdentity]);
  useEffect(()=>{if(!signedIn||!organizationId||!supabase)return;const channel=supabase.channel(`b2b-ui-${organizationId}`).on('postgres_changes',{event:'*',schema:'public',table:'client_ui_settings',filter:`organization_id=eq.${organizationId}`},()=>void loadConfig(organizationId));channel.subscribe();const timer=window.setInterval(()=>void loadConfig(organizationId),15000);return()=>{supabase.removeChannel(channel);window.clearInterval(timer);};},[signedIn,organizationId,loadConfig]);
  const loadData=useCallback(async()=>{if(!signedIn||!customerId||!supabase)return;setLoading(true);setError('');try{const [items,saved,cats]=await Promise.all([getCatalog(query,categoryId,CATALOG_PAGE_SIZE,catalogPage*CATALOG_PAGE_SIZE,warehouseId??undefined),getCart(),getCategories()]);const cmap=new Map(cats.map(c=>[c.id,c.name]));const urls=await getProductImageUrls(items.map(i=>i.image_path));const mapped=items.map(i=>mapProduct(i,cmap.get(i.category_id??'')??'أصناف',i.image_path?urls.get(i.image_path):undefined));setProducts(mapped);setCatalogHasMore(items.length===CATALOG_PAGE_SIZE);setCategories(cats);setCart(saved.map(i=>{const p=mapped.find(x=>x.id===i.product_id)??({id:i.product_id,sku:i.sku,name:i.name,unit:i.unit,category:'أصناف',availableQuantity:0,status:'active'} as Product);return{product:p,quantity:i.quantity,unitPrice:i.authorized_price??0};}));if(items.length){const {data:rows,error:tiersError}=await supabase.from('customer_price_tiers').select('product_id,min_quantity,unit_price,currency').eq('customer_id',customerId).in('product_id',items.map(i=>i.id)).order('min_quantity');if(tiersError)throw tiersError;const grouped:Record<string,PriceTier[]>={};for(const row of rows??[])(grouped[row.product_id]??=[]).push({min_quantity:Number(row.min_quantity),unit_price:Number(row.unit_price),currency:row.currency});setTiers(grouped);}const [{data:orderRows,error:ordersError},{data:account,error:accountError},{data:ledger,error:ledgerError}]=await Promise.all([supabase.from('orders').select('id,order_number,total,currency,status,created_at').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(30),supabase.from('customer_credit_accounts').select('currency,credit_limit,outstanding_balance,available_credit').eq('customer_id',customerId).maybeSingle(),supabase.from('customer_ledger_entries').select('id,reference,description,debit,credit,due_date,status,created_at').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(50)]);if(ordersError||accountError||ledgerError)throw ordersError??accountError??ledgerError;setOrders((orderRows??[]) as CustomerOrderSummary[]);setFinance(account?{currency:account.currency,creditLimit:Number(account.credit_limit),outstanding:Number(account.outstanding_balance),available:Number(account.available_credit),entries:(ledger??[]).map(e=>({...e,debit:Number(e.debit),credit:Number(e.credit)}))}:null);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المتجر.');}finally{setLoading(false);}},[signedIn,customerId,warehouseId,query,categoryId,catalogPage]);
  useEffect(()=>{setCatalogPage(0);},[query,categoryId]);
  useEffect(()=>{void loadData();},[loadData]);
  useEffect(()=>{const enabled=PAYMENT_OPTIONS.find(option=>config[option.field]);if(enabled&&!PAYMENT_OPTIONS.some(option=>option.key===payment&&config[option.field]))setPayment(enabled.key);},[config,payment]);
  useEffect(()=>{const handleOffline=()=>setOnline(false);const handleOnline=()=>{setOnline(true);if(!signedIn)return;setOfflineSyncing(true);setError('');void syncOfflineCart().then((result)=>{if(result.processed>0)setMessage(`تمت مزامنة ${result.processed} عملية سلة بعد عودة الاتصال.`);if(result.failed>0)setError(`تعذر مزامنة ${result.failed} عملية سلة مؤقتًا؛ ستبقى في الطابور لإعادة المحاولة الآمنة.`);return loadData();}).catch(e=>setError(e instanceof Error?e.message:'تعذر مزامنة السلة بعد عودة الاتصال.')).finally(()=>setOfflineSyncing(false));};window.addEventListener('online',handleOnline);window.addEventListener('offline',handleOffline);return()=>{window.removeEventListener('online',handleOnline);window.removeEventListener('offline',handleOffline);};},[signedIn,loadData]);

  const total=calculateClientPreviewTotal(cart);const cartCount=cart.reduce((s,l)=>s+l.quantity,0);const categoriesView=useMemo(()=>[{id:null,name:'الكل'},...categories],[categories]);const visibleProducts=useMemo(()=>{const next=[...products];if(catalogSort==='name')next.sort((x,y)=>x.name.localeCompare(y.name,'ar'));if(catalogSort==='stock')next.sort((x,y)=>y.availableQuantity-x.availableQuantity||x.name.localeCompare(y.name,'ar'));return next;},[catalogSort,products]);
  function effectivePrice(p:Product,q:number){const list=tiers[p.id]??[];return [...list].sort((a,b)=>b.min_quantity-a.min_quantity).find(x=>q>=x.min_quantity)?.unit_price??0;}
  function nextTier(p:Product,q:number){return (tiers[p.id]??[]).filter(x=>x.min_quantity>q).sort((a,b)=>a.min_quantity-b.min_quantity)[0];}
  function setQtyConfirmed(id:string,value:boolean){setConfirmed(c=>({...c,[id]:value}));}
  async function openOrderDetail(order:CustomerOrderSummary){setOrderDetailBusy(true);setError('');try{setSelectedOrder(await getCustomerOrderDetail(order.id));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل تفاصيل الطلب.');}finally{setOrderDetailBusy(false);}}
  async function refreshAccount(){if(!supabase)return;setBusy(true);setError('');try{const session=await getSession();if(!session)throw new Error('انتهت جلسة الحساب. سجّل الدخول مجددًا.');await loadIdentity(session.user.id);await loadData();setMessage('تم تحديث سياق الحساب والبيانات.');}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث سياق الحساب.');}finally{setBusy(false);}}
  function navigate(next:PortalSection){if(next!==section&&config.requireQuantityConfirmation&&cart.some(l=>!confirmed[l.product.id])){setError('اعتمد كميات السلة أولاً قبل الانتقال إلى قسم آخر.');setCartOpen(true);return;}setError('');setSection(next);if(typeof window!=='undefined'&&window.location.hash!==('#'+next))window.history.pushState(null,'','#'+next);}
  async function add(p:Product,q=1):Promise<boolean>{const price=effectivePrice(p,q);if(price<=0){setError('لا يوجد سعر مصرح به لهذا الصنف.');return false;}if(q<1||q>p.availableQuantity){setError('الكمية المطلوبة غير متاحة.');return false;}const existing=cart.find(l=>l.product.id===p.id);const next=Math.min((existing?.quantity??0)+q,p.availableQuantity);try{await setCartItem(p.id,next);setCart(c=>existing?c.map(l=>l.product.id===p.id?{...l,quantity:next,unitPrice:effectivePrice(p,next)}:l):[...c,{product:p,quantity:next,unitPrice:price}]);setQtyConfirmed(p.id,!config.requireQuantityConfirmation);setCartOpen(true);setError('');return true;}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث السلة.');return false;}}
  async function update(id:string,q:number){const line=cart.find(l=>l.product.id===id);if(!line)return;const next=Math.max(0,Math.min(q,line.product.availableQuantity));try{if(!next){await removeCartItem(id);setCart(c=>c.filter(l=>l.product.id!==id));setConfirmed(c=>{const n={...c};delete n[id];return n;});}else{await setCartItem(id,next);setCart(c=>c.map(l=>l.product.id===id?{...l,quantity:next,unitPrice:effectivePrice(l.product,next)}:l));setQtyConfirmed(id,!config.requireQuantityConfirmation);}}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث الكمية.');}}
  async function submit(){if(!customerId||!cart.length||busy)return;if(!online)return setError('الاتصال بالخادم مطلوب لإرسال الطلب. يمكن مواصلة تعديل السلة دون اتصال، لكن اعتماد وإرسال الطلب مؤجل حتى عودة الاتصال.');if(config.requireQuantityConfirmation&&cart.some(l=>!confirmed[l.product.id]))return setError('يجب اعتماد جميع الكميات قبل إرسال الطلب.');if(config.minOrderValue>0&&total<config.minOrderValue)return setError(`الحد الأدنى للطلب ${money(config.minOrderValue)}.`);if(config.maxOrderValue>0&&total>config.maxOrderValue)return setError(`الحد الأعلى للطلب ${money(config.maxOrderValue)}.`);if(config.showPaymentMethods&&!PAYMENT_OPTIONS.some(x=>x.key===payment&&config[x.field]))return setError('وسيلة الدفع المختارة غير متاحة حاليًا.');setBusy(true);setError('');try{const result=await createOrder({customerId,idempotencyKey:checkoutIdempotencyKey,lines:cart.map(l=>({productId:l.product.id,quantity:l.quantity}))},warehouseId??undefined,{paymentMethod:payment});setCheckoutIdempotencyKey(crypto.randomUUID());setCart([]);setConfirmed({});setCartOpen(false);setMessage(`تم إرسال الطلب #${result.order_number} بنجاح.`);navigate('orders');void loadData();}catch(e){setError(e instanceof Error?e.message:'تعذر إرسال الطلب.');}finally{setBusy(false);}}
  async function saveTemplate(){if(!cart.length||!templateName.trim()||busy)return;setBusy(true);setError('');setMessage('');try{const item=await createOrderTemplate({name:templateName,branchLabel:'الفرع الرئيسي',lines:cart.map(l=>({productId:l.product.id,sku:l.product.sku,name:l.product.name,unit:l.product.unit,quantity:l.quantity}))});setTemplates(current=>[item,...current].slice(0,config.maxTemplates));setTemplateName('');setMessage('تم حفظ المسحة في قاعدة البيانات.');}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ المسحة.');}finally{setBusy(false);}}
  async function removeTemplate(id:string){if(busy)return;setBusy(true);setError('');setMessage('');try{await deleteOrderTemplate(id);setTemplates(current=>current.filter(item=>item.id!==id));setMessage('تم حذف المسحة.');}catch(e){setError(e instanceof Error?e.message:'تعذر حذف المسحة.');}finally{setBusy(false);}}
  async function applyTemplate(t:OrderTemplate){if(busy)return;setBusy(true);setError('');setMessage('');try{await applyOrderTemplate(t.id,warehouseId??undefined);const saved=await getCart();setCart(saved.map(i=>{const p=products.find(x=>x.id===i.product_id)??({id:i.product_id,sku:i.sku,name:i.name,unit:i.unit,category:'أصناف',availableQuantity:0,status:'active'} as Product);return{product:p,quantity:i.quantity,unitPrice:i.authorized_price??0};}));setConfirmed({});setCartOpen(true);setMessage('تم تطبيق المسحة على السلة عبر العملية الذرية.');navigate('catalog');}catch(e){setError(e instanceof Error?e.message:'تعذر تطبيق المسحة.');}finally{setBusy(false);}}
  async function stageQuickExcel(file:File){setExcelBusy(true);setError('');setMessage('');try{const raw=await readXlsxFile(file) as unknown;const rows=Array.isArray(raw)?raw.filter(Array.isArray) as unknown[][]:[];if(!rows.length)throw new Error('ملف Excel فارغ.');if(rows.length>101)throw new Error('ملف الطلب السريع يتجاوز 100 صف.');const first=rows[0]?.map(cell=>String(cell??'').trim().toLowerCase())??[];const hasHeader=first.some(v=>['sku','identifier','product code','الرمز','الصنف','sku/الباركود'].includes(v));const dataRows=rows.slice(hasHeader?1:0);const seen=new Set<string>();const nextRows:QuickExcelLine[]=[];for(const row of dataRows){const identifier=String(row?.[0]??'').trim();const quantity=Number(row?.[1]);if(!identifier&&!row?.[1])continue;let rowError:string|null=null;if(!identifier)rowError='المعرف مطلوب.';else if(seen.has(identifier.toLowerCase()))rowError='العنصر مكرر في الملف.';else if(!Number.isSafeInteger(quantity)||quantity<1)rowError='الكمية يجب أن تكون عددًا صحيحًا موجبًا.';let product:Product|null=null;if(!rowError){seen.add(identifier.toLowerCase());const normalizedIdentifier=identifier.toLowerCase();product=products.find(p=>p.sku.toLowerCase()===normalizedIdentifier)??null;if(!product){const found=await getCatalog(identifier,null,5,0,warehouseId??undefined);const exact=found.find(item=>item.sku.toLowerCase()===normalizedIdentifier||(item.barcode??'').toLowerCase()===normalizedIdentifier);if(exact)product=mapProduct(exact,'أصناف');}if(!product)rowError='المعرف غير موجود أو غير مصرح به لهذا العميل.';else if(product.status!=='active')rowError='الصنف غير نشط.';else if(quantity>product.availableQuantity)rowError=`المخزون المتاح ${product.availableQuantity} فقط.`;else if(quantity>100000)rowError='الكمية تتجاوز الحد التشغيلي.';}nextRows.push({identifier,quantity,product,error:rowError});}if(!nextRows.length)throw new Error('لم توجد صفوف صالحة للمعالجة.');setExcelRows(nextRows);setExcelOpen(true);}catch(e){setExcelRows([]);setError(e instanceof Error?e.message:'تعذر تحليل ملف الطلب السريع.');}finally{setExcelBusy(false);}}
  async function confirmQuickExcel(){const invalid=excelRows.filter(row=>row.error||!row.product);if(invalid.length)return setError('يجب إصلاح جميع أخطاء ملف الطلب قبل الاعتماد.');if(!warehouseId)return setError('لا يوجد مستودع نشط متاح للحساب الحالي.');setExcelBusy(true);setError('');setMessage('');try{await applyQuickOrder({idempotencyKey:crypto.randomUUID(),warehouseId,lines:excelRows.map(row=>({productId:row.product!.id,quantity:row.quantity}))});await loadData();setExcelRows([]);setExcelOpen(false);setCartOpen(true);setMessage('تم اعتماد الطلب السريع وإضافة الأصناف إلى السلة وتسجيل العملية.');}catch(e){setError(e instanceof Error?e.message:'تعذر اعتماد الطلب السريع.');}finally{setExcelBusy(false);}}
  function downloadStatement(){if(!finance)return;const rows=[['المرجع','البيان','مدين','دائن','الاستحقاق','الحالة'],...finance.entries.map(e=>[e.reference??'-',e.description,String(e.debit),String(e.credit),e.due_date??'-',e.status])];const csv='\ufeff'+rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aghbari-statement-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await signIn(email,password);if(!s)throw new Error('تعذر إنشاء جلسة دخول صالحة.');await loadIdentity(s.user.id);setSignedIn(true);setReady(true);}catch(e){setSignedIn(false);setReady(true);setError(e instanceof Error?e.message:'تعذر تسجيل الدخول.');}finally{setBusy(false);}}
  async function logout(){await signOut();}
  if(!ready)return <div className="customer-shell"><div className="portal-loading">جارٍ تجهيز بوابة الأغبري…</div></div>;
  if(!signedIn)return <div className="customer-shell auth-shell"><div className="auth-card"><span className="eyebrow">AGHBARI B2B</span><h1>بوابة الأغبري التجارية</h1><p>شراء جملة سريع، أسعار مصرح بها، ومتابعة مالية وتشغيلية في مكان واحد.</p><form onSubmit={login}><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="البريد الإلكتروني" required/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="كلمة المرور" required/><button disabled={busy}>{busy?'جارٍ الدخول…':'دخول آمن'}</button></form>{error&&<div className="error-banner">{error}</div>}</div></div>;
  if([...STAFF_ROLES, 'viewer'].includes(role))return <><header className="staff-topbar"><strong>الأغبري · مركز التحكم التشغيلي</strong><div><span>الدور: {role==='viewer'?'مشاهد':role}</span><button onClick={()=>void logout()}>خروج</button></div></header><Suspense fallback={<div className="admin-loading-shell" role="status">جارٍ تحميل مركز الإدارة…</div>}><AdminPanel role={role as 'owner'|'admin'|'sales'|'warehouse'|'viewer'}/></Suspense></>;
  return <div className="customer-shell"><header className="portal-header"><div><span className="eyebrow">B2B ENTERPRISE</span><h1>بوابة الأغبري</h1><small>مرحبًا، {customerName}</small></div><div className="header-actions"><span className={`connection ${online?'':'connection-offline'}`} role="status">{online?(offlineSyncing?'↻ مزامنة…':'● متصل'):'○ غير متصل'}</span><button onClick={()=>setCartOpen(true)}>السلة <b>{cartCount}</b></button><button className="ghost" onClick={()=>void logout()}>خروج</button></div></header>
    <div className="portal-body"><aside className="portal-nav"><button aria-current={section==='catalog'?'page':undefined} className={section==='catalog'?'active':''} onClick={()=>navigate('catalog')}>الكتالوج</button><button aria-current={section==='orders'?'page':undefined} className={section==='orders'?'active':''} onClick={()=>navigate('orders')}>طلباتي</button><button aria-current={section==='account'?'page':undefined} className={section==='account'?'active':''} onClick={()=>navigate('account')}>حسابي</button><button aria-current={section==='notifications'?'page':undefined} className={section==='notifications'?'active':''} onClick={()=>navigate('notifications')}>الإشعارات</button>{config.showTemplates&&<button aria-current={section==='templates'?'page':undefined} className={section==='templates'?'active':''} onClick={()=>navigate('templates')}>المسحات</button>}{config.showCredit&&<button aria-current={section==='finance'?'page':undefined} className={section==='finance'?'active':''} onClick={()=>navigate('finance')}>المركز المالي</button>}</aside><main className="portal-main">
      <section className="customer-section-context" aria-label="سياق القسم الحالي"><div><span className="eyebrow">{PORTAL_SECTION_META[section].eyebrow}</span><strong>{PORTAL_SECTION_META[section].label}</strong><small>{PORTAL_SECTION_META[section].hint}</small></div><div className="customer-context-actions"><button type="button" className="ghost" onClick={()=>setCartOpen(true)}>السلة <b>{cartCount}</b></button>{section!=='catalog'&&<button type="button" className="ghost" onClick={()=>setSection('catalog')}>الكتالوج</button>}</div></section>
      {section==='catalog'&&<><section className="hero-card"><div><span className="eyebrow">تجارة جملة أسرع</span><h2>احتياج متجرك، في طلب واحد.</h2><p>ابحث بالاسم أو SKU أو الباركود، راجع شرائح السعر، ثم اعتمد الكميات وأرسل الطلب.</p></div><div className="hero-stat"><strong>{products.length}</strong><span>صنف في الصفحة</span></div></section>
      <section className="customer-overview-strip" aria-label="ملخص حساب التاجر">
        <article className="customer-overview-card customer-overview-primary">
          <span className="overview-icon" aria-hidden="true">◫</span>
          <div><small>المتاح للشراء</small><strong>{finance?money(finance.available,finance.currency):'—'}</strong><em>{finance?'من الحد الائتماني':'بانتظار بيانات الحساب'}</em></div>
        </article>
        <article className="customer-overview-card">
          <span className="overview-icon" aria-hidden="true">🧾</span>
          <div><small>الطلبات</small><strong>{orders.length.toLocaleString('ar')}</strong><em>{orders[0]?`آخر طلب #${orders[0].order_number}`:'لا توجد طلبات بعد'}</em></div>
        </article>
        <article className="customer-overview-card">
          <span className="overview-icon" aria-hidden="true">▣</span>
          <div><small>السلة الحالية</small><strong>{cartCount.toLocaleString('ar')}</strong><em>{cart.length?`${cart.length} أصناف جاهزة للمراجعة`:'السلة فارغة'}</em></div>
        </article>
        <article className="customer-overview-card">
          <span className="overview-icon" aria-hidden="true">{online?'●':'○'}</span>
          <div><small>حالة الاتصال</small><strong>{online?'متصل':'غير متصل'}</strong><em>{offlineSyncing?'تتم المزامنة الآمنة الآن':'الخدمة الأساسية'}</em></div>
        </article>
      </section>
      <section className="portal-quick-actions" aria-label="اختصارات بوابة الأغبري">
        <div className="portal-quick-lead"><span className="eyebrow">تشغيل سريع</span><strong>من نفس الشاشة إلى الإجراء التالي</strong><small>ابدأ الطلب، راجع طلباتك، أو افتح حسابك دون فقدان سياق المتجر.</small></div>
        <div className="portal-quick-grid">
          <button type="button" className="portal-quick-item primary" onClick={()=>setCartOpen(true)}><span aria-hidden="true">🛒</span><div><strong>مراجعة السلة</strong><small>{cartCount?cartCount.toLocaleString('ar')+' وحدة في السلة':'السلة فارغة'}</small></div><b>↗</b></button>
          <button type="button" className="portal-quick-item" onClick={()=>navigate('orders')}><span aria-hidden="true">🧾</span><div><strong>آخر الطلبات</strong><small>{orders.length?orders.length.toLocaleString('ar')+' طلب في السجل':'لم تُرسل طلبات بعد'}</small></div><b>↗</b></button>
          {config.showTemplates&&<button type="button" className="portal-quick-item" onClick={()=>navigate('templates')}><span aria-hidden="true">▤</span><div><strong>المسحات الجاهزة</strong><small>{templates.length} مسحة محفوظة</small></div><b>↗</b></button>}
          {config.showCredit&&<button type="button" className="portal-quick-item" onClick={()=>navigate('finance')}><span aria-hidden="true">◫</span><div><strong>المركز المالي</strong><small>{finance?money(finance.available,finance.currency):'بيانات الحساب'}</small></div><b>↗</b></button>}
        </div>
      </section>
      {config.showSearch&&<section className="search-panel"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الصنف، SKU أو الباركود…" aria-label="البحث في الكتالوج"/><div>{config.showVoiceSearch&&<button type="button" title="البحث الصوتي" aria-pressed={voiceListening} disabled={voiceListening} onClick={startVoiceSearch}>{voiceListening?'● جارٍ الاستماع':'🎙 البحث الصوتي'}</button>}{config.showImageSearch&&<span className="search-capability-disabled" role="note" title="البحث بالصور يحتاج عقد بحث مرئي حقيقي غير موجود في Commerce الحالي.">⌕ البحث بالصور غير متاح حاليًا</span>}{config.showExcel&&<label className="file-button">رفع Excel<input type="file" accept=".xlsx" disabled={excelBusy} onChange={async e=>{const f=e.target.files?.[0];if(f)await stageQuickExcel(f);e.currentTarget.value='';}}/></label>}{config.showQuickOrder&&<button onClick={()=>setQuickOpen(true)}>طلب سريع</button>}</div></section>}
      {config.showCategories&&<div className="category-row">{categoriesView.map(c=><button key={c.id??"all"} className={categoryId===c.id?"active":""} onClick={()=>setCategoryId(c.id)}>{c.name}</button>)}</div>}
      <div className="catalog-display-toolbar" aria-label="خيارات عرض الكتالوج"><div><span className="eyebrow">طريقة العرض</span><strong>{visibleProducts.length} صنف</strong></div><div className="catalog-display-controls"><label>الترتيب<select value={catalogSort} onChange={e=>setCatalogSort(e.target.value as typeof catalogSort)}><option value="relevance">الأولوية الحالية</option><option value="name">الاسم</option><option value="stock">الأكثر توفرًا</option></select></label><div className="catalog-view-switch" role="group" aria-label="طريقة عرض المنتجات"><button type="button" className={catalogView==='grid'?'active':''} aria-pressed={catalogView==='grid'} onClick={()=>setCatalogView('grid')}>▦ شبكة</button><button type="button" className={catalogView==='compact'?'active':''} aria-pressed={catalogView==='compact'} onClick={()=>setCatalogView('compact')}>☷ مضغوط</button></div></div></div>
      <div className="catalog-context-bar" aria-live="polite">
        <span>{loading?"جارٍ تحميل الكتالوج…":products.length+" صنف معروض"}</span>
        <span>{categoryId?(categories.find(item=>item.id===categoryId)?.name??"تصنيف محدد"):"كل التصنيفات"}</span>
        {query&&<span>بحث: <b>{query}</b></span>}
        {(query||categoryId)&&<button type="button" className="ghost" onClick={()=>{setQuery("");setCategoryId(null);setCatalogPage(0);}}>مسح الفلاتر</button>}
      </div>
      {loading?<div className="portal-loading">جارٍ تحميل الكتالوج…</div>:products.length?<> <div className={`product-grid ${catalogView==='compact'?'product-grid-compact':''}`}>{visibleProducts.map(p=>{const q=cart.find(l=>l.product.id===p.id)?.quantity??0;const baseQty=Math.max(1,q);const price=effectivePrice(p,baseQty);const next=nextTier(p,baseQty);return <article className="product-card" key={p.id}>{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>:<div className="product-placeholder">{p.name.slice(0,1)}</div>}<div className="product-body"><span className="sku">{p.sku}</span><h3>{p.name}</h3><small>{p.category} · {p.unit}</small>{config.showInventory&&<span className="stock">{p.availableQuantity>0?`متاح ${p.availableQuantity} ${p.unit}`:'غير متوفر'}</span>}{price>0?<div className="price-row"><strong>{money(price)}</strong>{config.showRetailPrice&&<small>سعر التجزئة متاح حسب الصلاحية</small>}</div>:<div className="price-hidden">السعر حسب حسابك</div>}{config.showTieredPricing&&(tiers[p.id]??[]).length>1&&<div className="tiers">{(tiers[p.id]??[]).map(t=><span key={t.min_quantity}>من {t.min_quantity}: {money(t.unit_price,t.currency)}</span>)}</div>}{config.showSavingsCalculator&&next&&<div className="saving">أضف {next.min_quantity-baseQty} {p.unit} للوصول إلى {money(next.unit_price,next.currency)}</div>}<div className="product-card-actions" aria-label={"إجراءات "+p.name}><div className="product-qty" aria-label={"كمية "+p.name+" في السلة"}><button type="button" aria-label={"تقليل "+p.name} onClick={()=>void update(p.id,q-1)} disabled={q<=0}>−</button><span aria-live="polite">{q}</span><button type="button" aria-label={"زيادة "+p.name} onClick={()=>{if(q===0){void add(p)}else{void update(p.id,q+1)}}} disabled={p.availableQuantity<1||price<=0||q>=p.availableQuantity}>+</button></div>{q>0&&<span className="in-cart-label">في السلة</span>}</div><button className="ghost" onClick={()=>setSelectedProduct(p)}>التفاصيل</button><button className="add-button" disabled={p.availableQuantity<1||price<=0} onClick={()=>void add(p)}>{q>0?"إضافة أخرى":"إضافة للسلة"}</button></div></article>})}</div><div className="catalog-pagination" aria-label="تصفح الكتالوج"><span>صفحة {catalogPage+1}</span><div><button type="button" className="ghost" onClick={()=>setCatalogPage(p=>Math.max(0,p-1))} disabled={catalogPage===0||loading}>السابق</button><button type="button" className="ghost" onClick={()=>setCatalogPage(p=>p+1)} disabled={!catalogHasMore||loading}>التالي</button></div></div></>:<div className="empty-state catalog-empty"><strong>{query||categoryId?'لم نجد أصنافًا مطابقة':'لا توجد أصناف متاحة حاليًا.'}</strong><span>{query||categoryId?'جرّب تغيير البحث أو التصنيف.':'تحقق من اتصال الحساب أو أعد المحاولة.'}</span><button onClick={()=>void loadData()}>إعادة المحاولة</button></div>}
      </>}
      {section==='orders'&&<CustomerOrdersPanel orders={orders} loading={loading} detailBusy={orderDetailBusy} productsCount={products.length} onOpenDetail={openOrderDetail} onReload={()=>void loadData()} onReorder={async(order)=>{try{const {data,error:itemsError}=await supabase.from('order_items').select('product_id,quantity').eq('order_id',order.id);if(itemsError)throw itemsError;for(const item of data??[]){const product=products.find(p=>p.id===item.product_id);if(product)await add(product,Math.min(Number(item.quantity),product.availableQuantity));}navigate('catalog');}catch(e){setError(e instanceof Error?e.message:'تعذر إعادة الطلب.');}}}/>}
      {section==='templates'&&config.showTemplates&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">طلبات دورية</span><h2>المسحات الجاهزة</h2></div><span>{templates.length}/{config.maxTemplates}</span></div>{loading?<div className="portal-loading">جارٍ تحميل المسحات…</div>:<><div className="template-save"><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="اسم المسحة"/><button disabled={busy||!templateName.trim()||!cart.length} onClick={()=>void saveTemplate()}>حفظ السلة كمسحة</button></div><div className="template-grid">{templates.map(t=><article className="template-card" key={t.id}><strong>{t.name}</strong><small>{t.lines.length} أصناف · {t.branchLabel}</small><div><button onClick={()=>void applyTemplate(t)}>إعادة الطلب</button><button className="ghost" disabled={busy} onClick={()=>void removeTemplate(t.id)}>حذف</button></div></article>)}</div>{templates.length===0&&<div className="empty-state"><strong>لا توجد مسحات محفوظة بعد.</strong><span>احفظ السلة الحالية كطلب دوري لإعادة استخدامها.</span></div>}</>}</section>}
      {section==='account'&&<section className="content-card account-card"><div className="section-title"><div><span className="eyebrow">الحساب</span><h2>حساب التاجر</h2><p>لوحة سياق سريعة للهوية، الرصيد، الطلبات والاتصال.</p></div><div className="order-detail-actions"><button className="ghost" onClick={()=>void refreshAccount()} disabled={busy}>{busy?'جارٍ التحديث…':'تحديث السياق'}</button><button onClick={()=>void logout()}>تسجيل الخروج</button></div></div><div className="account-summary-grid"><article><small>الحالة</small><strong>{online?'متصل':'غير متصل'}</strong><span>{offlineSyncing?'مزامنة السلة…':'الخدمة الأساسية متاحة'}</span></article><article><small>الرصيد المستحق</small><strong>{finance?money(finance.outstanding,finance.currency):'—'}</strong><span>{finance?'المتاح '+money(finance.available,finance.currency):'لا توجد بيانات مالية'}</span></article><article><small>الطلبات</small><strong>{orders.length}</strong><span>{orders[0]?'آخر طلب #'+orders[0].order_number:'لم تُرسل طلبات بعد'}</span></article><article><small>المسحات</small><strong>{templates.length}/{config.maxTemplates}</strong><span>قوائم الطلبات المتكررة</span></article></div><div className="account-grid"><div><small>اسم العميل</small><strong>{customerName}</strong></div><div><small>البريد المستخدم للجلسة</small><strong dir="ltr">{email||'—'}</strong></div><div><small>معرّف العميل</small><code>{customerId??'—'}</code></div><div><small>المنظمة</small><code>{organizationId??'—'}</code></div><div><small>المستودع التشغيلي</small><code>{warehouseId??'—'}</code></div><div><small>الصلاحية</small><strong>عميل B2B</strong></div></div><OfflineRecoveryPanel userId={sessionUserId} /><div className="account-shortcuts"><button onClick={()=>navigate('catalog')}>العودة للكتالوج</button><button className="ghost" onClick={()=>navigate('orders')}>فتح طلباتي</button>{config.showCredit&&<button className="ghost" onClick={()=>navigate('finance')}>فتح المركز المالي</button>} {config.showTemplates&&<button className="ghost" onClick={()=>navigate('templates')}>فتح المسحات</button>}</div></section>}      {section==='notifications'&&<NotificationPanel audience="customer"/>}
      {section==='finance' && config.showCredit && (
        <section className="content-card">
          <div className="section-title">
            <div><span className="eyebrow">الثقة المالية</span><h2>المركز المالي</h2></div>
            <button onClick={downloadStatement} disabled={!finance}>تنزيل الكشف</button>
          </div>
          {loading ? (
            <div className="portal-loading">جارٍ تحميل المركز المالي…</div>
          ) : finance ? (
            <>
              <div className="finance-grid">
                <div><small>الحد الائتماني</small><strong>{money(finance.creditLimit, finance.currency)}</strong></div>
                <div><small>الرصيد المستحق</small><strong>{money(finance.outstanding, finance.currency)}</strong></div>
                <div><small>المتاح للشراء</small><strong>{money(finance.available, finance.currency)}</strong></div>
              </div>
              <div className="ledger-table">
                {visibleFinanceEntries.map((entry) => (
                  <div className="ledger-row" key={entry.id}>
                    <span>{entry.reference ?? '—'}</span>
                    <strong>{entry.description}</strong>
                    <span>{entry.debit ? `مدين ${money(entry.debit, finance.currency)}` : `دائن ${money(entry.credit, finance.currency)}`}</span>
                    <span>{entry.due_date ?? '—'}</span>
                  </div>
                ))}
                <div className="directory-pagination" aria-label="صفحات الكشف المالي">
                  <span>صفحة {activeFinancePage} / {financePages} · {finance.entries.length} حركة</span>
                  <div>
                    <button type="button" className="ghost" onClick={() => setFinancePage((page) => Math.max(1, page - 1))} disabled={activeFinancePage === 1}>السابق</button>
                    <button type="button" className="ghost" onClick={() => setFinancePage((page) => Math.min(financePages, page + 1))} disabled={activeFinancePage === financePages}>التالي</button>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <div className="empty-state">لا توجد بيانات مركز مالي متاحة.</div>
          )}
        </section>
      )}
      {error&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
    </main></div>
    <nav className="customer-mobile-dock" aria-label="تنقل سريع للمشتري">
      <button type="button" className={section==="catalog"?"active":""} onClick={()=>navigate("catalog")}><span aria-hidden="true">▣</span><small>الكتالوج</small></button>
      <button type="button" className={section==="orders"?"active":""} onClick={()=>navigate("orders")}><span aria-hidden="true">🧾</span><small>طلباتي</small></button>
      <button type="button" className="dock-cart" onClick={()=>setCartOpen(true)}><span aria-hidden="true">🛒</span><small>السلة</small>{cartCount>0&&<b>{cartCount}</b>}</button>
      <button type="button" className={section==="account"?"active":""} onClick={()=>navigate("account")}><span aria-hidden="true">♙</span><small>حسابي</small></button>
      {config.showCredit&&<button type="button" className={section==="finance"?"active":""} onClick={()=>navigate("finance")}><span aria-hidden="true">◫</span><small>المالية</small></button>}
    </nav>
    {selectedProduct&&<div className="modal-backdrop" onClick={()=>setSelectedProduct(null)}><section className="modal product-detail-modal" role="dialog" aria-modal="true" aria-labelledby="product-detail-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">تفاصيل الصنف</span><h2 id="product-detail-title">{selectedProduct.name}</h2></div><button aria-label="إغلاق تفاصيل الصنف" onClick={()=>setSelectedProduct(null)}>×</button></div><div className="product-detail-grid">{selectedProduct.imageUrl?<img src={selectedProduct.imageUrl} alt={selectedProduct.name}/>:<div className="product-placeholder large">{selectedProduct.name.slice(0,1)}</div>}<div><span className="sku">{selectedProduct.sku}</span><p>{selectedProduct.description||'لا يوجد وصف إضافي لهذا الصنف.'}</p><div className="detail-facts"><span>الوحدة <strong>{selectedProduct.unit}</strong></span><span>التصنيف <strong>{selectedProduct.category}</strong></span><span>المتاح <strong>{selectedProduct.availableQuantity}</strong></span><span>في السلة <strong>{cart.find(l=>l.product.id===selectedProduct.id)?.quantity??0}</strong></span></div>{effectivePrice(selectedProduct,1)>0?<div className="price-row"><strong>{money(effectivePrice(selectedProduct,1))}</strong></div>:<div className="price-hidden">السعر حسب حسابك</div>}<div className="detail-tier-list">{(tiers[selectedProduct.id]??[]).map(t=><span key={t.min_quantity}>من {t.min_quantity} · {money(t.unit_price,t.currency)}</span>)}</div><button className="add-button" disabled={selectedProduct.availableQuantity<1||effectivePrice(selectedProduct,1)<=0} onClick={async()=>{if(await add(selectedProduct))setSelectedProduct(null);}}>إضافة للسلة</button></div></div></section></div>}
    {selectedOrder&&<div className="modal-backdrop" onClick={()=>setSelectedOrder(null)}><section className="modal order-detail-modal" role="dialog" aria-modal="true" aria-labelledby="customer-order-detail-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">تتبع الطلب</span><h2 id="customer-order-detail-title">طلب #{selectedOrder.order_number}</h2></div><button onClick={()=>setSelectedOrder(null)}>×</button></div><div className="order-detail-summary"><strong>{money(selectedOrder.total,selectedOrder.currency)}</strong><span className={`status status-${selectedOrder.status}`}>{selectedOrder.statusLabel}</span><small>{new Date(selectedOrder.created_at).toLocaleString('ar-YE')}</small></div><div className="timeline">{selectedOrder.timeline.map((step,index)=><div className={`timeline-step ${step.active?'done':''}`} key={`${step.status}-${index}`}><span>{step.active?'✓':index+1}</span><label>{step.label}</label></div>)}</div><div className="order-detail-lines">{selectedOrder.items.map(item=><div key={item.id}><div><strong>{item.name}</strong><small>{item.sku} · {item.unit}</small></div><span>{item.quantity} × {money(item.unit_price,item.currency)}</span><strong>{money(item.line_total,item.currency)}</strong></div>)}</div><div className="order-detail-actions"><button onClick={async()=>{for(const item of selectedOrder.items){const p=products.find(x=>x.id===item.product_id);if(p)await add(p,Math.min(item.quantity,p.availableQuantity));}setSelectedOrder(null);navigate('catalog');}}>إعادة الطلب</button><button className="ghost" onClick={()=>setSelectedOrder(null)}>إغلاق</button></div></section></div>}
    {quickOpen&&config.showQuickOrder&&<div className="modal-backdrop" onClick={()=>setQuickOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="quick-order-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2 id="quick-order-title">الطلب السريع</h2><button onClick={()=>setQuickOpen(false)}>×</button></div><p>أدخل SKU والكمية بسرعة.</p><QuickOrder products={products} onAdd={add}/></section></div>}
    {excelOpen&&<div className="modal-backdrop" onClick={()=>!excelBusy&&setExcelOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="excel-review-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2 id="excel-review-title">مراجعة الطلب من Excel</h2><button disabled={excelBusy} onClick={()=>setExcelOpen(false)}>×</button></div><p>تم تحليل الملف والتحقق من المعرفات والكميات والمخزون. لن تدخل البيانات السلة قبل اعتمادك.</p><div className="excel-review">{excelRows.map((row,index)=><div className="excel-row" key={`${row.identifier}-${index}`}><strong>{row.identifier||'—'}</strong><span>{row.quantity||'—'}</span><span>{row.product?.name??'غير مطابق'}</span><span className={row.error?'error-text':'ok-text'}>{row.error??'جاهز'}</span></div>)}</div><button className="checkout" disabled={excelBusy||excelRows.some(row=>Boolean(row.error)||!row.product)} onClick={()=>void confirmQuickExcel()}>{excelBusy?'جارٍ اعتماد الملف…':'اعتماد وإضافة إلى السلة'}</button></section></div>}
    {cartOpen&&<div className="drawer-backdrop" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-drawer-title" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2 id="cart-drawer-title">السلة · {cartCount}</h2><button aria-label="إغلاق السلة" onClick={()=>setCartOpen(false)}>×</button></div>{cart.map(l=>{const next=nextTier(l.product,l.quantity);return <div className="drawer-line" key={l.product.id}><div><strong>{l.product.name}</strong><small>{money(l.unitPrice)} / {l.product.unit}</small>{config.showSavingsCalculator&&next&&<small className="saving">تبقى {next.min_quantity-l.quantity} للوصول للسعر التالي</small>}</div><div className="quantity"><button onClick={()=>void update(l.product.id,l.quantity-1)}>−</button><span>{l.quantity}</span><button onClick={()=>void update(l.product.id,l.quantity+1)}>+</button></div>{config.requireQuantityConfirmation&&<button className={confirmed[l.product.id]?'confirmed':'confirm'} onClick={()=>setQtyConfirmed(l.product.id,!confirmed[l.product.id])}>{confirmed[l.product.id]?'✓ معتمد':'اعتماد الكمية'}</button>}</div>})}<div className="drawer-total"><span>الإجمالي</span><strong>{money(total)}</strong></div>{config.showPaymentMethods&&<div className="payment-box"><strong>طريقة الدفع</strong>{PAYMENT_OPTIONS.filter(x=>config[x.field]).map(x=><label key={x.key}><input type="radio" checked={payment===x.key} onChange={()=>setPayment(x.key)}/>{x.label}</label>)}</div>}{config.showTemplates&&<label className="template-inline"><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="حفظ كمسحة"/><button disabled={busy||!templateName.trim()} onClick={()=>void saveTemplate()}>حفظ</button></label>}<button className="checkout" disabled={busy||!cart.length} onClick={()=>void submit()}>{busy?'جارٍ إرسال الطلب…':'تأكيد وإرسال الطلب'}</button></aside></div>}
  </div>;
}

function QuickOrder({products,onAdd}:{products:Product[];onAdd:(p:Product,q?:number)=>Promise<boolean>}){const [sku,setSku]=useState('');const [qty,setQty]=useState('1');const [resolved,setResolved]=useState<Product|null>(null);const [resolving,setResolving]=useState(false);const [lookupError,setLookupError]=useState('');const normalized=sku.trim().toLowerCase();const local=products.find(p=>p.sku.toLowerCase()===normalized)??null;const found=local??resolved;const numericQty=Number(qty);const validQty=Number.isSafeInteger(numericQty)&&numericQty>=1;useEffect(()=>{setResolved(null);setLookupError('');},[sku]);async function resolveAndAdd(){if(!validQty||resolving)return;setResolving(true);setLookupError('');try{let product=found;if(!product){const rows=await getCatalog(sku.trim(),null,5,0);const exact=rows.find(item=>item.sku.toLowerCase()===normalized||(item.barcode??'').toLowerCase()===normalized);if(exact){product=mapProduct(exact,'أصناف');setResolved(product);}}if(!product){setLookupError('لم يتم العثور على SKU أو باركود مصرح به لهذا الحساب.');return;}if(await onAdd(product,numericQty)){setSku('');setResolved(null);}}catch(e){setLookupError(e instanceof Error?e.message:'تعذر البحث عن الصنف.');}finally{setResolving(false);}}return <div className="quick-editor"><input aria-label="SKU أو باركود المنتج" value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU أو الباركود"/><input aria-label="الكمية" value={qty} onChange={e=>setQty(e.target.value)} type="number" min="1" placeholder="الكمية"/><button disabled={resolving||!validQty} onClick={()=>void resolveAndAdd()}>{resolving?'جارٍ البحث…':'إضافة'}</button>{found&&<div className="quick-result" role="status">{found.name} · متاح {found.availableQuantity} {found.unit}</div>}{lookupError&&<div className="error-banner" role="alert">{lookupError}</div>}</div>}
