import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import readXlsxFile from './lib/read-excel-file-browser';
import type { CartLine, Product } from './domain/types';
import { calculateClientPreviewTotal, MAX_ORDER_QUANTITY_PER_LINE } from './domain/order';
import { resolveCustomerPortalPrice } from './domain/customerPricing';
import { formatMoney } from './domain/pricing';
import { getCatalog, getProductImageUrls, type CatalogItem } from './services/catalog';
import { getCategories, type CategoryOption } from './services/categories';
import { getCart, removeCartItem, setCartItem, syncOfflineCart } from './services/cart';
import { pendingOfflineOperations, type OfflineOperation } from './services/offlineQueue';
import { createOrder } from './services/orders';
import { applyQuickOrder } from './services/quickOrder';
import type { CustomerOrderSummary } from './services/customerOrders';
import { firstEnabledPaymentMethod, isPaymentMethodEnabled } from './domain/customerPolicy';
import { findProductByIdentifier } from './domain/productIdentifier';
import { getSession, signIn, signOut } from './services/auth';
import { createOrderTemplate, deleteOrderTemplate, getOrderTemplates, applyOrderTemplate, type OrderTemplate } from './services/orderTemplates';
import { supabase } from './lib/supabase';
import AdminPanel from './AdminPanel';
import CommandPalette from './CommandPalette';
import './styles.css';
import './customer-portal-v3.css';
import './customer-portal-v3-dynamic.css';

import { isStaffPortalRole, type UserRole } from './domain/roles';
const CUSTOMER_STATUS_LABELS: Record<string, string> = { draft: 'مسودة', pending: 'قيد المراجعة', confirmed: 'مؤكد', preparing: 'قيد التجهيز', ready: 'جاهز', completed: 'مكتمل', cancelled: 'ملغي' };
const CUSTOMER_ORDER_STEPS = ['pending', 'confirmed', 'preparing', 'ready', 'completed'] as const;
type PriceTier = { min_quantity: number; unit_price: number; currency: string };
type Finance = { currency: string; creditLimit: number; outstanding: number; available: number; entries: Array<{ id: string; reference?: string; description: string; debit: number; credit: number; due_date?: string; status: string; created_at: string }> };
type ClientUiConfig = {
  showSearch:boolean; showCategories:boolean; showExcel:boolean; showCredit:boolean; showTemplates:boolean; showInventory:boolean; showRetailPrice:boolean; showQuickOrder:boolean; accentColor:string; compactLayout:boolean;
  requireQuantityConfirmation:boolean; showTieredPricing:boolean; showSavingsCalculator:boolean; showImageSearch:boolean; showVoiceSearch:boolean; showPaymentMethods:boolean;
  paymentOnCredit:boolean; paymentCash:boolean; paymentTransfer:boolean; minOrderValue:number; maxOrderValue:number; maxTemplates:number;
};
const DEFAULT_UI_CONFIG: ClientUiConfig = { showSearch:true, showCategories:true, showExcel:true, showCredit:true, showTemplates:true, showInventory:true, showRetailPrice:false, showQuickOrder:true, accentColor:'#0d91a5', compactLayout:false, requireQuantityConfirmation:true, showTieredPricing:true, showSavingsCalculator:true, showImageSearch:false, showVoiceSearch:false, showPaymentMethods:true, paymentOnCredit:true, paymentCash:true, paymentTransfer:true, minOrderValue:0, maxOrderValue:0, maxTemplates:50 };
const PAYMENT_OPTIONS = [{key:'credit' as const,label:'آجل / ائتمان',field:'paymentOnCredit' as const},{key:'cash' as const,label:'نقدي',field:'paymentCash' as const},{key:'transfer' as const,label:'حوالة',field:'paymentTransfer' as const}];
function mapProduct(item: CatalogItem, categoryName: string, imageUrl?: string): Product { return { id:item.id, sku:item.sku, barcode:item.barcode ?? undefined, name:item.name, unit:item.unit, category:categoryName, description:item.description ?? undefined, availableQuantity:item.available_quantity, status:item.status === 'active' ? 'active' : 'inactive', imageUrl, authorizedPrice:item.authorized_price ?? undefined, currency:item.currency }; }
function money(value:number,currency='YER'){return `${formatMoney(value)} ${currency==='YER'?'ر.ي':currency}`;}
type QuickExcelLine = { identifier:string; quantity:number; product:Product|null; error:string|null };

export default function AppV3Fixed(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [signedIn,setSignedIn]=useState(false); const [ready,setReady]=useState(false); const [role,setRole]=useState<UserRole>('viewer'); const [customerId,setCustomerId]=useState<string|null>(null); const [organizationId,setOrganizationId]=useState<string|null>(null); const [warehouseId,setWarehouseId]=useState<string|null>(null); const [customerName,setCustomerName]=useState('تاجر الأغبري');
  const [config,setConfig]=useState<ClientUiConfig>(DEFAULT_UI_CONFIG); const [query,setQuery]=useState(''); const [catalogQuery,setCatalogQuery]=useState(''); const [categoryId,setCategoryId]=useState<string|null>(null); const [categories,setCategories]=useState<CategoryOption[]>([]); const [products,setProducts]=useState<Product[]>([]); const [tiers,setTiers]=useState<Record<string,PriceTier[]>>({}); const [cart,setCart]=useState<CartLine[]>([]); const [cartOpen,setCartOpen]=useState(false); const [quickOpen,setQuickOpen]=useState(false); const [excelOpen,setExcelOpen]=useState(false); const [excelRows,setExcelRows]=useState<QuickExcelLine[]>([]); const [excelBusy,setExcelBusy]=useState(false); const [section,setSection]=useState<'catalog'|'orders'|'finance'|'templates'>('catalog');
  const [catalogLoadingMore,setCatalogLoadingMore]=useState(false); const [catalogHasMore,setCatalogHasMore]=useState(true); const [operationalLoading,setOperationalLoading]=useState(false);
  const [selectedProduct,setSelectedProduct]=useState<Product|null>(null);
  const [orders,setOrders]=useState<CustomerOrderSummary[]>([]); const [finance,setFinance]=useState<Finance|null>(null); const [authUserId,setAuthUserId]=useState<string|null>(null); const [offlineOps,setOfflineOps]=useState<OfflineOperation[]>([]); const [offlineCenterOpen,setOfflineCenterOpen]=useState(false); const [templates,setTemplates]=useState<OrderTemplate[]>([]); const [templateName,setTemplateName]=useState(''); const [confirmed,setConfirmed]=useState<Record<string,boolean>>({}); const [payment,setPayment]=useState<'credit'|'cash'|'transfer'>('credit'); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [isOnline,setIsOnline]=useState(()=>typeof navigator==='undefined'||navigator.onLine); const [syncingOffline,setSyncingOffline]=useState(false); const [commandOpen,setCommandOpen]=useState(false); const searchRef=useRef<HTMLInputElement>(null); const syncingOfflineRef=useRef(false);
  const loadConfig=useCallback(async(orgId:string)=>{ if(!supabase)return; const {data,error:configError}=await supabase.from('client_ui_settings').select('config').eq('organization_id',orgId).maybeSingle(); if(configError)throw configError; const nextConfig:ClientUiConfig=data?.config?{...DEFAULT_UI_CONFIG,...(data.config as Partial<ClientUiConfig>)}:DEFAULT_UI_CONFIG; setConfig(nextConfig); const fallbackPayment=firstEnabledPaymentMethod(nextConfig); if(fallbackPayment)setPayment(current=>isPaymentMethodEnabled(nextConfig,current)?current:fallbackPayment); },[]);
  const loadIdentity=useCallback(async(userId:string)=>{setAuthUserId(userId);if(!supabase)return;const {data,error:profileError}=await supabase.from('profiles').select('customer_id,role,organization_id').eq('id',userId).single();if(profileError)throw profileError;setRole((data?.role as UserRole)??'viewer');setCustomerId(data?.customer_id??null);setOrganizationId(data?.organization_id??null);if(data?.organization_id){await loadConfig(data.organization_id);const {data:warehouse,error:warehouseError}=await supabase.from('warehouses').select('id').eq('organization_id',data.organization_id).eq('is_active',true).order('created_at').limit(1).maybeSingle();if(warehouseError)throw warehouseError;setWarehouseId(warehouse?.id??null);}if(data?.customer_id){const {data:customer,error:customerError}=await supabase.from('customers').select('name').eq('id',data.customer_id).maybeSingle();if(customerError)throw customerError;if(customer?.name)setCustomerName(customer.name);setTemplates(await getOrderTemplates());}},[loadConfig]);
  useEffect(()=>{let dead=false;void getSession().then(async s=>{if(dead)return;setSignedIn(Boolean(s));setReady(true);if(s)await loadIdentity(s.user.id);}).catch(e=>{if(!dead){setReady(true);setError(e instanceof Error?e.message:'تعذر قراءة الجلسة.');}});const sub=supabase?.auth.onAuthStateChange((event,s)=>{if(dead)return;setSignedIn(Boolean(s));if(s&&(event==='SIGNED_IN'||event==='TOKEN_REFRESHED'))void loadIdentity(s.user.id);if(!s){setAuthUserId(null);setOfflineOps([]);setOfflineCenterOpen(false);setCustomerId(null);setOrganizationId(null);setWarehouseId(null);setRole('viewer');setProducts([]);setCart([]);setFinance(null);setOrders([]);setTemplates([]);setConfig(DEFAULT_UI_CONFIG);}});return()=>{dead=true;sub?.data.subscription.unsubscribe();};},[loadIdentity]);
  useEffect(()=>{if(!signedIn||!organizationId||!supabase)return;const channel=supabase.channel(`b2b-ui-${organizationId}`).on('postgres_changes',{event:'*',schema:'public',table:'client_ui_settings',filter:`organization_id=eq.${organizationId}`},()=>void loadConfig(organizationId));channel.subscribe();const timer=window.setInterval(()=>void loadConfig(organizationId),15000);return()=>{supabase.removeChannel(channel);window.clearInterval(timer);};},[signedIn,organizationId,loadConfig]);
  const refreshOfflineState=useCallback(()=>{setOfflineOps(authUserId?pendingOfflineOperations<OfflineOperation>(authUserId):[]);},[authUserId]);
  const flushOfflineCart=useCallback(async()=>{if(!signedIn||!customerId||typeof navigator==='undefined'||!navigator.onLine||syncingOfflineRef.current)return;syncingOfflineRef.current=true;setSyncingOffline(true);try{const result=await syncOfflineCart();if(result.processed>0)setMessage(`تمت مزامنة ${result.processed} عملية سلة محفوظة بعد عودة الاتصال.`);if(result.failed>0)setError(`تعذر مزامنة ${result.failed} عملية محفوظة؛ ستبقى محفوظة للمحاولة التالية.`);}catch(e){setError(e instanceof Error?e.message:'تعذر مزامنة عمليات السلة المحفوظة.');}finally{syncingOfflineRef.current=false;setSyncingOffline(false);}},[signedIn,customerId,refreshOfflineState]);
  useEffect(()=>{const online=()=>{setIsOnline(true);void flushOfflineCart();void refreshOfflineState();};const offline=()=>setIsOnline(false);window.addEventListener('online',online);window.addEventListener('offline',offline);if(typeof navigator!=='undefined')setIsOnline(navigator.onLine);void flushOfflineCart();refreshOfflineState();const timer=window.setInterval(refreshOfflineState,5000);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offline);window.clearInterval(timer);};},[flushOfflineCart,refreshOfflineState]);
  useEffect(()=>{if(!signedIn)return;const onKeyDown=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();setCommandOpen(true);}if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='TEXTAREA'){event.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[signedIn]);
  useEffect(()=>{if(!signedIn)return;const hasModal=Boolean(selectedProduct||quickOpen||excelOpen||offlineCenterOpen||cartOpen);if(!hasModal)return;const onKeyDown=(event:KeyboardEvent)=>{if(event.key!=='Escape')return;if(busy||excelBusy||syncingOffline)return;if(selectedProduct)setSelectedProduct(null);else if(excelOpen)setExcelOpen(false);else if(offlineCenterOpen)setOfflineCenterOpen(false);else if(quickOpen)setQuickOpen(false);else if(cartOpen)setCartOpen(false);};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[signedIn,selectedProduct,quickOpen,excelOpen,offlineCenterOpen,cartOpen,busy,excelBusy,syncingOffline]);
  useEffect(()=>{const timer=window.setTimeout(()=>setCatalogQuery(query),250);return()=>window.clearTimeout(timer);},[query]);
  const loadCategories=useCallback(async()=>{if(!signedIn||!customerId||!supabase)return;try{const nextCategories=await getCategories();setCategories(nextCategories);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل التصنيفات.');}},[signedIn,customerId]);

  const loadCatalogData=useCallback(async()=>{if(!signedIn||!customerId||!supabase)return;setLoading(true);setError('');try{const [items,saved]=await Promise.all([getCatalog(catalogQuery,categoryId,60,0,warehouseId??undefined),getCart()]);const cmap=new Map(categories.map(c=>[c.id,c.name]));const urls=await getProductImageUrls(items.map(i=>i.image_path));const mapped=items.map(i=>mapProduct(i,cmap.get(i.category_id??'')??'أصناف',i.image_path?urls.get(i.image_path):undefined));setProducts(mapped);setCatalogHasMore(items.length===60);const grouped:Record<string,PriceTier[]>={};const tierProductIds=[...new Set([...items.map(i=>i.id),...saved.map(i=>i.product_id)])];if(tierProductIds.length){const {data:rows,error:tiersError}=await supabase.from('customer_price_tiers').select('product_id,min_quantity,unit_price,currency').eq('customer_id',customerId).in('product_id',tierProductIds).order('min_quantity');if(tiersError)throw tiersError;for(const row of rows??[])(grouped[row.product_id]??=[]).push({min_quantity:Number(row.min_quantity),unit_price:Number(row.unit_price),currency:row.currency});}setTiers(grouped);setCart(saved.map(i=>{const p=mapped.find(x=>x.id===i.product_id)??({id:i.product_id,sku:i.sku,name:i.name,unit:i.unit,category:'أصناف',availableQuantity:0,status:'active',authorizedPrice:i.authorized_price??undefined,currency:i.currency} as Product);const resolved=resolveCustomerPortalPrice({authorizedPrice:p.authorizedPrice??i.authorized_price??null,authorizedCurrency:p.currency??i.currency,tiers:(grouped[i.product_id]??[]).map(x=>({minQuantity:x.min_quantity,unitPrice:x.unit_price,currency:x.currency})),quantity:i.quantity});return{product:p,quantity:i.quantity,unitPrice:resolved.unitPrice};}));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الكتالوج.');}finally{setLoading(false);}},[signedIn,customerId,warehouseId,catalogQuery,categoryId,categories]);

  const loadOperationalData=useCallback(async()=>{if(!signedIn||!customerId||!supabase)return;setOperationalLoading(true);try{const [{data:orderRows,error:ordersError},{data:account,error:accountError},{data:ledger,error:ledgerError}]=await Promise.all([supabase.from('orders').select('id,order_number,total,currency,status,created_at').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(30),supabase.from('customer_credit_accounts').select('currency,credit_limit,outstanding_balance,available_credit').eq('customer_id',customerId).maybeSingle(),supabase.from('customer_ledger_entries').select('id,reference,description,debit,credit,due_date,status,created_at').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(50)]);if(ordersError||accountError||ledgerError)throw ordersError??accountError??ledgerError;setOrders((orderRows??[]) as CustomerOrderSummary[]);setFinance(account?{currency:account.currency,creditLimit:Number(account.credit_limit),outstanding:Number(account.outstanding_balance),available:Number(account.available_credit),entries:(ledger??[]).map(e=>({...e,debit:Number(e.debit),credit:Number(e.credit)}))}:null);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل بيانات الحساب التشغيلية.');}finally{setOperationalLoading(false);}},[signedIn,customerId]);

  useEffect(()=>{void loadCategories();},[loadCategories]);
  useEffect(()=>{void loadCatalogData();},[loadCatalogData]);
  useEffect(()=>{void loadOperationalData();},[loadOperationalData]);

  const total=calculateClientPreviewTotal(cart);const cartCount=cart.reduce((s,l)=>s+l.quantity,0);const categoriesView=useMemo(()=>[{id:null,name:'الكل'},...categories],[categories]);
  function effectivePrice(p:Product,q:number){const list=tiers[p.id]??[];return resolveCustomerPortalPrice({authorizedPrice:p.authorizedPrice,authorizedCurrency:p.currency,tiers:list.map(x=>({minQuantity:x.min_quantity,unitPrice:x.unit_price,currency:x.currency})),quantity:q}).unitPrice;}
  function nextTier(p:Product,q:number){return (tiers[p.id]??[]).filter(x=>x.min_quantity>q).sort((a,b)=>a.min_quantity-b.min_quantity)[0];}
  function setQtyConfirmed(id:string,value:boolean){setConfirmed(c=>({...c,[id]:value}));}
  function navigate(next:typeof section){if(next!==section&&config.requireQuantityConfirmation&&cart.some(l=>!confirmed[l.product.id])){setError('اعتمد كميات السلة أولاً قبل الانتقال إلى قسم آخر.');setCartOpen(true);return;}setError('');setSection(next);}
  async function add(p:Product,q=1){const price=effectivePrice(p,q);if(price<=0)return setError('لا يوجد سعر مصرح به لهذا الصنف.');if(q<1||q>p.availableQuantity)return setError('الكمية المطلوبة غير متاحة.');const existing=cart.find(l=>l.product.id===p.id);const next=Math.min((existing?.quantity??0)+q,p.availableQuantity);try{await setCartItem(p.id,next);setCart(c=>existing?c.map(l=>l.product.id===p.id?{...l,quantity:next,unitPrice:effectivePrice(p,next)}:l):[...c,{product:p,quantity:next,unitPrice:price}]);setQtyConfirmed(p.id,!config.requireQuantityConfirmation);setCartOpen(true);setError('');}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث السلة.');}}
  async function update(id:string,q:number){const line=cart.find(l=>l.product.id===id);if(!line)return;const next=Math.max(0,Math.min(q,line.product.availableQuantity));try{if(!next){await removeCartItem(id);setCart(c=>c.filter(l=>l.product.id!==id));setConfirmed(c=>{const n={...c};delete n[id];return n;});}else{await setCartItem(id,next);setCart(c=>c.map(l=>l.product.id===id?{...l,quantity:next,unitPrice:effectivePrice(l.product,next)}:l));setQtyConfirmed(id,!config.requireQuantityConfirmation);}}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث الكمية.');}}
  async function submit(){if(!customerId||!cart.length||busy)return;if(config.requireQuantityConfirmation&&cart.some(l=>!confirmed[l.product.id]))return setError('يجب اعتماد جميع الكميات قبل إرسال الطلب.');if(config.minOrderValue>0&&total<config.minOrderValue)return setError(`الحد الأدنى للطلب ${money(config.minOrderValue)}.`);if(config.maxOrderValue>0&&total>config.maxOrderValue)return setError(`الحد الأعلى للطلب ${money(config.maxOrderValue)}.`);if(config.showPaymentMethods&&!PAYMENT_OPTIONS.some(x=>x.key===payment&&config[x.field]))return setError('وسيلة الدفع المختارة غير متاحة حاليًا.');setBusy(true);setError('');try{const result=await createOrder({customerId,idempotencyKey:crypto.randomUUID(),lines:cart.map(l=>({productId:l.product.id,quantity:l.quantity}))},warehouseId??undefined,{ paymentMethod: payment });setCart([]);setConfirmed({});setCartOpen(false);setMessage(`تم إرسال الطلب #${result.order_number} بنجاح.`);setSection('orders');void loadOperationalData();}catch(e){setError(e instanceof Error?e.message:'تعذر إرسال الطلب.');}finally{setBusy(false);}}
  async function saveTemplate(){if(!cart.length||!templateName.trim()||busy)return;setBusy(true);setError('');setMessage('');try{const item=await createOrderTemplate({name:templateName,branchLabel:'الفرع الرئيسي',lines:cart.map(l=>({productId:l.product.id,sku:l.product.sku,name:l.product.name,unit:l.product.unit,quantity:l.quantity}))});setTemplates(current=>[item,...current].slice(0,config.maxTemplates));setTemplateName('');setMessage('تم حفظ المسحة في قاعدة البيانات.');}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ المسحة.');}finally{setBusy(false);}}
  async function removeTemplate(id:string){if(busy)return;setBusy(true);setError('');setMessage('');try{await deleteOrderTemplate(id);setTemplates(current=>current.filter(item=>item.id!==id));setMessage('تم حذف المسحة.');}catch(e){setError(e instanceof Error?e.message:'تعذر حذف المسحة.');}finally{setBusy(false);}}
  async function applyTemplate(t:OrderTemplate){if(busy)return;setBusy(true);setError('');setMessage('');try{await applyOrderTemplate(t.id,warehouseId??undefined);const saved=await getCart();setCart(saved.map(i=>{const p=products.find(x=>x.id===i.product_id)??({id:i.product_id,sku:i.sku,name:i.name,unit:i.unit,category:'أصناف',availableQuantity:0,status:'active'} as Product);return{product:p,quantity:i.quantity,unitPrice:i.authorized_price??0};}));setConfirmed({});setCartOpen(true);setMessage('تم تطبيق المسحة على السلة عبر العملية الذرية.');setSection('catalog');}catch(e){setError(e instanceof Error?e.message:'تعذر تطبيق المسحة.');}finally{setBusy(false);}}
  async function reorderOrder(orderId:string,orderNumber:number){if(!supabase){setError('خدمة الطلبات غير متاحة.');return;}try{const {data:items,error:itemsError}=await supabase.from('order_items').select('product_id,quantity').eq('order_id',orderId);if(itemsError)throw itemsError;const ids=[...new Set((items??[]).map(item=>item.product_id))];if(!ids.length){setError('الطلب السابق لا يحتوي أصنافًا قابلة لإعادة التجهيز.');return;}const {data:refs,error:refsError}=await supabase.from('products').select('id,sku').in('id',ids);if(refsError)throw refsError;const skuById=new Map((refs??[]).map(item=>[item.id,item.sku]));const resolved=await Promise.all((items??[]).map(async item=>{const sku=skuById.get(item.product_id);if(!sku)return null;const found=await getCatalog(sku,null,5,0,warehouseId??undefined);const exact=found.find(product=>product.sku.toLowerCase()===String(sku).toLowerCase());if(!exact||exact.status!=='active'||exact.available_quantity<1)return null;return {product:mapProduct(exact,'أصناف'),quantity:Math.min(Number(item.quantity),exact.available_quantity,MAX_ORDER_QUANTITY_PER_LINE)};}));let added=0;for(const item of resolved){if(item&&item.quantity>0){await add(item.product,item.quantity);added++;}}if(added){setMessage(`تم تجهيز ${added} أصناف من طلب #${orderNumber} بالأسعار والمخزون الحاليين.`);setSection('catalog');}else setError('لم تعد أصناف الطلب السابق متاحة أو مصرحًا بها حاليًا.');}catch(e){setError(e instanceof Error?e.message:'تعذر تجهيز إعادة الطلب.');}}
  async function reorderLatest(){const latest=orders[0];if(!latest){setError('لا يوجد طلب سابق لإعادة الطلب.');return;}await reorderOrder(latest.id,latest.order_number);}
  async function stageQuickExcel(file:File){setExcelBusy(true);setError('');setMessage('');try{const raw=await readXlsxFile(file) as unknown;const rows=Array.isArray(raw)?raw.filter(Array.isArray) as unknown[][]:[];if(!rows.length)throw new Error('ملف Excel فارغ.');if(rows.length>101)throw new Error('ملف الطلب السريع يتجاوز 100 صف.');const first=rows[0]?.map(cell=>String(cell??'').trim().toLowerCase())??[];const hasHeader=first.some(v=>['sku','identifier','product code','الرمز','الصنف','sku/الباركود'].includes(v));const dataRows=rows.slice(hasHeader?1:0);const seen=new Set<string>();const nextRows:QuickExcelLine[]=[];for(const row of dataRows){const identifier=String(row?.[0]??'').trim();const quantity=Number(row?.[1]);if(!identifier&&!row?.[1])continue;let rowError:string|null=null;if(!identifier)rowError='المعرف مطلوب.';else if(seen.has(identifier.toLowerCase()))rowError='العنصر مكرر في الملف.';else if(!Number.isSafeInteger(quantity)||quantity<1)rowError='الكمية يجب أن تكون عددًا صحيحًا موجبًا.';let product:Product|null=null;if(!rowError){seen.add(identifier.toLowerCase());product=findProductByIdentifier(products, identifier);if(!product){const found=await getCatalog(identifier,null,5,0,warehouseId??undefined);const candidateProducts=found.map(item=>mapProduct(item,'أصناف'));product=findProductByIdentifier(candidateProducts,identifier);}if(!product)rowError='المعرف غير موجود أو غير مصرح به لهذا العميل.';else if(product.status!=='active')rowError='الصنف غير نشط.';else if(quantity>product.availableQuantity)rowError=`المخزون المتاح ${product.availableQuantity} فقط.`;else if(quantity>MAX_ORDER_QUANTITY_PER_LINE)rowError=`الكمية تتجاوز الحد الأقصى ${MAX_ORDER_QUANTITY_PER_LINE}.`;}nextRows.push({identifier,quantity,product,error:rowError});}if(!nextRows.length)throw new Error('لم توجد صفوف صالحة للمعالجة.');setExcelRows(nextRows);setExcelOpen(true);}catch(e){setExcelRows([]);setError(e instanceof Error?e.message:'تعذر تحليل ملف الطلب السريع.');}finally{setExcelBusy(false);}}
  async function confirmQuickExcel(){const invalid=excelRows.filter(row=>row.error||!row.product);if(invalid.length)return setError('يجب إصلاح جميع أخطاء ملف الطلب قبل الاعتماد.');if(!warehouseId)return setError('لا يوجد مستودع نشط متاح للحساب الحالي.');setExcelBusy(true);setError('');setMessage('');try{await applyQuickOrder({idempotencyKey:crypto.randomUUID(),warehouseId,lines:excelRows.map(row=>({productId:row.product!.id,quantity:row.quantity}))});await loadCatalogData();setExcelRows([]);setExcelOpen(false);setCartOpen(true);setMessage('تم اعتماد الطلب السريع وإضافة الأصناف إلى السلة وتسجيل العملية.');}catch(e){setError(e instanceof Error?e.message:'تعذر اعتماد الطلب السريع.');}finally{setExcelBusy(false);}}
  const retryableOfflineCount=offlineOps.filter(operation=>!operation.terminal).length; const terminalOfflineCount=offlineOps.filter(operation=>operation.terminal).length;
  const commandActions=useMemo(()=>[
    {id:'catalog',label:'فتح الكتالوج',hint:'الأصناف والأسعار المصرح بها',icon:'▦',onSelect:()=>navigate('catalog'),keywords:['منتجات','اصناف']},
    {id:'orders',label:'فتح الطلبات',hint:'المتابعة وإعادة الطلب',icon:'↗',onSelect:()=>navigate('orders'),keywords:['طلبات','شحن']},
    {id:'latest-order',label:'إعادة تجهيز آخر طلب',hint:'تجهيز الأصناف المتاحة من آخر طلب',icon:'↻',onSelect:()=>void reorderLatest(),keywords:['إعادة طلب','reorder']},
    ...(config.showTemplates ? [{id:'templates',label:'الطلبات المحفوظة',hint:'المسحات المتكررة',icon:'▤',onSelect:()=>navigate('templates'),keywords:['مسحات','قوائم']}] : []),
    ...(config.showCredit ? [{id:'finance',label:'المركز المالي',hint:'الرصيد والائتمان والكشف',icon:'◫',onSelect:()=>navigate('finance'),keywords:['مالية','كشف','ائتمان']}] : []),
    {id:'quick-order',label:'الطلب السريع',hint:'SKU + الكمية',icon:'⚡',onSelect:()=>setQuickOpen(true),keywords:['sku','سريع']},
    ...(config.showExcel ? [{id:'excel',label:'استيراد طلب Excel',hint:'رفع ومراجعة الملف',icon:'⇧',onSelect:()=>document.getElementById('aghbari-excel-input')?.click(),keywords:['excel','استيراد']}] : []),
    {id:'cart',label:'فتح السلة',hint:'مراجعة الكميات والدفع',icon:'🛒',onSelect:()=>setCartOpen(true),keywords:['سلة','checkout']},
    ...(offlineOps.length ? [{id:'recovery',label:'مركز الاسترداد',hint:`${retryableOfflineCount} للمحاولة · ${terminalOfflineCount} نهائية`,icon:'⚠',onSelect:()=>setOfflineCenterOpen(true),keywords:['offline','استرداد','تعارض','مزامنة']}] : []),
    {id:'search',label:'البحث السريع',hint:'الاختصار / يركز البحث',icon:'⌕',onSelect:()=>requestAnimationFrame(()=>searchRef.current?.focus()),keywords:['بحث','باركود']},
  ],[orders,products,finance,config,cart,offlineOps,retryableOfflineCount,terminalOfflineCount]);
  async function loadMoreCatalog(){if(catalogLoadingMore||!catalogHasMore||!supabase)return;setCatalogLoadingMore(true);setError('');try{const items=await getCatalog(catalogQuery,categoryId,60,products.length,warehouseId??undefined);if(!items.length){setCatalogHasMore(false);return;}const cmap=new Map(categories.map(c=>[c.id,c.name]));const urls=await getProductImageUrls(items.map(i=>i.image_path));const mapped=items.map(i=>mapProduct(i,cmap.get(i.category_id??'')??'أصناف',i.image_path?urls.get(i.image_path):undefined));setProducts(current=>[...current.filter(existing=>!mapped.some(next=>next.id===existing.id)),...mapped]);if(items.length<60)setCatalogHasMore(false);if(items.length){const {data:rows,error:tiersError}=await supabase.from('customer_price_tiers').select('product_id,min_quantity,unit_price,currency').eq('customer_id',customerId).in('product_id',items.map(i=>i.id)).order('min_quantity');if(tiersError)throw tiersError;const grouped:Record<string,PriceTier[]>={};for(const row of rows??[])(grouped[row.product_id]??=[]).push({min_quantity:Number(row.min_quantity),unit_price:Number(row.unit_price),currency:row.currency});setTiers(current=>({...current,...grouped}));}}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المزيد من الأصناف.');}finally{setCatalogLoadingMore(false);}}
  function downloadStatement(){if(!finance)return;const rows=[['المرجع','البيان','مدين','دائن','الاستحقاق','الحالة'],...finance.entries.map(e=>[e.reference??'-',e.description,String(e.debit),String(e.credit),e.due_date??'-',e.status])];const csv='\ufeff'+rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aghbari-statement-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await signIn(email,password);if(!s)throw new Error('تعذر إنشاء جلسة دخول صالحة.');await loadIdentity(s.user.id);setSignedIn(true);setReady(true);}catch(e){setSignedIn(false);setReady(true);setError(e instanceof Error?e.message:'تعذر تسجيل الدخول.');}finally{setBusy(false);}}
  async function logout(){await signOut();}
  if(!ready)return <div className="customer-shell"><div className="portal-loading">جارٍ تجهيز بوابة الأغبري…</div></div>;
  if(!signedIn)return <div className="customer-shell auth-shell"><div className="auth-card"><span className="eyebrow">AGHBARI B2B</span><h1>بوابة الأغبري التجارية</h1><p>شراء جملة سريع، أسعار مصرح بها، ومتابعة مالية وتشغيلية في مكان واحد.</p><form onSubmit={login}><label htmlFor="login-email">البريد الإلكتروني</label><input id="login-email" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="البريد الإلكتروني" autoComplete="email" required/><label htmlFor="login-password">كلمة المرور</label><input id="login-password" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="كلمة المرور" autoComplete="current-password" required/><button disabled={busy} aria-busy={busy}>{busy?'جارٍ الدخول…':'دخول آمن'}</button></form>{error&&<div className="error-banner" role="alert" aria-live="assertive">{error}</div>}</div></div>;
  if(isStaffPortalRole(role)){const roleLabels:Record<string,string>={owner:'مالك',admin:'مدير',sales:'مبيعات',warehouse:'مخزون',viewer:'قارئ'};return <div className="staff-shell"><header className="staff-topbar"><div className="staff-brand"><span className="eyebrow">الأغبري</span><strong>مركز الإدارة والتشغيل</strong><small>دور الحساب: {roleLabels[role]??role}</small></div><div className="staff-actions"><span className="staff-connection" role="status">{isOnline?'● متصل':'● دون اتصال'}</span><button type="button" onClick={()=>void logout()}>خروج</button></div></header><main className="staff-main"><AdminPanel role={role as 'owner'|'admin'|'sales'|'warehouse'|'viewer'}/></main></div>;}
  return <div className={`customer-shell ${config.compactLayout?'density-compact':'density-comfortable'}`} data-density={config.compactLayout?'compact':'comfortable'} style={{'--aghbari-accent':config.accentColor} as CSSProperties}><header className="portal-header"><div><span className="eyebrow">B2B ENTERPRISE</span><h1>بوابة الأغبري</h1><small>مرحبًا، {customerName}</small></div><div className="header-actions"><span className={`connection ${isOnline?"":"offline"}`} role="status">{isOnline?(syncingOffline?"↻ تتم مزامنة السلة…":"● متصل"):"● دون اتصال — العمليات محفوظة محليًا"}</span><button className="command-launch-button" type="button" onClick={()=>setCommandOpen(true)} aria-label="فتح أوامر الأغبري"><span>⌘K</span><small>الأوامر</small></button>{offlineOps.length>0&&<button className={`offline-center-button ${terminalOfflineCount>0?"has-terminal":""}`} type="button" onClick={()=>setOfflineCenterOpen(true)} aria-label="فتح مركز الاسترداد"><span>⚠</span><b>{offlineOps.length}</b></button>}<button onClick={()=>setCartOpen(true)}>السلة <b>{cartCount}</b></button><button className="ghost" onClick={()=>void logout()}>خروج</button></div></header>
    <div className="portal-body"><aside className="portal-nav" aria-label="تنقل البوابة"><button className={section==='catalog'?'active':''} aria-current={section==='catalog'?'page':undefined} onClick={()=>navigate('catalog')}>الكتالوج</button><button className={section==='orders'?'active':''} aria-current={section==='orders'?'page':undefined} onClick={()=>navigate('orders')}>طلباتي</button>{config.showTemplates&&<button className={section==='templates'?'active':''} aria-current={section==='templates'?'page':undefined} onClick={()=>navigate('templates')}>المسحات</button>}{config.showCredit&&<button className={section==='finance'?'active':''} aria-current={section==='finance'?'page':undefined} onClick={()=>navigate('finance')}>المركز المالي</button>}</aside><main className="portal-main">
      {section==='catalog'&&<><section className="hero-card"><div><span className="eyebrow">تجارة جملة أسرع</span><h2>احتياج متجرك، في طلب واحد.</h2><p>ابحث بالاسم أو SKU أو الباركود، راجع شرائح السعر، ثم اعتمد الكميات وأرسل الطلب.</p></div><div className="hero-stat"><strong>{products.length}</strong><span>صنف متاح</span></div></section>
      {config.showSearch&&<section className="search-panel" aria-label="بحث وأدوات الكتالوج"><div className="search-field-wrap"><span aria-hidden="true">⌕</span><input id="aghbari-catalog-search" ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الصنف، SKU أو الباركود…" aria-label="البحث في الكتالوج"/>{query.trim()&&<button className="search-clear" type="button" onClick={()=>{setQuery('');setCategoryId(null);requestAnimationFrame(()=>searchRef.current?.focus());}} aria-label="مسح البحث">×</button>}</div><div className="search-actions">{config.showVoiceSearch&&<button type="button" title="البحث الصوتي" aria-label="البحث الصوتي">🎙</button>}{config.showImageSearch&&<button type="button" title="البحث بالصور" aria-label="البحث بالصور">⌕</button>}{config.showExcel&&<label className="file-button">رفع Excel<input id="aghbari-excel-input" type="file" accept=".xlsx" disabled={excelBusy} onChange={async e=>{const f=e.target.files?.[0];if(f)await stageQuickExcel(f);e.currentTarget.value='';}}/></label>}{config.showQuickOrder&&<button type="button" onClick={()=>setQuickOpen(true)}>طلب سريع</button>}</div><div className="search-context" aria-live="polite"><span>{loading?'جاري البحث…':products.length+' صنف ظاهر'}</span>{query.trim()||categoryId?<button type="button" className="search-filter-clear" onClick={()=>{setQuery('');setCategoryId(null);}}>مسح التصفية</button>:null}</div></section>}
      {config.showCategories&&<div className="category-row">{categoriesView.map(c=><button key={c.id??'all'} className={categoryId===c.id?'active':''} onClick={()=>setCategoryId(c.id)}>{c.name}</button>)}</div>}
      {loading?<div className="product-loading-grid" aria-label="تحميل الكتالوج" aria-busy="true">{Array.from({length:6},(_,index)=><div className="product-skeleton" key={index}><span/><div><i/><i/><i/></div></div>)}</div>:<>{products.length>0?<div className="product-grid">{products.map(p=>{const q=cart.find(l=>l.product.id===p.id)?.quantity??0;const baseQty=Math.max(1,q);const price=effectivePrice(p,baseQty);const next=nextTier(p,baseQty);return <article className="product-card" key={p.id} data-barcode={p.barcode ?? ""}>{p.imageUrl?<img src={p.imageUrl} alt={p.name} loading="lazy"/>:<div className="product-placeholder">{p.name.slice(0,1)}</div>}<div className="product-body"><span className="sku">{p.sku}</span><h3>{p.name}</h3><small>{p.category} · {p.unit}</small><button type="button" className="product-details-link" onClick={()=>setSelectedProduct(p)}>عرض التفاصيل</button>{config.showInventory&&<span className="stock">{p.availableQuantity>0?`متاح ${p.availableQuantity} ${p.unit}`:'غير متوفر'}</span>}{price>0?<div className="price-row"><strong>{money(price)}</strong>{config.showRetailPrice&&<small>سعر التجزئة متاح حسب الصلاحية</small>}</div>:<div className="price-hidden">السعر حسب حسابك</div>}{config.showTieredPricing&&(tiers[p.id]??[]).length>1&&<div className="tiers">{(tiers[p.id]??[]).map(t=><span key={t.min_quantity}>من {t.min_quantity}: {money(t.unit_price,t.currency)}</span>)}</div>}{config.showSavingsCalculator&&next&&<div className="saving">أضف {next.min_quantity-baseQty} {p.unit} للوصول إلى {money(next.unit_price,next.currency)}</div>}{q>0?<div className="product-qty-control" aria-label={`كمية ${p.name}`}><button type="button" onClick={()=>void update(p.id,q-1)} aria-label={`إنقاص ${p.name}`}>−</button><output>{q}</output><button type="button" onClick={()=>void update(p.id,q+1)} disabled={q>=p.availableQuantity} aria-label={`زيادة ${p.name}`}>+</button></div>:<button className="add-button" disabled={p.availableQuantity<1||price<=0} onClick={()=>void add(p)}>إضافة للسلة</button>}</div></article>})}</div>:<section className="content-card" aria-live="polite"><div className="empty-state"><strong>لا توجد أصناف مطابقة.</strong><p>جرّب تغيير كلمة البحث أو التصنيف، ثم أعد المحاولة.</p>{(query.trim()||categoryId)&&<button type="button" className="checkout" onClick={()=>{setQuery('');setCategoryId(null);}}>مسح البحث والتصنيف</button>}</div></section>}{catalogHasMore&&products.length>0&&<div className="catalog-load-more"><button type="button" onClick={()=>void loadMoreCatalog()} disabled={catalogLoadingMore}>{catalogLoadingMore?'جارٍ تحميل المزيد…':'تحميل المزيد'}</button><small>{products.length} صنف ظاهر</small></div>}</>}
      </>}
      {section==='orders'&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">التشغيل</span><h2>طلباتك وشحناتك</h2></div><span>{orders.length} طلب</span></div>{operationalLoading?<div className="portal-loading compact" aria-busy="true">جارٍ تحديث الطلبات…</div>:orders.length?<div className="orders-list">{orders.map(o=>{const currentIndex=CUSTOMER_ORDER_STEPS.indexOf(o.status as typeof CUSTOMER_ORDER_STEPS[number]);const cancelled=o.status==='cancelled';return <article className="order-card" key={o.id}><div className="order-head"><strong>طلب #{o.order_number}</strong><strong>{money(o.total,o.currency)}</strong></div><small>{new Intl.DateTimeFormat('ar-YE',{timeZone:'Asia/Aden',dateStyle:'medium',timeStyle:'short'}).format(new Date(o.created_at))}</small><div className={`order-status ${cancelled?'cancelled':''}`} role="status">{CUSTOMER_STATUS_LABELS[o.status]??o.status}</div>{cancelled?<div className="order-cancelled-note">تم إلغاء هذا الطلب تشغيليًا.</div>:<div className="order-progress" aria-label={`تقدم الطلب ${o.order_number}`}>{CUSTOMER_ORDER_STEPS.map((step,index)=><div key={step} className={index<=currentIndex?'done':''}><span>{index<currentIndex?'✓':index===currentIndex?'●':'○'}</span><small>{CUSTOMER_STATUS_LABELS[step]}</small></div>)}</div>}<button onClick={()=>void reorderOrder(o.id,o.order_number)}>إعادة الطلب من الحالة الحالية</button></article>})}</div>:<div className="empty-state">لا توجد طلبات سابقة بعد.</div>}</section>}
      {section==='templates'&&config.showTemplates&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">طلبات دورية</span><h2>المسحات الجاهزة</h2></div><span>{templates.length}/{config.maxTemplates}</span></div><div className="template-save"><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="اسم المسحة"/><button disabled={busy||!templateName.trim()||!cart.length} onClick={()=>void saveTemplate()}>حفظ السلة كمسحة</button></div><div className="template-grid">{templates.map(t=><article className="template-card" key={t.id}><strong>{t.name}</strong><small>{t.lines.length} أصناف · {t.branchLabel}</small><div><button onClick={()=>void applyTemplate(t)}>إعادة الطلب</button><button className="ghost" disabled={busy} onClick={()=>void removeTemplate(t.id)}>حذف</button></div></article>)}</div></section>}
      {section==='finance'&&config.showCredit&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">الثقة المالية</span><h2>المركز المالي</h2></div><button onClick={downloadStatement} disabled={!finance}>تنزيل الكشف</button></div>{operationalLoading?<div className="portal-loading compact" aria-busy="true">جارٍ تحديث المركز المالي…</div>:finance?<><div className="finance-grid"><div><small>الحد الائتماني</small><strong>{money(finance.creditLimit,finance.currency)}</strong></div><div><small>الرصيد المستحق</small><strong>{money(finance.outstanding,finance.currency)}</strong></div><div><small>المتاح للشراء</small><strong>{money(finance.available,finance.currency)}</strong></div></div><div className="ledger-table">{finance.entries.map(e=><div className="ledger-row" key={e.id}><span>{e.reference??'—'}</span><strong>{e.description}</strong><span>{e.debit?`مدين ${money(e.debit,finance.currency)}`:`دائن ${money(e.credit,finance.currency)}`}</span><span>{e.due_date??'—'}</span></div>)}</div></>:<div className="empty-state">لا توجد بيانات مركز مالي متاحة.</div>}</section>}
      {error&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
    </main></div>
    
    <nav className="portal-bottom-nav" aria-label="تنقل سريع"><button className={section==='catalog'?'active':''} aria-current={section==='catalog'?'page':undefined} onClick={()=>navigate('catalog')}>الكتالوج</button><button className={section==='orders'?'active':''} aria-current={section==='orders'?'page':undefined} onClick={()=>navigate('orders')}>الطلبات</button><button type="button" onClick={()=>setCartOpen(true)} aria-label="فتح السلة">السلة <b>{cartCount}</b></button><button type="button" onClick={()=>setCommandOpen(true)}>أوامر</button></nav>
    <CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} actions={commandActions} />
    {selectedProduct&&<div className="modal-backdrop" role="presentation" onClick={()=>setSelectedProduct(null)}><section className="modal product-detail-modal" role="dialog" aria-modal="true" aria-labelledby="product-detail-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">تفاصيل المنتج</span><h2 id="product-detail-title">{selectedProduct.name}</h2></div><button type="button" onClick={()=>setSelectedProduct(null)} aria-label="إغلاق تفاصيل المنتج">×</button></div><div className="product-detail-grid">{selectedProduct.imageUrl?<img src={selectedProduct.imageUrl} alt={selectedProduct.name} />:<div className="product-detail-placeholder">{selectedProduct.name.slice(0,1)}</div>}<div className="product-detail-copy"><div><span>SKU</span><strong>{selectedProduct.sku}</strong></div><div><span>الوحدة</span><strong>{selectedProduct.unit}</strong></div><div><span>التوفر</span><strong>{selectedProduct.availableQuantity>0?'متاح '+selectedProduct.availableQuantity+' '+selectedProduct.unit:'غير متوفر'}</strong></div><div><span>السعر</span><strong>{effectivePrice(selectedProduct,1)>0?money(effectivePrice(selectedProduct,1)):'السعر حسب حسابك'}</strong></div>{selectedProduct.description&&<p>{selectedProduct.description}</p>}{(tiers[selectedProduct.id]??[]).length>0&&<div className="product-detail-tiers">{(tiers[selectedProduct.id]??[]).map(tier=><span key={tier.min_quantity}>{'من '+tier.min_quantity+': '+money(tier.unit_price,tier.currency)}</span>)}</div>}<button className="checkout" type="button" disabled={selectedProduct.availableQuantity<1||effectivePrice(selectedProduct,1)<=0} onClick={()=>{void add(selectedProduct);setSelectedProduct(null);}}>إضافة للسلة</button></div></div></section></div>}

    {offlineCenterOpen&&<div className="modal-backdrop" role="presentation" onClick={()=>setOfflineCenterOpen(false)}><section className="modal recovery-center" role="dialog" aria-modal="true" aria-labelledby="recovery-center-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">Recovery Center</span><h2 id="recovery-center-title">مركز الاسترداد والمزامنة</h2></div><button type="button" aria-label="إغلاق مركز الاسترداد" onClick={()=>setOfflineCenterOpen(false)}>×</button></div><p>هذه العمليات تخص جلسة حسابك الحالية فقط. العمليات القابلة لإعادة المحاولة ستُعاد تلقائيًا عند توفر الاتصال، بينما العمليات النهائية تحتاج تدخلًا بدلًا من تكرارها بصمت.</p><div className="recovery-summary"><article><strong>{retryableOfflineCount}</strong><span>قابلة لإعادة المحاولة</span></article><article><strong>{terminalOfflineCount}</strong><span>نهائية وتحتاج مراجعة</span></article><article><strong>{offlineOps.length}</strong><span>إجمالي الطابور</span></article></div><div className="recovery-list">{offlineOps.map(operation=><div className="recovery-row" key={operation.operationId}><span className={operation.terminal?'terminal':'pending'}>{operation.terminal?'نهائية':'معلقة'}</span><div><strong>{operation.type==='cart:set_item'?'تحديث كمية السلة':'إزالة صنف من السلة'}</strong><small>{new Intl.DateTimeFormat('ar-YE',{timeZone:'Asia/Aden',dateStyle:'medium',timeStyle:'short'}).format(new Date(operation.createdAt))}</small></div><small>{operation.terminal?'استنفدت محاولات الاسترداد':operation.nextAttemptAt?`المحاولة التالية ${new Intl.DateTimeFormat('ar-YE',{timeZone:'Asia/Aden',timeStyle:'short'}).format(new Date(operation.nextAttemptAt))}`:'ستحاول عند توفر الاتصال'}</small></div>)}</div><div className="recovery-actions"><button type="button" disabled={!isOnline||syncingOffline} onClick={()=>{void flushOfflineCart();refreshOfflineState();}}>{syncingOffline?'جارٍ المزامنة…':'مزامنة الآن'}</button>{terminalOfflineCount>0&&<small>لن تُحذف العمليات النهائية تلقائيًا حتى تبقى قابلة للتشخيص.</small>}</div></section></div>}
    {quickOpen&&config.showQuickOrder&&<div className="modal-backdrop" role="presentation" onClick={()=>setQuickOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="quick-order-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2 id="quick-order-title">الطلب السريع</h2><button type="button" aria-label="إغلاق الطلب السريع" onClick={()=>setQuickOpen(false)}>×</button></div><p>أدخل SKU والكمية بسرعة.</p><QuickOrder products={products} warehouseId={warehouseId} onAdd={add}/></section></div>}
    {excelOpen&&<div className="modal-backdrop" role="presentation" onClick={()=>!excelBusy&&setExcelOpen(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="excel-review-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2 id="excel-review-title">مراجعة الطلب من Excel</h2><button type="button" aria-label="إغلاق مراجعة Excel" disabled={excelBusy} onClick={()=>setExcelOpen(false)}>×</button></div><p>تم تحليل الملف والتحقق من المعرفات والكميات والمخزون. لن تدخل البيانات السلة قبل اعتمادك.</p><div className="excel-review">{excelRows.map((row,index)=><div className="excel-row" key={`${row.identifier}-${index}`}><strong>{row.identifier||'—'}</strong><span>{row.quantity||'—'}</span><span>{row.product?.name??'غير مطابق'}</span><span className={row.error?'error-text':'ok-text'}>{row.error??'جاهز'}</span></div>)}</div><button className="checkout" disabled={excelBusy||excelRows.some(row=>Boolean(row.error)||!row.product)} onClick={()=>void confirmQuickExcel()}>{excelBusy?'جارٍ اعتماد الملف…':'اعتماد وإضافة إلى السلة'}</button></section></div>}
    {cartOpen&&<div className="drawer-backdrop" role="presentation" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" role="dialog" aria-modal="true" aria-labelledby="cart-drawer-title" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2 id="cart-drawer-title">السلة · {cartCount}</h2><button type="button" aria-label="إغلاق السلة" onClick={()=>setCartOpen(false)}>×</button></div>{cart.map(l=>{const next=nextTier(l.product,l.quantity);return <div className="drawer-line" key={l.product.id}><div><strong>{l.product.name}</strong><small>{money(l.unitPrice)} / {l.product.unit}</small>{config.showSavingsCalculator&&next&&<small className="saving">تبقى {next.min_quantity-l.quantity} للوصول للسعر التالي</small>}</div><div className="quantity"><button onClick={()=>void update(l.product.id,l.quantity-1)}>−</button><span>{l.quantity}</span><button onClick={()=>void update(l.product.id,l.quantity+1)}>+</button></div>{config.requireQuantityConfirmation&&<button className={confirmed[l.product.id]?'confirmed':'confirm'} onClick={()=>setQtyConfirmed(l.product.id,!confirmed[l.product.id])}>{confirmed[l.product.id]?'✓ معتمد':'اعتماد الكمية'}</button>}</div>})}<div className="drawer-total"><span>الإجمالي</span><strong>{money(total,cart[0]?.product.currency ?? 'YER')}</strong></div>{config.showPaymentMethods&&<div className="payment-box"><strong>طريقة الدفع</strong>{PAYMENT_OPTIONS.filter(x=>config[x.field]).map(x=><label key={x.key}><input type="radio" checked={payment===x.key} onChange={()=>setPayment(x.key)}/>{x.label}</label>)}</div>}{config.showTemplates&&<label className="template-inline"><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="حفظ كمسحة"/><button disabled={busy||!templateName.trim()} onClick={()=>void saveTemplate()}>حفظ</button></label>}<button className="checkout" disabled={busy||!cart.length} onClick={()=>void submit()}>{busy?'جارٍ إرسال الطلب…':'تأكيد وإرسال الطلب'}</button></aside></div>}
  </div>;
}

function QuickOrder({products,warehouseId,onAdd}:{products:Product[];warehouseId:string|null;onAdd:(p:Product,q?:number)=>Promise<void>}){const [sku,setSku]=useState('');const [qty,setQty]=useState('1');const [remoteFound,setRemoteFound]=useState<Product|null>(null);const [resolving,setResolving]=useState(false);const [searched,setSearched]=useState(false);const [lookupError,setLookupError]=useState('');const skuRef=useRef<HTMLInputElement>(null);const localFound=findProductByIdentifier(products, sku);const found=localFound??remoteFound;const numericQty=Number(qty);const validQty=Number.isSafeInteger(numericQty)&&numericQty>=1&&numericQty<=MAX_ORDER_QUANTITY_PER_LINE;useEffect(()=>{setRemoteFound(null);setSearched(false);setLookupError('');},[sku]);useEffect(()=>{requestAnimationFrame(()=>skuRef.current?.focus());},[]);async function resolveProduct(){if(localFound)return localFound;const identifier=sku.trim();if(!identifier)return null;setResolving(true);setSearched(false);setLookupError('');try{const items=await getCatalog(identifier,null,5,0,warehouseId??undefined);const mapped=items.map(item=>mapProduct(item,'أصناف'));const candidate=findProductByIdentifier(mapped,identifier);setRemoteFound(candidate);setSearched(true);return candidate;}catch(e){setSearched(true);setLookupError(e instanceof Error?e.message:'تعذر البحث عن الصنف.');return null;}finally{setResolving(false);}}async function commit(){if(!validQty)return;const product=found??await resolveProduct();if(!product){return;}if(product.status!=='active'||numericQty>product.availableQuantity){setSearched(true);return;}await onAdd(product,numericQty);setSku('');setQty('1');setRemoteFound(null);setSearched(false);requestAnimationFrame(()=>skuRef.current?.focus());}return <div className="quick-editor"><input ref={skuRef} value={sku} onChange={e=>setSku(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void commit();}}} placeholder="SKU / الباركود" aria-label="SKU / الباركود" autoComplete="off" inputMode="search"/><input value={qty} onChange={e=>setQty(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void commit();}}} type="number" min="1" max={MAX_ORDER_QUANTITY_PER_LINE} placeholder="الكمية" aria-label="كمية الطلب"/><button disabled={resolving||!sku.trim()||!validQty} onClick={()=>void commit()}>{resolving?'جارٍ البحث…':'إضافة'}</button>{sku.trim()&&(found?<div className="quick-result">{found.name} · متاح {found.availableQuantity} {found.unit}{numericQty>found.availableQuantity?' · الكمية تتجاوز المتاح':''}</div>:lookupError?<div className="quick-result quick-not-found">{lookupError}</div>:searched?<div className="quick-result quick-not-found">لم يتم العثور على SKU / الباركود ضمن الأصناف المصرح بها.</div>:<div className="quick-result">سيبحث الأغبري في الكتالوج الكامل عند الإضافة.</div>)}</div>}
