import { useEffect, useMemo, useState } from 'react';
import { getCategories, type CategoryOption } from './services/categories';
import './category-management.css';

type UserRole='owner'|'admin'|'sales'|'warehouse'|'viewer';

export default function CategoryManagementPanel({role}:{role:UserRole}){
  const canView=['owner','admin','sales'].includes(role);
  const [categories,setCategories]=useState<CategoryOption[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  async function reload(){setLoading(true);setError(null);try{setCategories(await getCategories());}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل التصنيفات.');}finally{setLoading(false);}}
  useEffect(()=>{void reload();},[]);
  const rows=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();const map=new Map(categories.map(item=>[item.id,item]));const children=new Map<string|null,CategoryOption[]>();for(const item of categories){const key=item.parent_id&&map.has(item.parent_id)?item.parent_id:null;const bucket=children.get(key)??[];bucket.push(item);children.set(key,bucket);}const result:Array<{item:CategoryOption;level:number;children:number}>=[],seen=new Set<string>();const walk=(parent:string|null,level:number)=>{for(const item of [...(children.get(parent)??[])].sort((a,b)=>a.name.localeCompare(b.name,'ar'))){const direct=children.get(item.id)?.length??0;if(!needle||item.name.toLocaleLowerCase().includes(needle))result.push({item,level,children:direct});seen.add(item.id);walk(item.id,level+1);}};walk(null,0);for(const item of categories)if(!seen.has(item.id)&&(!needle||item.name.toLocaleLowerCase().includes(needle)))result.push({item,level:0,children:children.get(item.id)?.length??0});return result;},[categories,query]);
  if(!canView)return null; const roots=categories.filter(c=>!c.parent_id).length;
  return <section className='cart-panel category-management' id='admin-categories'><div className='section-heading'><div><span className='eyebrow'>Catalog taxonomy</span><h2>دليل التصنيفات</h2><p className='panel-note'>عرض هرمي فعلي للكتالوج مع بحث سريع وحالات التحميل والخطأ والفراغ.</p></div><span>{categories.length} تصنيف · {roots} رئيسي</span></div>
    <div className='category-toolbar'><input aria-label='بحث التصنيفات' value={query} onChange={e=>setQuery(e.target.value)} placeholder='ابحث باسم التصنيف'/><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button><button type='button' className='ghost' onClick={()=>setQuery('')} disabled={!query}>مسح</button></div>
    {loading?<div className='portal-loading' role='status'>جارٍ تحميل التصنيفات…</div>:error?<div className='empty-state'><strong>تعذر تحميل دليل التصنيفات.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!rows.length?<div className='empty-state'><strong>{categories.length?'لا توجد نتائج مطابقة.':'لا توجد تصنيفات نشطة بعد.'}</strong><span>{categories.length?'غيّر عبارة البحث.':'أنشئ أول تصنيف من بطاقة التصنيف الجديدة أعلاه.'}</span>{query&&<button type='button' onClick={()=>setQuery('')}>مسح البحث</button>}</div>:<div className='category-tree' role='tree' aria-label='شجرة التصنيفات'><div className='category-tree-head'><span>التصنيف</span><span>النوع</span><span>التصنيف الأب</span><span>الفروع</span></div>{rows.map(({item,level,children})=><article className='category-tree-row' role='treeitem' aria-level={level+1} key={item.id}><div style={{paddingInlineStart:level*22}}><span className='tree-marker'>{level?'↳':'◆'}</span><strong>{item.name}</strong></div><span>{level?'فرعي':'رئيسي'}</span><span>{item.parent_id?categories.find(p=>p.id===item.parent_id)?.name??'غير معروف':'—'}</span><span>{children}</span></article>)}</div>}
  </section>;
}