import { useEffect, useMemo, useRef, useState } from 'react';
import type { Product } from './domain/types';
type Command={id:string;label:string;hint:string;section?:'home'|'catalog'|'orders'|'finance'|'templates'|'account'|'notifications';action?:()=>void};
export default function CustomerCommandPalette({products,visibleSections,onNavigate,onOpenCart,onOpenProduct,onOpenQuickOrder,onOpenPricing,onReorderLatest}:{products:Product[];visibleSections:readonly string[];onNavigate:(section:'home'|'catalog'|'orders'|'finance'|'templates'|'account'|'notifications')=>void;onOpenCart:()=>void;onOpenProduct:(product:Product)=>void;onOpenQuickOrder:()=>void;onOpenPricing:()=>void;onReorderLatest:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0);const inputRef=useRef<HTMLInputElement>(null);
 const commands=useMemo<Command[]>(()=>{const nav:Command[]=[{id:'home',label:'الرئيسية',hint:'ملخص الحساب والشراء السريع',section:'home'},{id:'catalog',label:'الكتالوج',hint:'البحث والشراء والمخزون',section:'catalog'},{id:'orders',label:'الطلبات والتتبع',hint:'السجل والحالات وإعادة الطلب',section:'orders'},...(visibleSections.includes('finance')?[{id:'finance',label:'المركز المالي',hint:'الفواتير والمدفوعات والكشف',section:'finance' as const}]:[]),...(visibleSections.includes('templates')?[{id:'templates',label:'القوالب المحفوظة',hint:'طلباتك المتكررة وإعادة التطبيق',section:'templates' as const}]:[]),{id:'account',label:'الحساب والشركة',hint:'الهوية والعناوين والإعدادات',section:'account'},{id:'notifications',label:'الإشعارات',hint:'التنبيهات المرتبطة بالحساب',section:'notifications'}];return [...nav,{id:'cart',label:'فتح السلة',hint:'راجع الكميات ثم انتقل إلى الاعتماد',action:onOpenCart},{id:'quick-order',label:'طلب سريع',hint:'إدخال SKU/باركود وكمية مباشرة',action:onOpenQuickOrder},{id:'pricing',label:'قائمة الأسعار',hint:'الأسعار والشرائح المصرح بها',action:onOpenPricing},{id:'repeat-last',label:'إعادة آخر طلب',hint:'إعادة المتاح من آخر طلب إلى السلة',action:onReorderLatest}];},[onOpenCart,onOpenPricing,onOpenQuickOrder,onReorderLatest,visibleSections]);
 const productMatches=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();if(needle.length<2)return [];return products.filter(p=>p.name.toLocaleLowerCase().includes(needle)||p.sku.toLocaleLowerCase().includes(needle)||p.category.toLocaleLowerCase().includes(needle)).slice(0,6);},[products,query]);
 const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();if(!needle)return commands;return commands.filter(c=>(c.label+' '+c.hint).toLocaleLowerCase().includes(needle));},[commands,query]);
 const totalItems=filtered.length+productMatches.length;
 useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{const hotkey=(event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k';if(hotkey){event.preventDefault();setOpen(true);setQuery('');setActive(0);return;}if(!open)return;if(event.key==='Escape'){event.preventDefault();setOpen(false);}else if(event.key==='ArrowDown'){event.preventDefault();setActive(v=>Math.min(Math.max(totalItems-1,0),v+1));}else if(event.key==='ArrowUp'){event.preventDefault();setActive(v=>Math.max(0,v-1));}else if(event.key==='Enter'){event.preventDefault();if(active<filtered.length){const item=filtered[active];if(item.section)onNavigate(item.section);else item.action?.();setOpen(false);}else{const product=productMatches[active-filtered.length];if(product){onOpenProduct(product);setOpen(false);}}}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[active,filtered,onNavigate,onOpenProduct,open,productMatches,totalItems]);
 useEffect(()=>{if(open)window.setTimeout(()=>inputRef.current?.focus(),0);},[open]);
 if(!open)return <button type="button" className="customer-command-trigger" onClick={()=>{setOpen(true);setQuery('');setActive(0);}} aria-label="فتح مركز الأوامر"><span aria-hidden="true">⌘K</span><strong>مركز الأوامر</strong><small>بحث وتنقل سريع</small></button>;
 return <><button type="button" className="customer-command-scrim" aria-label="إغلاق مركز الأوامر" onClick={()=>setOpen(false)}/><section className="customer-command-palette" role="dialog" aria-modal="true" aria-labelledby="customer-command-title"><div className="customer-command-head"><div><span className="eyebrow">COMMAND CENTER</span><strong id="customer-command-title">إلى أين تريد الذهاب؟</strong><small>اختصار Ctrl/⌘ + K في أي وقت · أسهم للتنقل · Enter للاختيار</small></div><button type="button" className="ghost" onClick={()=>setOpen(false)}>إغلاق</button></div><label className="customer-command-search"><span aria-hidden="true">⌕</span><input ref={inputRef} value={query} onChange={e=>{setQuery(e.target.value);setActive(0);}} placeholder="ابحث عن شاشة، إجراء، SKU أو صنف…" aria-label="بحث مركز الأوامر"/><kbd>ESC</kbd></label><div className="customer-command-results" role="listbox" aria-label="نتائج مركز الأوامر">{filtered.length>0&&<div className="customer-command-group"><span>المسارات والإجراءات</span>{filtered.map((c,i)=><button type="button" role="option" aria-selected={active===i} className={active===i?'is-active':''} key={c.id} onMouseEnter={()=>setActive(i)} onClick={()=>{if(c.section)onNavigate(c.section);else c.action?.();setOpen(false);}}><i aria-hidden="true">{c.section?'↗':'⚡'}</i><div><strong>{c.label}</strong><small>{c.hint}</small></div><b>{c.section?'قسم':'إجراء'}</b></button>)}</div>}{productMatches.length>0&&<div className="customer-command-group"><span>أصناف من الكتالوج</span>{productMatches.map((p,i)=>{const n=filtered.length+i;return <button type="button" role="option" aria-selected={active===n} className={active===n?'is-active':''} key={p.id} onMouseEnter={()=>setActive(n)} onClick={()=>{onOpenProduct(p);setOpen(false);}}><i className="product-search-thumb" aria-hidden="true">{p.imageUrl?<img src={p.imageUrl} alt=""/>:p.name.slice(0,1)}</i><div><strong>{p.name}</strong><small>{p.sku} · {p.category} · {p.availableQuantity>0?'متوفر':'غير متوفر'}</small></div><b>صنف</b></button>})}</div>}{!filtered.length&&!productMatches.length&&<div className="customer-command-empty"><strong>لا توجد نتائج</strong><span>جرّب اسم الشاشة أو SKU أو اسم صنف مختلف.</span></div>}</div><footer className="customer-command-footer"><span>بحث محلي سريع ضمن البيانات المحملة للحساب.</span><span><kbd>↑</kbd><kbd>↓</kbd> للتنقل · <kbd>Enter</kbd> فتح · <kbd>Esc</kbd> إغلاق</span></footer></section></>;
}
