import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import './finance-history.css';
import RecordDetailDrawer from './RecordDetailDrawer';
import { getOperationalInvoiceDetail } from './services/finance';

type UserRole='owner'|'admin'|'sales';
type Tab='invoices'|'payments'|'expenses';
interface Invoice{id:string;invoice_number:number;order_id:string;status:string;total:number;currency:string;due_at:string|null;created_at:string;}
interface Payment{id:string;invoice_id:string;amount:number;method:string;reference:string|null;paid_at:string;}
interface Expense{id:string;branch_id:string;cash_account_id:string|null;category:string;amount:number;currency:string;description:string|null;expense_date:string;}

export default function FinanceOperationsHistoryPanel({role}:{role:UserRole}){
  const canUse=['owner','admin','sales'].includes(role);
  const [tab,setTab]=useState<Tab>('invoices');const [invoices,setInvoices]=useState<Invoice[]>([]);const [payments,setPayments]=useState<Payment[]>([]);const [expenses,setExpenses]=useState<Expense[]>([]);
  const [query,setQuery]=useState('');const [page,setPage]=useState(1);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null); const [selectedInvoice,setSelectedInvoice]=useState<Invoice|null>(null); const [selectedPayment,setSelectedPayment]=useState<Payment|null>(null); const [selectedExpense,setSelectedExpense]=useState<Expense|null>(null); const [invoiceDetail,setInvoiceDetail]=useState<Awaited<ReturnType<typeof getOperationalInvoiceDetail>>|null>(null); const [invoiceDetailBusy,setInvoiceDetailBusy]=useState(false);
  const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [i,p,e]=await Promise.all([supabase.from('operational_invoices').select('id,invoice_number,order_id,status,total,currency,due_at,created_at').order('created_at',{ascending:false}).limit(300),supabase.from('payments').select('id,invoice_id,amount,method,reference,paid_at').order('paid_at',{ascending:false}).limit(500),supabase.from('expenses').select('id,branch_id,cash_account_id,category,amount,currency,description,expense_date').order('expense_date',{ascending:false}).limit(300)]);if(i.error)throw i.error;if(p.error)throw p.error;if(e.error)throw e.error;setInvoices((i.data??[]) as Invoice[]);setPayments((p.data??[]) as Payment[]);setExpenses((e.data??[]) as Expense[]);}catch(err){setError(err instanceof Error?err.message:'تعذر تحميل السجل المالي.');}finally{setLoading(false);}},[canUse]);
  useEffect(()=>{void reload();},[reload]);
  async function openInvoiceDetail(id:string){setInvoiceDetailBusy(true);setError(null);try{setInvoiceDetail(await getOperationalInvoiceDetail(id));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل تفاصيل الفاتورة.');}finally{setInvoiceDetailBusy(false);}}useEffect(()=>{setPage(1);},[query,tab]);
  const current=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();if(tab==='invoices')return invoices.filter(x=>!needle||[x.invoice_number,x.order_id,x.status,x.total,x.currency].join(' ').toLocaleLowerCase().includes(needle));if(tab==='payments')return payments.filter(x=>!needle||[x.invoice_id,x.amount,x.method,x.reference??''].join(' ').toLocaleLowerCase().includes(needle));return expenses.filter(x=>!needle||[x.category,x.amount,x.currency,x.description??'',x.expense_date].join(' ').toLocaleLowerCase().includes(needle));},[expenses,invoices,payments,query,tab]);
  const pages=Math.max(1,Math.ceil(current.length/10));const activePage=Math.min(page,pages);const visible=current.slice((activePage-1)*10,activePage*10);
  if(!canUse)return null;
  return <section className='cart-panel' id='admin-finance-history'><div className='section-heading'><div><span className='eyebrow'>Finance Ledger</span><h2>سجل العمليات المالية</h2><p className='panel-note'>فواتير وتحصيلات ومصروفات تشغيلية مرتبطة بالسجلات الفعلية.</p></div><span>{current.length} سجل</span></div>
    <div className='history-tabs' role='tablist'><button type='button' role='tab' aria-selected={tab==='invoices'} className={tab==='invoices'?'active':''} onClick={()=>setTab('invoices')}>الفواتير ({invoices.length})</button><button type='button' role='tab' aria-selected={tab==='payments'} className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}>التحصيل ({payments.length})</button><button type='button' role='tab' aria-selected={tab==='expenses'} className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>المصروفات ({expenses.length})</button></div>
    <div className='order-queue-toolbar'><input aria-label='بحث السجل المالي' value={query} onChange={e=>setQuery(e.target.value)} placeholder='ابحث في السجل الحالي'/><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button><button type='button' className='ghost' onClick={()=>setQuery('')} disabled={!query}>مسح</button></div>
    {loading?<div className='portal-loading' role='status'>جارٍ تحميل السجل المالي…</div>:error?<div className='empty-state'><strong>تعذر تحميل السجل المالي.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!current.length?<div className='empty-state'><strong>{query?'لا توجد سجلات مطابقة.':'لا توجد سجلات مالية بعد.'}</strong><span>{query?'غيّر عبارة البحث.':'ستظهر العمليات هنا بعد الاستخدام الفعلي للمالية التشغيلية.'}</span></div>:<><div className='cart-lines'>{tab==='invoices'&&visible.map(x=><article className='cart-line' key={x.id}><div><strong>فاتورة #{x.invoice_number}</strong><small>طلب #{x.order_id.slice(0,8)} · {x.status}</small></div><div><strong>{x.total} {x.currency}</strong><small>{x.due_at?'استحقاق '+x.due_at.slice(0,10):'بدون استحقاق'}</small></div><time>{x.created_at.slice(0,10)}</time><button type='button' className='ghost' onClick={()=>void openInvoiceDetail(x.id)} disabled={invoiceDetailBusy}>التفاصيل</button></article>)}{tab==='payments'&&visible.map(x=><article className='cart-line' key={x.id}><div><strong>تحصيل {x.amount}</strong><small>فاتورة #{x.invoice_id.slice(0,8)}</small></div><div><strong>{x.method}</strong><small>{x.reference??'بدون مرجع'}</small></div><time>{x.paid_at.slice(0,10)}</time><button type='button' className='ghost' onClick={()=>setSelectedPayment(x)}>التفاصيل</button></article>)}{tab==='expenses'&&visible.map(x=><article className='cart-line' key={x.id}><div><strong>{x.category}</strong><small>{x.description??'بدون وصف'}</small></div><div><strong>{x.amount} {x.currency}</strong><small>حساب نقدية {x.cash_account_id?x.cash_account_id.slice(0,8):'—'}</small></div><time>{x.expense_date}</time><button type='button' className='ghost' onClick={()=>setSelectedExpense(x)}>التفاصيل</button></article>)}</div><div className='directory-pagination'><span>صفحة {activePage} / {pages}</span><div><button type='button' className='ghost' onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={activePage===1}>السابق</button><button type='button' className='ghost' onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={activePage===pages}>التالي</button></div></div></>}
  {invoiceDetail&&<RecordDetailDrawer eyebrow='Finance Ledger' title={`فاتورة #${invoiceDetail.invoice_number}`} summary={`${invoiceDetail.total} ${invoiceDetail.currency} · ${invoiceDetail.status}`} fields={[
    {label:'رقم الطلب',value:invoiceDetail.order_id},
    {label:'الإجمالي',value:`${invoiceDetail.total.toLocaleString('ar-YE')} ${invoiceDetail.currency}`},
    {label:'المحصّل',value:`${invoiceDetail.paid_total.toLocaleString('ar-YE')} ${invoiceDetail.currency}`},
    {label:'المتبقي',value:`${invoiceDetail.balance_due.toLocaleString('ar-YE')} ${invoiceDetail.currency}`},
    {label:'الحالة',value:invoiceDetail.status},
    {label:'تاريخ الإنشاء',value:new Date(invoiceDetail.created_at).toLocaleString('ar-YE')},
    {label:'الاستحقاق',value:invoiceDetail.due_at?new Date(invoiceDetail.due_at).toLocaleString('ar-YE'):'غير محدد'},
    {label:'المعرّف',value:invoiceDetail.id},
    {label:'بنود الفاتورة',wide:true,value:<div className='record-detail-lines'>{invoiceDetail.items.length?invoiceDetail.items.map(item=><div key={item.id}><span>{item.description}</span><strong>{item.quantity} × {item.unit_price.toLocaleString('ar-YE')} · {item.line_total.toLocaleString('ar-YE')} {invoiceDetail.currency}</strong></div>):'لا توجد بنود مرتبطة بالفاتورة.'}</div>},
    {label:'سجل التحصيلات',wide:true,value:<div className='record-detail-lines'>{invoiceDetail.payments.length?invoiceDetail.payments.map(payment=><div key={payment.id}><span>{payment.method} · {payment.reference??'بدون مرجع'}</span><strong>{payment.amount.toLocaleString('ar-YE')} {invoiceDetail.currency} · {new Date(payment.paid_at).toLocaleString('ar-YE')}</strong></div>):'لا توجد تحصيلات مسجلة.'}</div>}
  ]} onClose={()=>setInvoiceDetail(null)}/>}
  {selectedPayment&&<RecordDetailDrawer eyebrow='Finance Ledger' title='تفاصيل التحصيل' summary={`${selectedPayment.amount} · ${selectedPayment.method}`} fields={[{label:'الفاتورة',value:selectedPayment.invoice_id},{label:'المبلغ',value:String(selectedPayment.amount)},{label:'الطريقة',value:selectedPayment.method},{label:'المرجع',value:selectedPayment.reference??'بدون مرجع'},{label:'تاريخ التحصيل',value:new Date(selectedPayment.paid_at).toLocaleString('ar-YE')},{label:'المعرّف',value:selectedPayment.id}]} onClose={()=>setSelectedPayment(null)}/>}
  {selectedExpense&&<RecordDetailDrawer eyebrow='Finance Ledger' title={selectedExpense.category} summary={`${selectedExpense.amount} ${selectedExpense.currency}`} fields={[{label:'الحساب النقدي',value:selectedExpense.cash_account_id??'—'},{label:'الفرع',value:selectedExpense.branch_id},{label:'المبلغ',value:`${selectedExpense.amount} ${selectedExpense.currency}`},{label:'التاريخ',value:selectedExpense.expense_date},{label:'الوصف',value:selectedExpense.description??'بدون وصف',wide:true},{label:'المعرّف',value:selectedExpense.id}]} onClose={()=>setSelectedExpense(null)}/>}
  </section>;
}