import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import './finance-history.css';
import RecordDetailDrawer from './RecordDetailDrawer';

type UserRole='owner'|'admin'|'warehouse';
type Tab='transfers'|'counts'|'reconciliations';
interface Transfer{id:string;source_warehouse_id:string;destination_warehouse_id:string;status:string;notes:string|null;created_at:string;}
interface Count{id:string;warehouse_id:string;status:string;started_at:string;completed_at:string|null;notes:string|null;}
interface Reconciliation{id:string;warehouse_id:string;status:string;source_name:string;source_fingerprint:string;summary:Record<string,unknown>|null;conflicts:unknown[]|null;applied_at:string|null;rolled_back_at:string|null;created_at:string;}

export default function InventoryActivityPanel({role}:{role:UserRole}){
 const canUse=['owner','admin','warehouse'].includes(role); const [tab,setTab]=useState<Tab>('transfers'); const [transfers,setTransfers]=useState<Transfer[]>([]); const [counts,setCounts]=useState<Count[]>([]); const [reconciliations,setReconciliations]=useState<Reconciliation[]>([]); const [warehouses,setWarehouses]=useState<Map<string,string>>(new Map()); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selectedTransfer,setSelectedTransfer]=useState<Transfer|null>(null); const [selectedCount,setSelectedCount]=useState<Count|null>(null); const [selectedReconciliation,setSelectedReconciliation]=useState<Reconciliation|null>(null);
 const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [t,c,r,w]=await Promise.all([supabase.from('inventory_transfers').select('id,source_warehouse_id,destination_warehouse_id,status,notes,created_at').order('created_at',{ascending:false}).limit(300),supabase.from('stock_count_sessions').select('id,warehouse_id,status,started_at,completed_at,notes').order('started_at',{ascending:false}).limit(300),supabase.from('inventory_reconciliations').select('id,warehouse_id,status,source_name,source_fingerprint,summary,conflicts,applied_at,rolled_back_at,created_at').order('created_at',{ascending:false}).limit(300),supabase.from('warehouses').select('id,name').eq('is_active',true)]);if(t.error)throw t.error;if(c.error)throw c.error;if(r.error)throw r.error;if(w.error)throw w.error;setTransfers((t.data??[]) as Transfer[]);setCounts((c.data??[]) as Count[]);setReconciliations((r.data??[]) as Reconciliation[]);setWarehouses(new Map((w.data??[]).map(x=>[x.id,x.name])));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل نشاط المخزون.');}finally{setLoading(false);}},[canUse]);
 useEffect(()=>{void reload();},[reload]); useEffect(()=>{setQuery('');},[tab]);
 const current=useMemo(()=>{const n=query.trim().toLocaleLowerCase();if(tab==='transfers')return transfers.filter(x=>!n||[warehouses.get(x.source_warehouse_id)??'',warehouses.get(x.destination_warehouse_id)??'',x.status,x.notes??''].join(' ').toLocaleLowerCase().includes(n));if(tab==='counts')return counts.filter(x=>!n||[warehouses.get(x.warehouse_id)??'',x.status,x.notes??''].join(' ').toLocaleLowerCase().includes(n));return reconciliations.filter(x=>!n||[warehouses.get(x.warehouse_id)??'',x.status,x.source_name,x.source_fingerprint].join(' ').toLocaleLowerCase().includes(n));},[counts,reconciliations,query,tab,transfers,warehouses]);
 if(!canUse)return null;
 return <section className='cart-panel' id='admin-inventory-activity'><div className='section-heading'><div><span className='eyebrow'>Inventory Operations</span><h2>نشاط المخزون المتقدم</h2><p className='panel-note'>التحويلات والجرد والتسويات من السجلات التشغيلية الحالية.</p></div><span>{current.length} سجل</span></div>
 <div className='history-tabs' role='tablist'><button type='button' role='tab' aria-selected={tab==='transfers'} className={tab==='transfers'?'active':''} onClick={()=>setTab('transfers')}>التحويلات ({transfers.length})</button><button type='button' role='tab' aria-selected={tab==='counts'} className={tab==='counts'?'active':''} onClick={()=>setTab('counts')}>الجرد ({counts.length})</button><button type='button' role='tab' aria-selected={tab==='reconciliations'} className={tab==='reconciliations'?'active':''} onClick={()=>setTab('reconciliations')}>التسويات ({reconciliations.length})</button></div>
 <div className='order-queue-toolbar'><input aria-label='بحث نشاط المخزون' value={query} onChange={e=>setQuery(e.target.value)} placeholder='بحث في القسم الحالي'/><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button><button type='button' className='ghost' onClick={()=>setQuery('')} disabled={!query}>مسح</button></div>
 {loading?<div className='portal-loading' role='status'>جارٍ تحميل نشاط المخزون…</div>:error?<div className='empty-state'><strong>تعذر تحميل نشاط المخزون.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!current.length?<div className='empty-state'><strong>{query?'لا توجد نتائج مطابقة.':'لا توجد سجلات في هذا القسم بعد.'}</strong><span>{query?'غيّر عبارة البحث.':'ستظهر العمليات هنا بعد استخدام المخزون.'}</span></div>:<div className='cart-lines'>{tab==='transfers'&&current.map(x=><article className='cart-line' key={x.id}><div><strong>{warehouses.get(x.source_warehouse_id)??'مصدر'}</strong><small>إلى {warehouses.get(x.destination_warehouse_id)??'وجهة'}</small></div><div><strong>{x.status}</strong><small>{x.created_at.slice(0,10)}</small></div><span>{x.notes??'بدون ملاحظات'}</span><button type='button' className='ghost' onClick={()=>setSelectedTransfer(x)}>التفاصيل</button></article>)}{tab==='counts'&&current.map(x=><article className='cart-line' key={x.id}><div><strong>{warehouses.get(x.warehouse_id)??'مستودع'}</strong><small>{x.status}</small></div><div><strong>{x.started_at.slice(0,16).replace('T',' ')}</strong><small>{x.completed_at?'اكتمل '+x.completed_at.slice(0,10):'مفتوح'}</small></div><span>{x.notes??'بدون ملاحظات'}</span><button type='button' className='ghost' onClick={()=>setSelectedCount(x)}>التفاصيل</button></article>)}{tab==='reconciliations'&&current.map(x=>{const s=x.summary??{};const conflicts=Array.isArray(x.conflicts)?x.conflicts.length:0;return <article className='cart-line' key={x.id}><div><strong>{x.source_name}</strong><small>{warehouses.get(x.warehouse_id)??'مستودع'} · {x.status}</small></div><div><strong>{typeof s['rows']!=='undefined'?String(s['rows']):'—'} صفوف</strong><small>تعارضات {conflicts}</small></div><span>{x.applied_at?'مطبق '+x.applied_at.slice(0,10):x.rolled_back_at?'متراجع '+x.rolled_back_at.slice(0,10):'غير مطبق'}</span><button type='button' className='ghost' onClick={()=>setSelectedReconciliation(x)}>التفاصيل</button></article>})}</div>
 {selectedTransfer&&<RecordDetailDrawer eyebrow='Inventory Operations' title='تفاصيل تحويل المخزون' fields={[{label:'من المستودع',value:warehouses.get(selectedTransfer.source_warehouse_id)??'—'},{label:'إلى المستودع',value:warehouses.get(selectedTransfer.destination_warehouse_id)??'—'},{label:'الحالة',value:selectedTransfer.status},{label:'تاريخ الإنشاء',value:new Date(selectedTransfer.created_at).toLocaleString('ar-YE')},{label:'المعرف',value:selectedTransfer.id},{label:'الملاحظات',value:selectedTransfer.notes??'بدون ملاحظات',wide:true}]} onClose={()=>setSelectedTransfer(null)}/>} {selectedCount&&<RecordDetailDrawer eyebrow='Inventory Operations' title='تفاصيل جلسة الجرد' fields={[{label:'المستودع',value:warehouses.get(selectedCount.warehouse_id)??'—'},{label:'الحالة',value:selectedCount.status},{label:'بدأ',value:new Date(selectedCount.started_at).toLocaleString('ar-YE')},{label:'اكتمل',value:selectedCount.completed_at?new Date(selectedCount.completed_at).toLocaleString('ar-YE'):'ما زال مفتوحًا'},{label:'المعرف',value:selectedCount.id},{label:'الملاحظات',value:selectedCount.notes??'بدون ملاحظات',wide:true}]} onClose={()=>setSelectedCount(null)}/>} {selectedReconciliation&&<RecordDetailDrawer eyebrow='Inventory Operations' title={selectedReconciliation.source_name} summary={selectedReconciliation.status} fields={[{label:'المستودع',value:warehouses.get(selectedReconciliation.warehouse_id)??'—'},{label:'الحالة',value:selectedReconciliation.status},{label:'بصمة المصدر',value:selectedReconciliation.source_fingerprint},{label:'عدد التعارضات',value:Array.isArray(selectedReconciliation.conflicts)?selectedReconciliation.conflicts.length:0},{label:'التطبيق',value:selectedReconciliation.applied_at?new Date(selectedReconciliation.applied_at).toLocaleString('ar-YE'):'غير مطبق'},{label:'التراجع',value:selectedReconciliation.rolled_back_at?new Date(selectedReconciliation.rolled_back_at).toLocaleString('ar-YE'):'—'},{label:'الملخص',value:selectedReconciliation.summary?JSON.stringify(selectedReconciliation.summary):'—',wide:true}]} onClose={()=>setSelectedReconciliation(null)}/>}  </section>;
}