import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import './inventory-history.css';

type UserRole='owner'|'admin'|'warehouse';
interface Movement{id:string;warehouse_id:string;product_id:string;delta:number;source_type:string;source_id:string|null;created_at:string;}

export default function InventoryHistoryPanel({role}:{role:UserRole}){
  const canUse=['owner','admin','warehouse'].includes(role);
  const [rows,setRows]=useState<Movement[]>([]); const [products,setProducts]=useState<Map<string,string>>(new Map()); const [warehouses,setWarehouses]=useState<Map<string,string>>(new Map());
  const [query,setQuery]=useState(''); const [sourceType,setSourceType]=useState('all'); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [m,p,w]=await Promise.all([supabase.from('inventory_movements').select('id,warehouse_id,product_id,delta,source_type,source_id,created_at').order('created_at',{ascending:false}).limit(500),supabase.from('products').select('id,name,sku').eq('status','active').limit(500),supabase.from('warehouses').select('id,name').eq('is_active',true)]);if(m.error)throw m.error;if(p.error)throw p.error;if(w.error)throw w.error;setRows((m.data??[]) as Movement[]);setProducts(new Map((p.data??[]).map(x=>[x.id,x.name+' · '+x.sku])));setWarehouses(new Map((w.data??[]).map(x=>[x.id,x.name])));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل دفتر حركة المخزون.');}finally{setLoading(false);}},[canUse]);
  useEffect(()=>{void reload();},[reload]);useEffect(()=>{setPage(1);},[query,sourceType]);
  const types=useMemo(()=>Array.from(new Set(rows.map(x=>x.source_type))),[rows]);
  const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return rows.filter(x=>(sourceType==='all'||x.source_type===sourceType)&&(!needle||[products.get(x.product_id)??'',warehouses.get(x.warehouse_id)??'',x.source_type,x.source_id??''].join(' ').toLocaleLowerCase().includes(needle)));},[products,query,rows,sourceType,warehouses]);
  const pages=Math.max(1,Math.ceil(filtered.length/12));const activePage=Math.min(page,pages);const visible=filtered.slice((activePage-1)*12,activePage*12);
  if(!canUse)return null;
  return <section className='cart-panel inventory-history' id='admin-inventory-history'><div className='section-heading'><div><span className='eyebrow'>Inventory Ledger</span><h2>دفتر حركة المخزون</h2><p className='panel-note'>سجل الحركات التشغيلية الفعلية مع نوع العملية والمرجع والزمن.</p></div><span>{filtered.length}/{rows.length} حركة</span></div>
    <div className='order-queue-toolbar'><input aria-label='بحث حركات المخزون' value={query} onChange={e=>setQuery(e.target.value)} placeholder='الصنف أو المستودع أو نوع الحركة'/><select aria-label='نوع حركة المخزون' value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value='all'>كل الأنواع</option>{types.map(t=><option key={t} value={t}>{t}</option>)}</select><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button></div>
    {loading?<div className='portal-loading' role='status'>جارٍ تحميل دفتر المخزون…</div>:error?<div className='empty-state'><strong>تعذر تحميل دفتر حركة المخزون.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!filtered.length?<div className='empty-state'><strong>{rows.length?'لا توجد نتائج مطابقة.':'لا توجد حركات مخزون مسجلة بعد.'}</strong><span>{rows.length?'جرّب فلترًا أو عبارة بحث أخرى.':'ستظهر الحركة بعد البيع أو الاستلام أو التحويل أو التسوية.'}</span></div>:<><div className='history-table'><div className='history-row history-head'><span>الوقت</span><span>الصنف</span><span>المستودع</span><span>التغيير</span><span>المصدر</span></div>{visible.map(x=><div className='history-row' key={x.id}><time>{new Date(x.created_at).toLocaleString('ar-YE')}</time><strong>{products.get(x.product_id)??x.product_id}</strong><span>{warehouses.get(x.warehouse_id)??x.warehouse_id}</span><b className={x.delta<0?'negative':'positive'}>{x.delta>0?'+':''}{x.delta}</b><span>{x.source_type}{x.source_id?' · '+x.source_id.slice(0,8):''}</span></div>)}</div><div className='directory-pagination'><span>صفحة {activePage} / {pages}</span><div><button type='button' className='ghost' onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={activePage===1}>السابق</button><button type='button' className='ghost' onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={activePage===pages}>التالي</button></div></div></>}
  </section>;
}