import { useCallback,useEffect,useMemo,useState } from 'react';
import { getSession } from './services/auth';
import { supabase } from './lib/supabase';
import { canMarkNotificationRead,filterNotifications,type NotificationKind,type NotificationRow } from './domain/operations';
type Audience='customer'|'staff';
const KINDS:Array<{key:'all'|NotificationKind;label:string}>=[{key:'all',label:'الكل'},{key:'order',label:'طلبات'},{key:'inventory',label:'مخزون'},{key:'security',label:'أمان'},{key:'system',label:'نظام'},{key:'task',label:'مهام'}];
const KIND_LABELS:Record<NotificationKind,string>={order:'طلب',inventory:'مخزون',security:'أمان',system:'نظام',task:'مهمة'};
export default function NotificationPanel({audience}:{audience:Audience}){
 const [rows,setRows]=useState<NotificationRow[]>([]),[query,setQuery]=useState(''),[kind,setKind]=useState<'all'|NotificationKind>('all'),[unreadOnly,setUnreadOnly]=useState(false),[loading,setLoading]=useState(true),[busyId,setBusyId]=useState<string|null>(null),[actorId,setActorId]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 const reload=useCallback(async()=>{if(!supabase)throw new Error('خدمة البيانات غير متاحة.');const session=await getSession();const userId=session?.user.id??null;setActorId(userId);if(!userId)throw new Error('انتهت جلسة الحساب.');setLoading(true);setError(null);try{const {data,error:queryError}=await supabase.from('notifications').select('id,kind,title,body,entity_type,entity_id,read_at,recipient_user_id,customer_id,created_at').order('created_at',{ascending:false}).limit(80);if(queryError)throw queryError;setRows((data??[]) as NotificationRow[]);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الإشعارات.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void reload();},[reload]);
 const visible=useMemo(()=>filterNotifications(rows,query,kind,unreadOnly),[rows,query,kind,unreadOnly]);
 const unreadCount=rows.filter(row=>!row.read_at).length;
 async function markRead(row:NotificationRow){if(!supabase||!canMarkNotificationRead(row,audience,actorId))return;setBusyId(row.id);setError(null);const readAt=new Date().toISOString();try{const {error:updateError}=await supabase.from('notifications').update({read_at:readAt}).eq('id',row.id).is('read_at',null);if(updateError)throw updateError;setRows(current=>current.map(item=>item.id===row.id?{...item,read_at:readAt}:item));}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث حالة الإشعار.');}finally{setBusyId(null);}}
 return <section className="content-card operations-panel" aria-busy={loading}><div className="section-title"><div><span className="eyebrow">التنبيهات والتشغيل</span><h2>{audience==='staff'?'إشعارات مركز التشغيل':'إشعارات الحساب'}</h2></div><span>{unreadCount} غير مقروء</span></div><div className="operations-toolbar"><input aria-label="بحث الإشعارات" placeholder="بحث في العنوان أو المحتوى…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="نوع الإشعار" value={kind} onChange={e=>setKind(e.target.value as 'all'|NotificationKind)}>{KINDS.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select><label className="inline-toggle"><input type="checkbox" checked={unreadOnly} onChange={e=>setUnreadOnly(e.target.checked)}/> غير مقروء فقط</label><button type="button" className="ghost" onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button></div>{loading?<div className="portal-loading" role="status">جارٍ تحميل الإشعارات…</div>:error?<div className="empty-state"><strong>تعذر تحميل الإشعارات.</strong><span>{error}</span><button type="button" onClick={()=>void reload()}>إعادة المحاولة</button></div>:!visible.length?<div className="empty-state"><strong>لا توجد إشعارات مطابقة.</strong><span>{unreadOnly?'لا توجد إشعارات غير مقروءة ضمن المرشح الحالي.':'ستظهر هنا التنبيهات التشغيلية التي يحق للحساب الاطلاع عليها.'}</span></div>:<div className="notification-list">{visible.map(row=><article className={row.read_at?'notification-row read':'notification-row'} key={row.id}><div className="notification-icon" aria-hidden="true">{row.kind==='order'?'↗':row.kind==='inventory'?'▣':row.kind==='security'?'!':row.kind==='task'?'✓':'•'}</div><div className="notification-body"><div className="notification-head"><strong>{row.title}</strong><span>{KIND_LABELS[row.kind]}</span></div><p>{row.body}</p><small>{new Date(row.created_at).toLocaleString('ar-YE')}</small></div>{canMarkNotificationRead(row,audience,actorId)&&<button type="button" className="ghost notification-read" disabled={busyId===row.id} onClick={()=>void markRead(row)}>{busyId===row.id?'جارٍ التحديث…':'تحديد كمقروء'}</button>}{!row.read_at&&!canMarkNotificationRead(row,audience,actorId)&&<span className="notification-state">موجّه تشغيليًا</span>}</article>)}</div>}{error&&!loading&&<div className="error-banner" role="alert"><span>{error}</span><button type="button" className="ghost" onClick={()=>void reload()}>إعادة تحميل الإشعارات</button></div>}</section>;
}