import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import './pricing-matrix.css';

type UserRole='owner'|'admin'|'sales';
interface PriceList{id:string;tier:string;name:string;currency:string;is_active:boolean;}
interface Product{id:string;name:string;sku:string;unit:string;}
interface Price{id:string;price_list_id:string;product_id:string;amount:number;valid_from:string;valid_to:string|null;created_at:string;}

export default function PricingMatrixPanel({role}:{role:UserRole}){
 const canUse=['owner','admin','sales'].includes(role); const [lists,setLists]=useState<PriceList[]>([]); const [prices,setPrices]=useState<Price[]>([]); const [products,setProducts]=useState<Map<string,Product>>(new Map());
 const [query,setQuery]=useState(''); const [tier,setTier]=useState('all'); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [l,p,r]=await Promise.all([supabase.from('price_lists').select('id,tier,name,currency,is_active').order('name'),supabase.from('product_prices').select('id,price_list_id,product_id,amount,valid_from,valid_to,created_at').order('created_at',{ascending:false}).limit(1000),supabase.from('products').select('id,name,sku,unit').eq('status','active').limit(1000)]);if(l.error)throw l.error;if(p.error)throw p.error;if(r.error)throw r.error;setLists((l.data??[]) as PriceList[]);setPrices((p.data??[]) as Price[]);setProducts(new Map((r.data??[]).map(x=>[x.id,x as Product])));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل مصفوفة الأسعار.');}finally{setLoading(false);}},[canUse]);
 useEffect(()=>{void reload();},[reload]);useEffect(()=>{setPage(1);},[query,tier]);
 const tiers=useMemo(()=>Array.from(new Set(lists.map(x=>x.tier))),[lists]);
 const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return prices.filter(x=>{const list=lists.find(l=>l.id===x.price_list_id);const product=products.get(x.product_id);return (tier==='all'||list?.tier===tier)&&(!needle||[product?.name??'',product?.sku??'',list?.name??'',list?.tier??'',list?.currency??'',x.amount].join(' ').toLocaleLowerCase().includes(needle));});},[lists,prices,products,query,tier]);
 const pages=Math.max(1,Math.ceil(filtered.length/12));const activePage=Math.min(page,pages);const visible=filtered.slice((activePage-1)*12,activePage*12);
 if(!canUse)return null;
 return <section className='cart-panel' id='admin-pricing-matrix'><div className='section-heading'><div><span className='eyebrow'>Pricing Control</span><h2>مصفوفة الأسعار</h2><p className='panel-note'>قوائم الأسعار الفعلية حسب شريحة العميل والمنتج، مع صلاحية السعر والعملة.</p></div><span>{filtered.length}/{prices.length} سعر</span></div>
 <div className='order-queue-toolbar'><input aria-label='بحث مصفوفة الأسعار' value={query} onChange={e=>setQuery(e.target.value)} placeholder='اسم المنتج أو SKU أو قائمة السعر'/><select aria-label='فلترة شريحة السعر' value={tier} onChange={e=>setTier(e.target.value)}><option value='all'>كل الشرائح</option>{tiers.map(t=><option key={t} value={t}>{t}</option>)}</select><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button><button type='button' className='ghost' onClick={()=>{setQuery('');setTier('all')}} disabled={!query&&tier==='all'}>مسح</button></div>
 {loading?<div className='portal-loading' role='status'>جارٍ تحميل الأسعار…</div>:error?<div className='empty-state'><strong>تعذر تحميل مصفوفة الأسعار.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!filtered.length?<div className='empty-state'><strong>{prices.length?'لا توجد أسعار مطابقة.':'لا توجد أسعار منشورة بعد.'}</strong><span>{prices.length?'غيّر البحث أو الشريحة.':'أضف سعرًا من نموذج التسعير أعلاه.'}</span></div>:<><div className='history-table'><div className='history-row price-row-head'><span>المنتج</span><span>القائمة</span><span>السعر</span><span>الصلاحية</span><span>الحالة</span></div>{visible.map(x=>{const p=products.get(x.product_id);const l=lists.find(i=>i.id===x.price_list_id);const now=Date.now();const valid=!!l?.is_active&&new Date(x.valid_from).getTime()<=now&&(!x.valid_to||new Date(x.valid_to).getTime()>now);return <div className='history-row' key={x.id}><div><strong>{p?.name??'منتج'}</strong><small>{p?.sku??x.product_id.slice(0,8)} · {p?.unit??''}</small></div><span>{l?.name??'قائمة'} · {l?.tier??'—'}</span><strong>{x.amount} {l?.currency??''}</strong><span>{x.valid_to?'حتى '+x.valid_to.slice(0,10):'مفتوح'}</span><b className={valid?'positive':'negative'}>{valid?'ساري':'غير ساري'}</b></div>})}</div><div className='directory-pagination'><span>صفحة {activePage} / {pages}</span><div><button type='button' className='ghost' onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={activePage===1}>السابق</button><button type='button' className='ghost' onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={activePage===pages}>التالي</button></div></div></>}
 </section>;
}