import { useCallback, useEffect, useMemo, useState } from 'react';
import { completeStockCount, getOpenStockCount, getStockCountLines, setStockCountLine, startStockCount, type StockCountLine, type StockCountSession } from './services/inventory';
type Warehouse={id:string;name:string};

export default function StockCountWorkspace({warehouses}:{warehouses:Warehouse[]}){
 const [online,setOnline]=useState(()=>typeof navigator==='undefined'?true:navigator.onLine);
 const [session,setSession]=useState<StockCountSession|null>(null); const [selectedWarehouse,setSelectedWarehouse]=useState('');
 const [lines,setLines]=useState<StockCountLine[]>([]); const [dirty,setDirty]=useState<Set<string>>(()=>new Set()); const [query,setQuery]=useState(''); const [page,setPage]=useState(1);
 const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false); const [saving,setSaving]=useState<string|null>(null);
 const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);
 const reload=useCallback(async()=>{if(!online){setLoading(false);return;}setLoading(true);setError('');try{const next=await getOpenStockCount();setSession(next);setDirty(new Set());if(next){setSelectedWarehouse(next.warehouse_id);setLines(await getStockCountLines(next.id))}else{setLines([]);setSelectedWarehouse(v=>v||warehouses[0]?.id||'')}}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل جلسة الجرد.')}finally{setLoading(false)}},[online,warehouses]);
 useEffect(()=>{void reload()},[reload]);
 const filtered=useMemo(()=>{const n=query.trim().toLocaleLowerCase();return n?lines.filter(x=>[x.product_id,String(x.expected_quantity),String(x.counted_quantity??'')].join(' ').toLocaleLowerCase().includes(n)):lines},[lines,query]);
 const pages=Math.max(1,Math.ceil(filtered.length/12));const activePage=Math.min(page,pages);const visible=filtered.slice((activePage-1)*12,activePage*12);
 const counted=lines.filter(x=>x.counted_quantity!==null).length; const allCounted=lines.length>0&&counted===lines.length; const hasUnsaved=dirty.size>0; const variance=lines.reduce((s,x)=>s+(x.variance??0),0);
 const warehouseName=(id:string)=>warehouses.find(x=>x.id===id)?.name??'المستودع';
 async function begin(){if(!selectedWarehouse)return setError('اختر المستودع قبل بدء الجرد.');if(!online)return setError('لا يمكن بدء الجرد دون اتصال.');setBusy(true);setError('');setMessage('');try{const next=await startStockCount(selectedWarehouse,'agh-count-'+crypto.randomUUID(),notes);setSession(next);setLines(await getStockCountLines(next.id));setNotes('');setMessage('تم فتح جلسة الجرد.')}catch(e){setError(e instanceof Error?e.message:'تعذر بدء الجرد.')}finally{setBusy(false)}}
 async function save(line:StockCountLine){if(!session||line.counted_quantity===null||!online)return;setSaving(line.id);setError('');setMessage('');try{const saved=await setStockCountLine(session.id,line.product_id,line.counted_quantity);setLines(xs=>xs.map(x=>x.id===line.id?saved:x));setDirty(xs=>{const next=new Set(xs);next.delete(line.id);return next});setMessage('تم حفظ كمية الجرد.')}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ كمية الجرد.')}finally{setSaving(null)}}
 async function complete(){if(!session||!online)return;if(!allCounted)return setError('أدخل الكمية المعدودة لكل الأصناف قبل الإقفال.');setBusy(true);setError('');setMessage('');try{const r=await completeStockCount(session.id);setMessage('أُقفل الجرد. التسويات: '+r.adjusted_lines);await reload()}catch(e){setError(e instanceof Error?e.message:'تعذر إقفال الجرد.')}finally{setBusy(false)}}
 return <section className='stock-count-workspace' aria-labelledby='stock-count-title'><div className='stock-count-header'><div><span className='eyebrow'>Stock Count Control</span><h3 id='stock-count-title'>تشغيل جرد المخزون</h3><p>فتح الجلسة وإدخال الكميات الفعلية وحفظ الفروقات ثم الإقفال عبر عقود Commerce.</p></div><span className={online?'stock-count-status is-online':'stock-count-status is-offline'} role='status'>{online?'● متصل':'○ غير متصل'}</span></div>
 {error&&<div className='error-banner' role='alert'>{error}</div>}{message&&<div className='success' role='status'>{message}</div>}
 {!online&&<div className='stock-count-boundary'><strong>الجرد متوقف دون اتصال.</strong><span>لا توجد كتابة محلية لتفادي مصدر جرد غير موثوق.</span><button type='button' className='ghost' onClick={()=>void reload()}>إعادة المحاولة</button></div>}
 {loading?<div className='portal-loading' role='status'>جارٍ تحميل جلسة الجرد…</div>:!session?<div className='stock-count-start-card'><div className='stock-count-summary'><article><small>الحالة</small><strong>لا توجد جلسة مفتوحة</strong><span>ابدأ جردًا جديدًا.</span></article><article><small>المستودعات</small><strong>{warehouses.length.toLocaleString('ar')}</strong><span>متاحة لهذا المستخدم.</span></article></div><div className='stock-count-start-form'><label>المستودع<select value={selectedWarehouse} onChange={e=>setSelectedWarehouse(e.target.value)} disabled={!online||busy}><option value=''>اختر المستودع</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>ملاحظات البداية<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} rows={3} disabled={!online||busy}/></label><button type='button' onClick={()=>void begin()} disabled={!online||busy||!selectedWarehouse}>{busy?'جارٍ البدء…':'بدء جلسة جرد'}</button></div></div>:session.status==='open'?<div className='stock-count-active'><div className='stock-count-metrics'><article><small>المستودع</small><strong>{warehouseName(session.warehouse_id)}</strong></article><article><small>التغطية</small><strong>{counted.toLocaleString('ar')} / {lines.length.toLocaleString('ar')}</strong></article><article><small>الجاهزية</small><strong>{lines.length?Math.round(counted/lines.length*100):0}%</strong></article><article><small>إجمالي الفرق</small><strong className={variance===0?'neutral':variance>0?'positive':'negative'}>{variance.toLocaleString('ar')}</strong></article></div>
 <div className='stock-count-toolbar'><input aria-label='بحث سطور الجرد' value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder='بحث بالمعرف أو الكمية'/><button type='button' className='ghost' onClick={()=>void reload()} disabled={busy||Boolean(saving)}>تحديث</button><button type='button' onClick={()=>void complete()} disabled={busy||Boolean(saving)||!allCounted||hasUnsaved}>{busy?'جارٍ الإقفال…':'إقفال الجرد'}</button></div>
 {!lines.length?<div className='empty-state'><strong>لا توجد سطور جرد.</strong><span>أعد تحميل الجلسة أو تحقق من المستودع.</span></div>:<><div className='stock-count-table'><div className='stock-count-row stock-count-head'><span>الصنف</span><span>المتوقع</span><span>المعدود</span><span>الفرق</span><span>إجراء</span></div>{visible.map(line=><div className='stock-count-row' key={line.id}><div><strong>{line.product_id.slice(0,8)}</strong><small dir='ltr'>{line.product_id}</small></div><strong>{line.expected_quantity.toLocaleString('ar')}</strong><input aria-label={'الكمية المعدودة '+line.product_id} type='number' min='0' step='1' value={line.counted_quantity===null?'':line.counted_quantity} onChange={e=>{const raw=e.target.value;const q=raw===''?null:Number(raw);setLines(xs=>xs.map(x=>x.id===line.id?{...x,counted_quantity:q,variance:q===null?null:q-x.expected_quantity}:x));setDirty(xs=>{const next=new Set(xs);next.add(line.id);return next})}} disabled={!online||busy||saving===line.id}/><strong className={line.variance===null?'neutral':line.variance>0?'positive':line.variance<0?'negative':'neutral'}>{line.variance===null?'—':line.variance.toLocaleString('ar')}</strong><button type='button' className='ghost' onClick={()=>void save(line)} disabled={!online||busy||saving===line.id||line.counted_quantity===null}>{saving===line.id?'جارٍ الحفظ…':'حفظ'}</button></div>)}</div><div className='directory-pagination'><span>صفحة {activePage} / {pages} · {filtered.length} سطر</span><div><button type='button' className='ghost' onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={activePage===1}>السابق</button><button type='button' className='ghost' onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={activePage===pages}>التالي</button></div></div></>}</div>:<div className='stock-count-completed-card'><strong>الجلسة الحالية مكتملة</strong><span>{warehouseName(session.warehouse_id)} · {session.completed_at?new Date(session.completed_at).toLocaleString('ar-YE'):'مكتملة'}</span><button type='button' className='ghost' onClick={()=>void reload()}>تحديث السجل</button></div>}</section>;
}