import { useCallback, useEffect, useMemo, useState } from 'react';
import { getCashBalances, type CashBalance } from './services/finance';
import { createSupplierBill, getSupplierAccounting, recordSupplierPayment, type SupplierBill, type SupplierLedgerEntry, type SupplierPaymentMethod } from './services/supplierAccounting';
type Role='owner'|'admin'|'sales'|'warehouse'|'viewer';
interface Props{supplierId:string;supplierName:string;role:Role;}
const statusLabels:Record<SupplierBill['status'],string>={issued:'صادرة',partially_paid:'مدفوعة جزئيًا',paid:'مسددة',void:'ملغاة'};
const methodLabels:Record<SupplierPaymentMethod,string>={cash:'نقدًا',bank_transfer:'تحويل بنكي',card:'بطاقة',other:'أخرى'};
export default function SupplierAccountingPanel({supplierId,supplierName,role}:Props){
 const canMutate=role==='owner'||role==='admin';
 const [bills,setBills]=useState<SupplierBill[]>([]); const [entries,setEntries]=useState<SupplierLedgerEntry[]>([]);
 const [cashAccounts,setCashAccounts]=useState<CashBalance[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const [billNumber,setBillNumber]=useState(''); const [billTotal,setBillTotal]=useState(''); const [billDueAt,setBillDueAt]=useState('');
 const [paymentBillId,setPaymentBillId]=useState(''); const [paymentAmount,setPaymentAmount]=useState(''); const [paymentMethod,setPaymentMethod]=useState<SupplierPaymentMethod>('cash'); const [paymentCashAccount,setPaymentCashAccount]=useState(''); const [paymentReference,setPaymentReference]=useState('');
 const reload=useCallback(async()=>{setLoading(true);setError('');try{const accounting=await getSupplierAccounting(supplierId);setBills(accounting.bills);setEntries(accounting.entries);if(canMutate){try{setCashAccounts(await getCashBalances());}catch{setCashAccounts([]);}}}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل حساب المورد.');}finally{setLoading(false);}},[canMutate,supplierId]);
 useEffect(()=>{void reload();},[reload]);
 const balance=useMemo(()=>entries.filter(item=>item.entry_status==='posted').reduce((sum,item)=>sum+item.credit-item.debit,0),[entries]);
 const billBalance=(bill:SupplierBill)=>entries.filter(e=>e.supplier_bill_id===bill.id&&e.entry_status==='posted').reduce((sum,e)=>sum+e.credit-e.debit,0);
 async function submitBill(e:React.FormEvent){e.preventDefault();if(!canMutate||busy)return;setBusy(true);setError('');setMessage('');try{await createSupplierBill({supplierId,billNumber,total:Number(billTotal),currency:'YER',dueAt:billDueAt?new Date(billDueAt).toISOString():null,idempotencyKey:'supplier-bill:'+supplierId+':'+crypto.randomUUID()});setBillNumber('');setBillTotal('');setBillDueAt('');setMessage('تم إصدار فاتورة المورد وتسجيلها في كشف الحساب.');await reload();}catch(err){setError(err instanceof Error?err.message:'تعذر إصدار فاتورة المورد.');}finally{setBusy(false);}}
 async function submitPayment(bill:SupplierBill){if(!canMutate||busy)return;setBusy(true);setError('');setMessage('');try{await recordSupplierPayment({supplierBillId:bill.id,amount:Number(paymentAmount),method:paymentMethod,cashAccountId:paymentCashAccount||null,reference:paymentReference,idempotencyKey:'supplier-payment:'+bill.id+':'+crypto.randomUUID()});setPaymentAmount('');setPaymentReference('');setPaymentCashAccount('');setPaymentBillId('');setMessage('تم تسجيل سداد المورد وتحديث حالة الفاتورة.');await reload();}catch(err){setError(err instanceof Error?err.message:'تعذر تسجيل السداد.');}finally{setBusy(false);}}
 if(loading)return <div className="admin-card"><div className="cart-empty">جارٍ تحميل الحساب المالي للمورد…</div></div>;
 return <div className="admin-card supplier-accounting">
  <div className="section-heading"><div><span className="eyebrow">الحسابات</span><h4>كشف حساب {supplierName}</h4><small>الرصيد الدائن يعني مبلغًا مستحقًا للمورد؛ القراءة محكومة بالمؤسسة والدور.</small></div><strong>{balance.toLocaleString('ar-YE')} YER</strong></div>
  {canMutate&&<form className="admin-card" onSubmit={(e)=>void submitBill(e)}><h5>فاتورة مورد جديدة</h5><div className="admin-grid"><input aria-label="رقم فاتورة المورد" placeholder="رقم الفاتورة" value={billNumber} onChange={e=>setBillNumber(e.target.value)} required/><input aria-label="إجمالي فاتورة المورد" type="number" min="0.01" step="0.01" placeholder="الإجمالي" value={billTotal} onChange={e=>setBillTotal(e.target.value)} required/><input aria-label="تاريخ استحقاق فاتورة المورد" type="date" value={billDueAt} onChange={e=>setBillDueAt(e.target.value)}/></div><button disabled={busy}>إصدار فاتورة المورد</button></form>}
  {!bills.length?<div className="cart-empty">لا توجد فواتير مورد مسجلة لهذه الجهة.</div>:<div className="cart-lines">{bills.map(bill=><article className="cart-line" key={bill.id}><div><strong>فاتورة {bill.bill_number}</strong><small>{statusLabels[bill.status]} · {bill.due_at?'استحقاق '+new Date(bill.due_at).toLocaleDateString('ar-YE'):'بدون تاريخ استحقاق'}</small></div><div><b>{bill.total.toLocaleString('ar-YE')} {bill.currency}</b><small>متبقٍ {billBalance(bill).toLocaleString('ar-YE')} {bill.currency}</small></div>{canMutate&&bill.status!=='paid'&&bill.status!=='void'&&<button type="button" className="ghost compact-action" onClick={()=>setPaymentBillId(paymentBillId===bill.id?'':bill.id)}>سداد</button>}{paymentBillId===bill.id&&canMutate&&<div className="invite-controls"><input aria-label={'مبلغ سداد '+bill.bill_number} type="number" min="0.01" step="0.01" placeholder="مبلغ السداد" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)}/><select aria-label={'طريقة سداد '+bill.bill_number} value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as SupplierPaymentMethod)}>{Object.entries(methodLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select aria-label={'حساب نقدية '+bill.bill_number} value={paymentCashAccount} onChange={e=>setPaymentCashAccount(e.target.value)}><option value="">بدون حساب نقدية</option>{cashAccounts.filter(a=>a.currency===bill.currency).map(a=><option key={a.id} value={a.id}>{a.name} · {a.current_balance.toLocaleString('ar-YE')} {a.currency}</option>)}</select><input aria-label={'مرجع سداد '+bill.bill_number} placeholder="مرجع السداد" value={paymentReference} onChange={e=>setPaymentReference(e.target.value)}/><button type="button" disabled={busy} onClick={()=>void submitPayment(bill)}>تسجيل السداد</button></div>}</article>)}</div>}
  <div className="admin-card"><div className="section-heading"><div><h5>الحركة المالية</h5><small>فاتورة المورد تزيد الالتزام (دائن)، والسداد يخفضه (مدين).</small></div><span>{entries.length} حركة</span></div>{!entries.length?<div className="cart-empty">لا توجد حركة مالية.</div>:<div className="cart-lines">{entries.map(entry=><article className="cart-line" key={entry.id}><div><strong>{entry.description}</strong><small>{entry.reference??entry.source_type} · {new Date(entry.created_at).toLocaleString('ar-YE')}</small></div><div><span>مدين {entry.debit.toLocaleString('ar-YE')}</span><span>دائن {entry.credit.toLocaleString('ar-YE')}</span></div></article>)}</div>}</div>
  {error&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
 </div>;
}
