import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';

type UserRole='owner'|'admin'|'warehouse';
interface Supplier{id:string;name:string;phone:string|null;email:string|null;address:string|null;is_active:boolean;created_at:string;}
interface Bill{id:string;supplier_id:string;bill_number:string;status:string;currency:string;subtotal:number;total:number;due_at:string|null;notes:string|null;created_at:string;}
interface Ledger{id:string;supplier_id:string;reference:string|null;description:string;debit:number;credit:number;currency:string;due_date:string|null;entry_status:string;created_at:string;}

export default function SupplierLedgerPanel({role}:{role:UserRole}){
 const canUse=['owner','admin','warehouse'].includes(role); const [tab,setTab]=useState<'suppliers'|'bills'|'ledger'>('suppliers'); const [suppliers,setSuppliers]=useState<Supplier[]>([]); const [bills,setBills]=useState<Bill[]>([]); const [ledger,setLedger]=useState<Ledger[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [s,b,l]=await Promise.all([supabase.from('suppliers').select('id,name,phone,email,address,is_active,created_at').order('name').limit(300),supabase.from('supplier_bills').select('id,supplier_id,bill_number,status,currency,subtotal,total,due_at,notes,created_at').order('created_at',{ascending:false}).limit(300),supabase.from('supplier_ledger_entries').select('id,supplier_id,reference,description,debit,credit,currency,due_date,entry_status,created_at').order('created_at',{ascending:false}).limit(500)]);if(s.error)throw s.error;if(b.error)throw b.error;if(l.error)throw l.error;setSuppliers((s.data??[]) as Supplier[]);setBills((b.data??[]) as Bill[]);setLedger((l.data??[]) as Ledger[]);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل بيانات الموردين.');}finally{setLoading(false);}},[canUse]);
 useEffect(()=>{void reload();},[reload]);useEffect(()=>{setQuery('');},[tab]);
 const names=useMemo(()=>new Map(suppliers.map(x=>[x.id,x.name])),[suppliers]); const current=useMemo(()=>{const n=query.trim().toLocaleLowerCase();if(tab==='suppliers')return suppliers.filter(x=>!n||[x.name,x.phone??'',x.email??'',x.address??''].join(' ').toLocaleLowerCase().includes(n));if(tab==='bills')return bills.filter(x=>!n||[x.bill_number,names.get(x.supplier_id)??'',x.status,x.total,x.currency].join(' ').toLocaleLowerCase().includes(n));return ledger.filter(x=>!n||[x.reference??'',x.description,names.get(x.supplier_id)??'',x.entry_status,x.currency].join(' ').toLocaleLowerCase().includes(n));},[bills,ledger,names,query,suppliers,tab]);
 if(!canUse)return null;
 return <section className='cart-panel' id='admin-suppliers'><div className='section-heading'><div><span className='eyebrow'>Supplier Control</span><h2>الموردون وحسابهم التشغيلي</h2><p className='panel-note'>دليل الموردين والفواتير وحركة حساب المورد من البيانات التشغيلية الحالية.</p></div><span>{current.length} سجل</span></div>
 <div className='history-tabs' role='tablist'><button type='button' role='tab' aria-selected={tab==='suppliers'} className={tab==='suppliers'?'active':''} onClick={()=>setTab('suppliers')}>الموردون ({suppliers.length})</button><button type='button' role='tab' aria-selected={tab==='bills'} className={tab==='bills'?'active':''} onClick={()=>setTab('bills')}>الفواتير ({bills.length})</button><button type='button' role='tab' aria-selected={tab==='ledger'} className={tab==='ledger'?'active':''} onClick={()=>setTab('ledger')}>الحساب ({ledger.length})</button></div>
 <div className='order-queue-toolbar'><input aria-label='بحث بيانات الموردين' value={query} onChange={e=>setQuery(e.target.value)} placeholder='بحث في القسم الحالي'/><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button><button type='button' className='ghost' onClick={()=>setQuery('')} disabled={!query}>مسح</button></div>
 {loading?<div className='portal-loading' role='status'>جارٍ تحميل بيانات الموردين…</div>:error?<div className='empty-state'><strong>تعذر تحميل بيانات الموردين.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!current.length?<div className='empty-state'><strong>{query?'لا توجد نتائج مطابقة.':'لا توجد سجلات في هذا القسم بعد.'}</strong><span>{query?'غيّر عبارة البحث.':'ستظهر البيانات هنا بعد إنشاء المورد أو الفاتورة أو الحركة.'}</span></div>:<div className='cart-lines'>{tab==='suppliers'&&current.map(x=><article className='cart-line' key={x.id}><div><strong>{x.name}</strong><small>{x.phone??'بدون هاتف'} · {x.email??'بدون بريد'}</small></div><div><strong>{x.is_active?'نشط':'موقوف'}</strong><small>{x.address??'بدون عنوان'}</small></div></article>)}{tab==='bills'&&current.map(x=><article className='cart-line' key={x.id}><div><strong>فاتورة {x.bill_number}</strong><small>{names.get(x.supplier_id)??'مورد'} · {x.status}</small></div><div><strong>{x.total} {x.currency}</strong><small>{x.due_at?'استحقاق '+x.due_at.slice(0,10):'بدون استحقاق'}</small></div></article>)}{tab==='ledger'&&current.map(x=><article className='cart-line' key={x.id}><div><strong>{x.description}</strong><small>{names.get(x.supplier_id)??'مورد'} · {x.reference??'بدون مرجع'}</small></div><div><strong>{x.debit?x.debit+' مدين':x.credit+' دائن'} {x.currency}</strong><small>{x.due_date??'—'} · {x.entry_status}</small></div></article>)}</div>}
 </section>;
}