import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import { updateWarehouse } from './services/purchasing';
import RecordDetailDrawer from './RecordDetailDrawer';

type UserRole='owner'|'admin'|'warehouse';
interface Warehouse{id:string;name:string;branch_id:string;is_active:boolean;created_at:string;}

export default function WarehouseDirectoryPanel({role}:{role:UserRole}){
 const canUse=['owner','admin','warehouse'].includes(role); const canEdit=role==='owner'||role==='admin'; const [warehouses,setWarehouses]=useState<Warehouse[]>([]); const [branches,setBranches]=useState<Map<string,string>>(new Map()); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [page,setPage]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selectedWarehouse,setSelectedWarehouse]=useState<Warehouse|null>(null); const [editingWarehouse,setEditingWarehouse]=useState<Warehouse|null>(null); const [warehouseName,setWarehouseName]=useState(''); const [warehouseBranchId,setWarehouseBranchId]=useState(''); const [warehouseActive,setWarehouseActive]=useState(true); const [editBusy,setEditBusy]=useState(false); const [editError,setEditError]=useState<string|null>(null); const [editMessage,setEditMessage]=useState<string|null>(null); const [branchRows,setBranchRows]=useState<Array<{id:string;name:string;is_active:boolean}>>([]);
 const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [w,b]=await Promise.all([supabase.from('warehouses').select('id,name,branch_id,is_active,created_at').order('created_at'),supabase.from('branches').select('id,name,is_active').order('created_at')]);if(w.error)throw w.error;if(b.error)throw b.error;setWarehouses((w.data??[]) as Warehouse[]);setBranches(new Map((b.data??[]).map(x=>[x.id,x.name]))); setBranchRows((b.data??[]) as Array<{id:string;name:string;is_active:boolean}>);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل دليل المستودعات.');}finally{setLoading(false);}},[canUse]);
 useEffect(()=>{void reload();},[reload]); useEffect(()=>{setPage(1);},[query,status]);
 function startWarehouseEdit(warehouse: Warehouse){ if(!canEdit)return; setEditingWarehouse(warehouse); setWarehouseName(warehouse.name); setWarehouseBranchId(warehouse.branch_id); setWarehouseActive(warehouse.is_active); setEditError(null); setEditMessage(null); setSelectedWarehouse(null); }
 async function saveWarehouse(event: React.FormEvent<HTMLFormElement>){ event.preventDefault(); if(!editingWarehouse||editBusy)return; setEditBusy(true); setEditError(null); setEditMessage(null); try{ await updateWarehouse({warehouseId:editingWarehouse.id,name:warehouseName,branchId:warehouseBranchId,isActive:warehouseActive}); setEditMessage('تم تحديث المستودع وتسجيل أثر العملية.'); setEditingWarehouse(null); await reload(); }catch(e){setEditError(e instanceof Error?e.message:'تعذر تحديث المستودع.');}finally{setEditBusy(false);} }

 const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return warehouses.filter(w=>(status==='all'||(status==='active'&&w.is_active)||(status==='inactive'&&!w.is_active))&&(!needle||[w.name,branches.get(w.branch_id)??''].join(' ').toLocaleLowerCase().includes(needle)));},[branches,query,status,warehouses]);
 const pages=Math.max(1,Math.ceil(filtered.length/10)); const activePage=Math.min(page,pages); const visible=filtered.slice((activePage-1)*10,activePage*10); if(!canUse)return null;
 return <section className='cart-panel' id='admin-warehouses'><div className='section-heading'><div><span className='eyebrow'>Warehouse Control</span><h2>دليل المستودعات والفروع</h2><p className='panel-note'>المستودعات التشغيلية المرتبطة بالفروع والحالة الحالية.</p></div><span>{filtered.length}/{warehouses.length} مستودع</span></div>
 <div className='order-queue-toolbar'><input aria-label='بحث المستودعات' value={query} onChange={e=>setQuery(e.target.value)} placeholder='اسم المستودع أو الفرع'/><select aria-label='حالة المستودع' value={status} onChange={e=>setStatus(e.target.value)}><option value='all'>كل الحالات</option><option value='active'>نشط</option><option value='inactive'>موقوف</option></select><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button></div>
 {loading?<div className='portal-loading' role='status'>جارٍ تحميل دليل المستودعات…</div>:error?<div className='empty-state'><strong>تعذر تحميل دليل المستودعات.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!filtered.length?<div className='empty-state'><strong>{warehouses.length?'لا توجد نتائج مطابقة.':'لا توجد مستودعات مهيأة.'}</strong><span>{warehouses.length?'غيّر البحث أو الحالة.':'ستظهر المستودعات هنا عند تجهيزها للمؤسسة.'}</span></div>:<div className='cart-lines'>{visible.map(w=><article className='cart-line' key={w.id}><div><strong>{w.name}</strong><small>الفرع: {branches.get(w.branch_id)??'غير معروف'}</small></div><div><strong>{w.is_active?'نشط':'موقوف'}</strong><small>أُنشئ {w.created_at.slice(0,10)}</small></div><div className='status-actions'><button type='button' className='ghost' onClick={()=>setSelectedWarehouse(w)}>التفاصيل</button>{canEdit&&<button type='button' className='ghost' onClick={()=>startWarehouseEdit(w)}>تعديل</button>}</div></article>)}</div>}
 {editingWarehouse&&<form className='admin-inline-editor' onSubmit={saveWarehouse} aria-label='تعديل المستودع'><div className='section-heading'><div><span className='eyebrow'>Warehouse Edit</span><h3>تعديل المستودع</h3><p className='panel-note'>يتطلب التعديل صلاحية مالك أو مدير، ويُحفظ عبر RPC مدقق.</p></div><button type='button' className='ghost' onClick={()=>setEditingWarehouse(null)} disabled={editBusy}>إلغاء</button></div><div className='admin-inline-editor-grid'><label>اسم المستودع<input value={warehouseName} onChange={e=>setWarehouseName(e.target.value)} maxLength={200} required/></label><label>الفرع<select value={warehouseBranchId} onChange={e=>setWarehouseBranchId(e.target.value)} required>{branchRows.filter(b=>b.is_active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className='admin-checkbox-field'><input type='checkbox' checked={warehouseActive} onChange={e=>setWarehouseActive(e.target.checked)}/><span>المستودع نشط</span></label></div>{editError&&<div className='empty-state' role='alert'><strong>تعذر الحفظ</strong><span>{editError}</span></div>}{editMessage&&<div className='success' role='status'>{editMessage}</div>}<button type='submit' disabled={editBusy}>{editBusy?'جارٍ الحفظ…':'حفظ التعديلات'}</button></form>}
 {editingWarehouse&&editMessage&&null}
 {selectedWarehouse&&<RecordDetailDrawer eyebrow='Warehouse Control' title={selectedWarehouse.name} summary={selectedWarehouse.is_active?'مستودع نشط':'مستودع موقوف'} fields={[{label:'الفرع',value:branches.get(selectedWarehouse.branch_id)??'غير معروف'},{label:'الحالة',value:selectedWarehouse.is_active?'نشط':'موقوف'},{label:'تاريخ الإنشاء',value:new Date(selectedWarehouse.created_at).toLocaleString('ar-YE')},{label:'المعرّف',value:selectedWarehouse.id},{label:'معرّف الفرع',value:selectedWarehouse.branch_id}]} onClose={()=>setSelectedWarehouse(null)}/>}
 <div className='directory-pagination'><span>صفحة {activePage} / {pages} · {filtered.length} مستودع</span><div><button type='button' className='ghost' onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={activePage===1}>السابق</button><button type='button' className='ghost' onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={activePage===pages}>التالي</button></div></div>
 </section>;
}