import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import RecordDetailDrawer from './RecordDetailDrawer';

type UserRole='owner'|'admin'|'warehouse';
interface Warehouse{id:string;name:string;branch_id:string;is_active:boolean;created_at:string;}
interface Branch{id:string;name:string;is_active:boolean;}

export default function WarehouseDirectoryPanel({role}:{role:UserRole}){
 const canUse=['owner','admin','warehouse'].includes(role); const [warehouses,setWarehouses]=useState<Warehouse[]>([]); const [branches,setBranches]=useState<Map<string,string>>(new Map()); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selectedWarehouse,setSelectedWarehouse]=useState<Warehouse|null>(null);
 const reload=useCallback(async()=>{if(!supabase||!canUse){setLoading(false);return;}setLoading(true);setError(null);try{const [w,b]=await Promise.all([supabase.from('warehouses').select('id,name,branch_id,is_active,created_at').order('created_at'),supabase.from('branches').select('id,name,is_active').order('created_at')]);if(w.error)throw w.error;if(b.error)throw b.error;setWarehouses((w.data??[]) as Warehouse[]);setBranches(new Map((b.data??[]).map(x=>[x.id,x.name])));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل دليل المستودعات.');}finally{setLoading(false);}},[canUse]);
 useEffect(()=>{void reload();},[reload]);
 const filtered=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return warehouses.filter(w=>(status==='all'||(status==='active'&&w.is_active)||(status==='inactive'&&!w.is_active))&&(!needle||[w.name,branches.get(w.branch_id)??''].join(' ').toLocaleLowerCase().includes(needle)));},[branches,query,status,warehouses]);
 if(!canUse)return null;
 return <section className='cart-panel' id='admin-warehouses'><div className='section-heading'><div><span className='eyebrow'>Warehouse Control</span><h2>دليل المستودعات والفروع</h2><p className='panel-note'>المستودعات التشغيلية المرتبطة بالفروع والحالة الحالية.</p></div><span>{filtered.length}/{warehouses.length} مستودع</span></div>
 <div className='order-queue-toolbar'><input aria-label='بحث المستودعات' value={query} onChange={e=>setQuery(e.target.value)} placeholder='اسم المستودع أو الفرع'/><select aria-label='حالة المستودع' value={status} onChange={e=>setStatus(e.target.value)}><option value='all'>كل الحالات</option><option value='active'>نشط</option><option value='inactive'>موقوف</option></select><button type='button' className='ghost' onClick={()=>void reload()} disabled={loading}>إعادة تحميل</button></div>
 {loading?<div className='portal-loading' role='status'>جارٍ تحميل دليل المستودعات…</div>:error?<div className='empty-state'><strong>تعذر تحميل دليل المستودعات.</strong><span>{error}</span><button type='button' onClick={()=>void reload()}>إعادة المحاولة</button></div>:!filtered.length?<div className='empty-state'><strong>{warehouses.length?'لا توجد نتائج مطابقة.':'لا توجد مستودعات مهيأة.'}</strong><span>{warehouses.length?'غيّر البحث أو الحالة.':'ستظهر المستودعات هنا عند تجهيزها للمؤسسة.'}</span></div>:<div className='cart-lines'>{filtered.map(w=><article className='cart-line' key={w.id}><div><strong>{w.name}</strong><small>الفرع: {branches.get(w.branch_id)??'غير معروف'}</small></div><div><strong>{w.is_active?'نشط':'موقوف'}</strong><small>أُنشئ {w.created_at.slice(0,10)}</small></div><button type='button' className='ghost' onClick={()=>setSelectedWarehouse(w)}>التفاصيل</button></article>)}</div>}
 {selectedWarehouse&&<RecordDetailDrawer eyebrow='Warehouse Control' title={selectedWarehouse.name} summary={selectedWarehouse.is_active?'مستودع نشط':'مستودع موقوف'} fields={[{label:'الفرع',value:branches.get(selectedWarehouse.branch_id)??'غير معروف'},{label:'الحالة',value:selectedWarehouse.is_active?'نشط':'موقوف'},{label:'تاريخ الإنشاء',value:new Date(selectedWarehouse.created_at).toLocaleString('ar-YE')},{label:'المعرّف',value:selectedWarehouse.id},{label:'معرّف الفرع',value:selectedWarehouse.branch_id}]} onClose={()=>setSelectedWarehouse(null)}/>}
 </section>;
}