-- Aghbari R1 transactional foundation.
-- Bounded implementation slice: tenant/scope + catalog + tier pricing + inventory + orders.
-- Runtime authority remains server/database-side; client totals/prices are never trusted.

create extension if not exists pgcrypto;
create schema if not exists app;
create type app.order_status as enum ('draft','pending','confirmed','processing','ready','delivered','cancelled');

create table app.organizations (id uuid primary key default gen_random_uuid(), name text not null check (length(trim(name)) > 0), created_at timestamptz not null default now());
create table app.branches (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete restrict, name text not null, active boolean not null default true, created_at timestamptz not null default now(), unique (organization_id, name));
create table app.warehouses (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete restrict, branch_id uuid not null references app.branches(id) on delete restrict, name text not null, active boolean not null default true, created_at timestamptz not null default now(), unique (organization_id, name));
create table app.roles (id uuid primary key default gen_random_uuid(), code text not null unique, description text not null default '');
create table app.users (id uuid primary key, display_name text not null, active boolean not null default true, created_at timestamptz not null default now());
create table app.user_roles (user_id uuid not null references app.users(id) on delete cascade, organization_id uuid not null references app.organizations(id) on delete cascade, role_id uuid not null references app.roles(id) on delete restrict, branch_id uuid references app.branches(id) on delete restrict, warehouse_id uuid references app.warehouses(id) on delete restrict, created_at timestamptz not null default now(), primary key (user_id, organization_id, role_id));
create unique index user_roles_scope_uq on app.user_roles (user_id, organization_id, role_id, coalesce(branch_id, '00000000-0000-0000-0000-000000000000'::uuid), coalesce(warehouse_id, '00000000-0000-0000-0000-000000000000'::uuid));
create table app.customer_tiers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, code text not null, name text not null, active boolean not null default true, unique (organization_id, code));
create table app.customers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, name text not null, customer_tier_id uuid not null references app.customer_tiers(id) on delete restrict, active boolean not null default true, created_at timestamptz not null default now());
create table app.categories (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, parent_id uuid references app.categories(id) on delete restrict, name text not null, active boolean not null default true, unique (organization_id, parent_id, name));
create table app.products (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, category_id uuid references app.categories(id) on delete restrict, sku text not null, name text not null, description text not null default '', unit text not null default 'unit', image_path text, status text not null default 'active' check (status in ('active','inactive','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, sku));
create table app.product_identifiers (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, product_id uuid not null references app.products(id) on delete cascade, identifier_type text not null check (identifier_type in ('sku','barcode','item_number')), value text not null, unique (organization_id, identifier_type, value));
create table app.price_lists (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, customer_tier_id uuid not null references app.customer_tiers(id) on delete restrict, code text not null, currency char(3) not null default 'YER', active boolean not null default true, unique (organization_id, code), unique (organization_id, customer_tier_id));
create table app.product_prices (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, price_list_id uuid not null references app.price_lists(id) on delete cascade, product_id uuid not null references app.products(id) on delete cascade, unit_price numeric(14,2) not null check (unit_price >= 0), effective_from timestamptz not null default now(), effective_to timestamptz, check (effective_to is null or effective_to > effective_from), unique (organization_id, price_list_id, product_id, effective_from));
create table app.inventory_balances (organization_id uuid not null references app.organizations(id) on delete cascade, warehouse_id uuid not null references app.warehouses(id) on delete restrict, product_id uuid not null references app.products(id) on delete restrict, quantity numeric(14,3) not null default 0 check (quantity >= 0), updated_at timestamptz not null default now(), primary key (warehouse_id, product_id));
create table app.inventory_movements (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, warehouse_id uuid not null references app.warehouses(id) on delete restrict, product_id uuid not null references app.products(id) on delete restrict, movement_type text not null check (movement_type in ('receipt','sale','adjustment','reservation','release')), quantity_delta numeric(14,3) not null check (quantity_delta <> 0), source_type text not null, source_id uuid, actor_id uuid not null references app.users(id) on delete restrict, reason text not null, created_at timestamptz not null default now());
create table app.orders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete restrict, customer_id uuid not null references app.customers(id) on delete restrict, warehouse_id uuid not null references app.warehouses(id) on delete restrict, order_number bigint generated always as identity unique, status app.order_status not null default 'pending', currency char(3) not null default 'YER', subtotal numeric(14,2) not null check (subtotal >= 0), total numeric(14,2) not null check (total >= 0), operation_id uuid not null, payload_hash text not null, created_by uuid not null references app.users(id) on delete restrict, created_at timestamptz not null default now(), unique (organization_id, operation_id));
create table app.order_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, order_id uuid not null references app.orders(id) on delete cascade, product_id uuid not null references app.products(id) on delete restrict, quantity numeric(14,3) not null check (quantity > 0), unit_price numeric(14,2) not null check (unit_price >= 0), line_total numeric(14,2) generated always as (round(quantity * unit_price, 2)) stored, pricing_context jsonb not null default '{}'::jsonb);
create table app.order_status_history (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, order_id uuid not null references app.orders(id) on delete cascade, from_status app.order_status, to_status app.order_status not null, actor_id uuid not null references app.users(id) on delete restrict, created_at timestamptz not null default now());
create table app.audit_events (id uuid primary key default gen_random_uuid(), organization_id uuid references app.organizations(id) on delete set null, actor_id uuid references app.users(id) on delete set null, event_type text not null, entity_type text not null, entity_id uuid, correlation_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table app.outbox_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references app.organizations(id) on delete cascade, event_type text not null, aggregate_type text not null, aggregate_id uuid not null, correlation_id uuid not null, payload jsonb not null, created_at timestamptz not null default now(), published_at timestamptz, attempts integer not null default 0 check (attempts >= 0), next_attempt_at timestamptz, terminal_failure boolean not null default false);

create index branches_org_idx on app.branches (organization_id, active);
create index warehouses_org_branch_idx on app.warehouses (organization_id, branch_id, active);
create index customers_org_idx on app.customers (organization_id, customer_tier_id, active);
create index products_org_category_idx on app.products (organization_id, category_id, status);
create index identifiers_lookup_idx on app.product_identifiers (organization_id, identifier_type, value);
create index prices_lookup_idx on app.product_prices (organization_id, price_list_id, product_id, effective_from desc);
create index inventory_org_product_idx on app.inventory_balances (organization_id, product_id);
create index inventory_movements_scope_time_idx on app.inventory_movements (organization_id, warehouse_id, product_id, created_at desc);
create index orders_scope_time_idx on app.orders (organization_id, created_at desc, status);
create index orders_customer_time_idx on app.orders (organization_id, customer_id, created_at desc);
create index order_items_order_idx on app.order_items (organization_id, order_id);
create index outbox_ready_idx on app.outbox_events (published_at, terminal_failure, next_attempt_at, created_at);
create index audit_entity_time_idx on app.audit_events (organization_id, entity_type, entity_id, created_at desc);

create or replace function app.current_actor_id() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create or replace function app.current_organization_id() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.org_id', true), '')::uuid $$;
create or replace function app.current_customer_id() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.customer_id', true), '')::uuid $$;
create or replace function app.is_org_member(p_org uuid) returns boolean language sql stable security invoker set search_path = app, public as $$ select exists (select 1 from app.user_roles ur where ur.organization_id=p_org and ur.user_id=app.current_actor_id()) $$;
create or replace function app.resolve_price(p_product uuid) returns table(unit_price numeric(14,2), currency char(3), tier_id uuid) language sql stable security invoker set search_path=app,public as $$ select pp.unit_price,pl.currency,ct.id from app.customers c join app.customer_tiers ct on ct.id=c.customer_tier_id join app.price_lists pl on pl.organization_id=c.organization_id and pl.customer_tier_id=ct.id and pl.active join app.product_prices pp on pp.organization_id=c.organization_id and pp.price_list_id=pl.id and pp.product_id=p_product where c.id=app.current_customer_id() and c.organization_id=app.current_organization_id() and c.active and pp.effective_from<=now() and (pp.effective_to is null or pp.effective_to>now()) order by pp.effective_from desc limit 1 $$;

create or replace function app.create_order(p_operation_id uuid,p_product_id uuid,p_quantity numeric,p_warehouse_id uuid) returns table(order_id uuid,order_number bigint,total numeric(14,2),replayed boolean)
language plpgsql security invoker set search_path=app,public as $$
declare v_org uuid:=app.current_organization_id(); v_actor uuid:=app.current_actor_id(); v_customer uuid:=app.current_customer_id(); v_price record; v_stock numeric(14,3); v_existing app.orders%rowtype; v_hash text;
begin
  if v_org is null or v_actor is null or v_customer is null then raise exception 'authentication context required' using errcode='28000'; end if;
  if p_quantity<=0 then raise exception 'invalid quantity' using errcode='22023'; end if;
  if not app.is_org_member(v_org) then raise exception 'forbidden' using errcode='42501'; end if;
  if not exists(select 1 from app.customers where id=v_customer and organization_id=v_org and active) then raise exception 'customer not found' using errcode='P0002'; end if;
  if not exists(select 1 from app.warehouses where id=p_warehouse_id and organization_id=v_org and active) then raise exception 'warehouse not found' using errcode='P0002'; end if;
  if not exists(select 1 from app.products where id=p_product_id and organization_id=v_org and status='active') then raise exception 'product not found' using errcode='P0002'; end if;
  v_hash:=encode(digest(format('%s|%s|%s',p_product_id,p_quantity,p_warehouse_id),'sha256'),'hex');
  perform pg_advisory_xact_lock(hashtextextended(p_operation_id::text,0));
  select * into v_existing from app.orders where organization_id=v_org and operation_id=p_operation_id;
  if found then if v_existing.payload_hash<>v_hash then raise exception 'operation_id replay payload conflict' using errcode='23505'; end if; return query select v_existing.id,v_existing.order_number,v_existing.total,true; return; end if;
  select * into v_price from app.resolve_price(p_product_id);
  if not found then raise exception 'authorized price not found' using errcode='P0002'; end if;
  select quantity into v_stock from app.inventory_balances where organization_id=v_org and warehouse_id=p_warehouse_id and product_id=p_product_id for update;
  if not found or v_stock<p_quantity then raise exception 'insufficient inventory' using errcode='P0001'; end if;
  insert into app.orders(organization_id,customer_id,warehouse_id,status,currency,subtotal,total,operation_id,payload_hash,created_by) values(v_org,v_customer,p_warehouse_id,'pending',v_price.currency,round(p_quantity*v_price.unit_price,2),round(p_quantity*v_price.unit_price,2),p_operation_id,v_hash,v_actor) returning id,orders.order_number,orders.total into order_id,order_number,total;
  insert into app.order_items(organization_id,order_id,product_id,quantity,unit_price,pricing_context) values(v_org,order_id,p_product_id,p_quantity,v_price.unit_price,jsonb_build_object('customer_tier_id',v_price.tier_id));
  update app.inventory_balances set quantity=quantity-p_quantity,updated_at=now() where organization_id=v_org and warehouse_id=p_warehouse_id and product_id=p_product_id;
  insert into app.inventory_movements(organization_id,warehouse_id,product_id,movement_type,quantity_delta,source_type,source_id,actor_id,reason) values(v_org,p_warehouse_id,p_product_id,'sale',-p_quantity,'order',order_id,v_actor,'order creation');
  insert into app.order_status_history(organization_id,order_id,from_status,to_status,actor_id) values(v_org,order_id,null,'pending',v_actor);
  insert into app.audit_events(organization_id,actor_id,event_type,entity_type,entity_id,correlation_id,metadata) values(v_org,v_actor,'order.created','order',order_id,p_operation_id,jsonb_build_object('quantity',p_quantity,'unit_price',v_price.unit_price,'total',total));
  insert into app.outbox_events(organization_id,event_type,aggregate_type,aggregate_id,correlation_id,payload) values(v_org,'order.created.v1','order',order_id,p_operation_id,jsonb_build_object('order_id',order_id,'order_number',order_number));
  replayed:=false; return next;
end; $$;

alter table app.organizations enable row level security; alter table app.branches enable row level security; alter table app.warehouses enable row level security; alter table app.users enable row level security; alter table app.roles enable row level security; alter table app.user_roles enable row level security; alter table app.customer_tiers enable row level security; alter table app.customers enable row level security; alter table app.categories enable row level security; alter table app.products enable row level security; alter table app.product_identifiers enable row level security; alter table app.price_lists enable row level security; alter table app.product_prices enable row level security; alter table app.inventory_balances enable row level security; alter table app.inventory_movements enable row level security; alter table app.orders enable row level security; alter table app.order_items enable row level security; alter table app.order_status_history enable row level security; alter table app.audit_events enable row level security; alter table app.outbox_events enable row level security;
create policy user_self_roles on app.user_roles for select to public using(user_id=app.current_actor_id());
create policy org_member_select on app.organizations for select to public using(id=app.current_organization_id() and app.is_org_member(id));
create policy org_scoped_select on app.branches for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy org_scoped_select on app.warehouses for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy user_self_select on app.users for select to public using(id=app.current_actor_id());
create policy role_select on app.roles for select to public using(exists(select 1 from app.user_roles ur where ur.role_id=id and ur.user_id=app.current_actor_id()));
create policy tier_select on app.customer_tiers for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy customer_self_select on app.customers for select to public using(id=app.current_customer_id() and organization_id=app.current_organization_id());
create policy catalog_select on app.categories for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy product_select on app.products for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy identifier_select on app.product_identifiers for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy price_list_select on app.price_lists for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy product_price_select on app.product_prices for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy inventory_select on app.inventory_balances for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy movement_select on app.inventory_movements for select to public using(organization_id=app.current_organization_id() and app.is_org_member(organization_id));
create policy order_select on app.orders for select to public using(organization_id=app.current_organization_id() and (customer_id=app.current_customer_id() or app.is_org_member(organization_id)));
create policy order_item_select on app.order_items for select to public using(organization_id=app.current_organization_id() and exists(select 1 from app.orders o where o.id=order_id and (o.customer_id=app.current_customer_id() or app.is_org_member(o.organization_id))));
create policy order_history_select on app.order_status_history for select to public using(organization_id=app.current_organization_id() and exists(select 1 from app.orders o where o.id=order_id and (o.customer_id=app.current_customer_id() or app.is_org_member(o.organization_id))));

revoke all on all tables in schema app from public;
revoke all on function app.create_order(uuid,uuid,numeric,uuid) from public;
revoke all on function app.resolve_price(uuid) from public;
do $$ begin if exists(select 1 from pg_roles where rolname='authenticated') then execute 'grant usage on schema app to authenticated'; execute 'grant select on app.organizations,app.branches,app.warehouses,app.users,app.roles,app.user_roles,app.customer_tiers,app.customers,app.categories,app.products,app.product_identifiers,app.price_lists,app.product_prices,app.inventory_balances,app.inventory_movements,app.orders,app.order_items,app.order_status_history to authenticated'; execute 'grant execute on function app.create_order(uuid,uuid,numeric,uuid),app.resolve_price(uuid) to authenticated'; end if; end $$;
