-- Lock canonical RPC execution to authenticated callers only.
-- PUBLIC grants are removed first; authenticated access is then explicitly retained.
revoke execute on function public.adjust_inventory(uuid,uuid,integer,text) from public;
revoke execute on function public.clear_cart() from public;
revoke execute on function public.commit_product_import(uuid,uuid) from public;
revoke execute on function public.create_category(text,text,uuid) from public;
revoke execute on function public.create_order(text,uuid,jsonb) from public;
revoke execute on function public.current_customer_id() from public;
revoke execute on function public.current_organization_id() from public;
revoke execute on function public.current_role() from public;
revoke execute on function public.get_cart() from public;
revoke execute on function public.get_catalog(text,uuid,integer,integer) from public;
revoke execute on function public.get_or_create_cart() from public;
revoke execute on function public.is_staff() from public;
revoke execute on function public.remove_cart_item(uuid) from public;
revoke execute on function public.set_cart_item(uuid,integer) from public;
revoke execute on function public.set_product_price(uuid,public.customer_tier,numeric,text) from public;
revoke execute on function public.stage_product_import(text,text,jsonb) from public;
revoke execute on function public.transition_order(uuid,public.order_status) from public;
revoke execute on function public.upsert_product(uuid,text,text,text,uuid,text,text) from public;

grant execute on function public.adjust_inventory(uuid,uuid,integer,text) to authenticated;
grant execute on function public.clear_cart() to authenticated;
grant execute on function public.commit_product_import(uuid,uuid) to authenticated;
grant execute on function public.create_category(text,text,uuid) to authenticated;
grant execute on function public.create_order(text,uuid,jsonb) to authenticated;
grant execute on function public.current_customer_id() to authenticated;
grant execute on function public.current_organization_id() to authenticated;
grant execute on function public.current_role() to authenticated;
grant execute on function public.get_cart() to authenticated;
grant execute on function public.get_catalog(text,uuid,integer,integer) to authenticated;
grant execute on function public.get_or_create_cart() to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.remove_cart_item(uuid) to authenticated;
grant execute on function public.set_cart_item(uuid,integer) to authenticated;
grant execute on function public.set_product_price(uuid,public.customer_tier,numeric,text) to authenticated;
grant execute on function public.stage_product_import(text,text,jsonb) to authenticated;
grant execute on function public.transition_order(uuid,public.order_status) to authenticated;
grant execute on function public.upsert_product(uuid,text,text,text,uuid,text,text) to authenticated;
