-- Legacy finance migration intentionally retired on the closure lineage.
--
-- This migration referenced the former `sales_invoices` / `companies` schema before
-- that schema existed in a fresh database, making the migration history internally
-- inconsistent. The authoritative operational finance model is established later in
-- `0032_finance_invoices_cash_expenses.sql` and subsequent hardening migrations.
--
-- Keep this version as a no-op so historical ordering remains stable while a fresh
-- database can deterministically replay the complete current migration lineage.
