-- Retired obsolete company-schema customer/order repair.
-- Current order/customer command contracts are organization-scoped in the authoritative chain.
-- This historical migration is intentionally inert on fresh replay.
