-- Retired obsolete company-schema KPI migration.
-- Current dashboard metrics are defined on the organization-scoped operational model.
-- This historical repair referenced removed companies/company_id columns and is intentionally inert on fresh replay.
