-- Retired obsolete company-schema dashboard access hardening.
-- Current staff access is enforced by the organization-scoped dashboard contract.
-- This historical migration referenced removed company memberships and is intentionally inert.
