-- Intentionally retained as a no-op migration for history compatibility.
-- The previous implementation referenced public.operation_idempotency,
-- which is not part of the canonical schema and caused clean replay to fail.
-- There is no canonical operation_idempotency table/type or supported runtime
-- surface for this helper, so the migration must not introduce a dependency
-- on that legacy surface.