-- Retired legacy company-based order command repair.
-- The authoritative create_order RPC is organization-scoped and was already hardened
-- in the active operational command chain. The historical repair targeted removed
-- companies/customer_price_tiers columns and must remain a no-op on fresh replay.
-- No database objects are changed here intentionally.
