-- Superseded: authoritative commerce order lifecycle is defined in migrations 0001-0017
-- using organizations/order_status_history/outbox_events, not the retired company schema.
-- This historical compatibility migration is intentionally a no-op for clean-source replay.
