-- Performance hardening identified by Supabase advisors.
-- This migration intentionally contains no legacy table references.
-- The advisor findings that motivated it referred to tables which are not part of
-- the canonical clean migration chain. Encoding those references would make
-- `supabase db reset --local` fail on an empty database.
