-- Retired legacy company-based order lifecycle migration.
-- The authoritative order/inventory command surface is defined by the organization-scoped
-- operational core plus the earlier hardening migrations. This historical migration depended
-- on the removed companies/company_memberships schema and must remain a no-op on fresh replay.
-- No database objects are changed here intentionally.
