-- Superseded: authoritative commerce order commands are defined by the 0001-0017
-- organization-based schema and later hardened command migrations.
-- This stale company-schema compatibility rewrite is intentionally a no-op.
