-- Retired obsolete company-schema transition-order role gate.
-- Current transition_order is maintained by the organization-scoped authoritative order chain.
-- This historical company_memberships repair is intentionally inert on fresh replay.
